window.APPS_3 = [
// Photography
{id:601,name:"Lightroom Web",url:"lightroom.adobe.com",desc:"Adobe's cloud-based photo editing suite.",r:4.7,cat:"Photography",p:0},
{id:602,name:"VSCO",url:"vsco.co",desc:"Film-inspired filters and photo editing tools.",r:4.5,cat:"Photography",p:0},
{id:603,name:"Polarr",url:"polarr.com",desc:"AI-powered photo editor with smart filters.",r:4.4,cat:"Photography",p:0},
{id:604,name:"Fotor",url:"fotor.com",desc:"Online photo editor with collage and design.",r:4.3,cat:"Photography",p:0},
{id:605,name:"Photopea",url:"photopea.com",desc:"Free Photoshop-compatible browser editor.",r:4.8,cat:"Photography",p:0},
{id:606,name:"Pixlr",url:"pixlr.com",desc:"Fast AI-enhanced photo editing in browser.",r:4.3,cat:"Photography",p:0},
{id:607,name:"BeFunky",url:"befunky.com",desc:"Photo editor, collage maker, and designer.",r:4.2,cat:"Photography",p:0},
{id:608,name:"Adobe Stock",url:"stock.adobe.com",desc:"Premium stock photos, videos, and assets.",r:4.6,cat:"Photography",p:0},
{id:609,name:"Shutterstock",url:"shutterstock.com",desc:"Huge library of licensed stock imagery.",r:4.5,cat:"Photography",p:0},
{id:610,name:"Getty Images",url:"gettyimages.com",desc:"World's leading press and editorial photos.",r:4.6,cat:"Photography",p:0},
{id:611,name:"500px",url:"500px.com",desc:"Community for pro photographers to showcase.",r:4.4,cat:"Photography",p:0},
{id:612,name:"Flickr",url:"flickr.com",desc:"Photo sharing community with vast archives.",r:4.2,cat:"Photography",p:0},
{id:613,name:"SmugMug",url:"smugmug.com",desc:"Pro photo portfolio and client galleries.",r:4.4,cat:"Photography",p:0},
{id:614,name:"Unsplash",url:"unsplash.com",desc:"Free high-resolution photos for any use.",r:4.8,cat:"Photography",p:0},
{id:615,name:"Pexels",url:"pexels.com",desc:"Free stock photos and videos by creators.",r:4.7,cat:"Photography",p:0},
{id:616,name:"Depositphotos",url:"depositphotos.com",desc:"Affordable stock photos and vector images.",r:4.3,cat:"Photography",p:0},
{id:617,name:"Stocksy",url:"stocksy.com",desc:"Artist-owned co-op premium stock photos.",r:4.5,cat:"Photography",p:0},
{id:618,name:"EyeEm",url:"eyeem.com",desc:"Photography community with AI image search.",r:4.1,cat:"Photography",p:0},
{id:619,name:"Zenfolio",url:"zenfolio.com",desc:"Portfolio websites and client proofing tools.",r:4.3,cat:"Photography",p:0},
{id:620,name:"Google Photos",url:"photos.google.com",desc:"Smart photo storage with AI organization.",r:4.6,cat:"Photography",p:0},
{id:621,name:"Imgix",url:"imgix.com",desc:"Real-time image processing and delivery CDN.",r:4.5,cat:"Photography",p:0},
{id:622,name:"Cloudinary",url:"cloudinary.com",desc:"Media management with transforms and CDN.",r:4.7,cat:"Photography",p:0},
{id:623,name:"TinyPNG",url:"tinypng.com",desc:"Smart PNG and JPEG compression tool.",r:4.8,cat:"Photography",p:0},
{id:624,name:"Squoosh",url:"squoosh.app",desc:"Browser-based image compression by Google.",r:4.7,cat:"Photography",p:0},
{id:625,name:"SVGOMG",url:"jakearchibald.github.io/svgomg",desc:"SVG optimizer with live preview controls.",r:4.7,cat:"Photography",p:0},
// Writing & Blogging
{id:626,name:"Medium",url:"medium.com",desc:"Publishing platform for ideas and stories.",r:4.4,cat:"Writing & Blogging",p:0},
{id:627,name:"Substack",url:"substack.com",desc:"Newsletter platform with paid subscriptions.",r:4.6,cat:"Writing & Blogging",p:0},
{id:628,name:"Ghost",url:"ghost.org",desc:"Modern publishing CMS for serious writers.",r:4.7,cat:"Writing & Blogging",p:0},
{id:629,name:"Hashnode",url:"hashnode.com",desc:"Developer blogging with custom domains.",r:4.5,cat:"Writing & Blogging",p:0},
{id:630,name:"Dev.to",url:"dev.to",desc:"Collaborative community for software developers.",r:4.5,cat:"Writing & Blogging",p:0},
{id:631,name:"Blogger",url:"blogger.com",desc:"Google's free classic blogging platform.",r:3.9,cat:"Writing & Blogging",p:0},
{id:632,name:"Beehiiv",url:"beehiiv.com",desc:"Newsletter platform built for growth.",r:4.6,cat:"Writing & Blogging",p:0},
{id:633,name:"Buttondown",url:"buttondown.email",desc:"Simple, elegant newsletter publishing tool.",r:4.5,cat:"Writing & Blogging",p:0},
{id:634,name:"Typefully",url:"typefully.com",desc:"Write and schedule Twitter/X threads easily.",r:4.4,cat:"Writing & Blogging",p:0},
{id:635,name:"Hemingway Editor",url:"hemingwayapp.com",desc:"Highlights complex sentences for clarity.",r:4.4,cat:"Writing & Blogging",p:0},
{id:636,name:"Grammarly",url:"grammarly.com",desc:"AI writing assistant for grammar and style.",r:4.6,cat:"Writing & Blogging",p:0},
{id:637,name:"ProWritingAid",url:"prowritingaid.com",desc:"Deep grammar and style analysis for writers.",r:4.4,cat:"Writing & Blogging",p:0},
{id:638,name:"LanguageTool",url:"languagetool.org",desc:"Open-source multilingual grammar checker.",r:4.3,cat:"Writing & Blogging",p:0},
{id:639,name:"QuillBot",url:"quillbot.com",desc:"AI paraphrasing and summarization tool.",r:4.4,cat:"Writing & Blogging",p:0},
{id:640,name:"Wordtune",url:"wordtune.com",desc:"AI rewriting tool to improve your writing.",r:4.3,cat:"Writing & Blogging",p:0},
{id:641,name:"Copy.ai",url:"copy.ai",desc:"AI copywriting for marketing and content.",r:4.3,cat:"Writing & Blogging",p:0},
{id:642,name:"Jasper",url:"jasper.ai",desc:"AI content platform for marketing teams.",r:4.2,cat:"Writing & Blogging",p:0},
{id:643,name:"Writesonic",url:"writesonic.com",desc:"AI writer for blogs, ads, and SEO content.",r:4.2,cat:"Writing & Blogging",p:0},
{id:644,name:"Rytr",url:"rytr.me",desc:"Affordable AI writing assistant for all needs.",r:4.1,cat:"Writing & Blogging",p:0},
{id:645,name:"Scrivener",url:"literatureandlatte.com",desc:"Long-form writing tool for authors and scripts.",r:4.6,cat:"Writing & Blogging",p:0},
{id:646,name:"iA Writer",url:"ia.net/writer",desc:"Distraction-free writing with focus mode.",r:4.7,cat:"Writing & Blogging",p:0},
{id:647,name:"Penflip",url:"penflip.com",desc:"Collaborative writing with version control.",r:4.0,cat:"Writing & Blogging",p:0},
{id:648,name:"Wattpad",url:"wattpad.com",desc:"Platform to write and share original stories.",r:4.3,cat:"Writing & Blogging",p:0},
{id:649,name:"Archive of Our Own",url:"archiveofourown.org",desc:"Nonprofit fanfiction and creative writing archive.",r:4.6,cat:"Writing & Blogging",p:0},
{id:650,name:"Reedsy",url:"reedsy.com",desc:"Book editor marketplace and writing tools.",r:4.5,cat:"Writing & Blogging",p:0},
// Marketing & SEO
{id:651,name:"SEMrush",url:"semrush.com",desc:"All-in-one SEO and competitive research tool.",r:4.7,cat:"Marketing & SEO",p:0},
{id:652,name:"Ahrefs",url:"ahrefs.com",desc:"Backlink analysis and keyword research suite.",r:4.8,cat:"Marketing & SEO",p:0},
{id:653,name:"Moz",url:"moz.com",desc:"SEO software with DA scores and link explorer.",r:4.5,cat:"Marketing & SEO",p:0},
{id:654,name:"Ubersuggest",url:"neilpatel.com/ubersuggest",desc:"Free keyword and competitor research tool.",r:4.2,cat:"Marketing & SEO",p:0},
{id:655,name:"Mangools",url:"mangools.com",desc:"Beginner-friendly SEO tools suite.",r:4.5,cat:"Marketing & SEO",p:0},
{id:656,name:"Google Search Console",url:"search.google.com/search-console",desc:"Monitor your site's Google search performance.",r:4.8,cat:"Marketing & SEO",p:0},
{id:657,name:"Google Ads",url:"ads.google.com",desc:"Run search, display, and video ad campaigns.",r:4.5,cat:"Marketing & SEO",p:0},
{id:658,name:"Meta Ads",url:"adsmanager.facebook.com",desc:"Advertise on Facebook and Instagram platforms.",r:4.3,cat:"Marketing & SEO",p:0},
{id:659,name:"HubSpot",url:"app.hubspot.com",desc:"CRM, marketing, and sales growth platform.",r:4.6,cat:"Marketing & SEO",p:0},
{id:660,name:"Mailchimp",url:"mailchimp.com",desc:"Email marketing and automation for all sizes.",r:4.4,cat:"Marketing & SEO",p:0},
{id:661,name:"Klaviyo",url:"klaviyo.com",desc:"E-commerce email and SMS marketing platform.",r:4.6,cat:"Marketing & SEO",p:0},
{id:662,name:"ActiveCampaign",url:"activecampaign.com",desc:"Email automation and CRM for marketers.",r:4.5,cat:"Marketing & SEO",p:0},
{id:663,name:"ConvertKit",url:"convertkit.com",desc:"Email platform built for creators and bloggers.",r:4.5,cat:"Marketing & SEO",p:0},
{id:664,name:"Buffer",url:"buffer.com",desc:"Social media scheduling and analytics tool.",r:4.4,cat:"Marketing & SEO",p:0},
{id:665,name:"Hootsuite",url:"hootsuite.com",desc:"Manage all social media from one dashboard.",r:4.2,cat:"Marketing & SEO",p:0},
{id:666,name:"Sprout Social",url:"sproutsocial.com",desc:"Social media management and analytics suite.",r:4.5,cat:"Marketing & SEO",p:0},
{id:667,name:"Later",url:"later.com",desc:"Visual Instagram and social media scheduler.",r:4.4,cat:"Marketing & SEO",p:0},
{id:668,name:"Canva Social",url:"canva.com",desc:"Design and schedule social media posts easily.",r:4.7,cat:"Marketing & SEO",p:0},
{id:669,name:"Hotjar",url:"hotjar.com",desc:"Heatmaps and session recordings for UX.",r:4.6,cat:"Marketing & SEO",p:0},
{id:670,name:"Crazy Egg",url:"crazyegg.com",desc:"Visual heatmaps and A/B testing for websites.",r:4.3,cat:"Marketing & SEO",p:0},
{id:671,name:"FullStory",url:"fullstory.com",desc:"Digital experience analytics and session replay.",r:4.5,cat:"Marketing & SEO",p:0},
{id:672,name:"Microsoft Clarity",url:"clarity.microsoft.com",desc:"Free heatmaps and session recordings by MS.",r:4.5,cat:"Marketing & SEO",p:0},
{id:673,name:"Mouseflow",url:"mouseflow.com",desc:"Session replay, heatmaps, and funnel analysis.",r:4.3,cat:"Marketing & SEO",p:0},
{id:674,name:"Brand24",url:"brand24.com",desc:"Social listening and brand monitoring tool.",r:4.4,cat:"Marketing & SEO",p:0},
{id:675,name:"Mention",url:"mention.com",desc:"Real-time media monitoring and social alerts.",r:4.2,cat:"Marketing & SEO",p:0},
{id:676,name:"BuzzSumo",url:"buzzsumo.com",desc:"Content research and influencer discovery tool.",r:4.4,cat:"Marketing & SEO",p:0},
{id:677,name:"SimilarWeb",url:"similarweb.com",desc:"Website traffic and competitive intelligence.",r:4.5,cat:"Marketing & SEO",p:0},
{id:678,name:"SpyFu",url:"spyfu.com",desc:"Competitor keyword and PPC research tool.",r:4.3,cat:"Marketing & SEO",p:0},
{id:679,name:"Screaming Frog",url:"screamingfrog.co.uk",desc:"Website crawler for technical SEO audits.",r:4.7,cat:"Marketing & SEO",p:0},
{id:680,name:"Majestic",url:"majestic.com",desc:"Backlink intelligence and link analysis tool.",r:4.4,cat:"Marketing & SEO",p:0},
// HR & Recruiting
{id:681,name:"LinkedIn Jobs",url:"linkedin.com/jobs",desc:"World's largest professional job marketplace.",r:4.5,cat:"HR & Recruiting",p:0},
{id:682,name:"Indeed",url:"indeed.com",desc:"Global job board aggregator for all roles.",r:4.3,cat:"HR & Recruiting",p:0},
{id:683,name:"Glassdoor",url:"glassdoor.com",desc:"Company reviews, salaries, and job postings.",r:4.2,cat:"HR & Recruiting",p:0},
{id:684,name:"Wellfound",url:"wellfound.com",desc:"Startup job platform formerly AngelList Talent.",r:4.4,cat:"HR & Recruiting",p:0},
{id:685,name:"Lever",url:"lever.co",desc:"ATS and CRM for recruiting teams combined.",r:4.4,cat:"HR & Recruiting",p:0},
{id:686,name:"Greenhouse",url:"greenhouse.io",desc:"Structured hiring platform for growing teams.",r:4.5,cat:"HR & Recruiting",p:0},
{id:687,name:"Workday",url:"workday.com",desc:"Enterprise HR, finance, and talent management.",r:4.2,cat:"HR & Recruiting",p:0},
{id:688,name:"BambooHR",url:"bamboohr.com",desc:"HR software for small and mid-size businesses.",r:4.5,cat:"HR & Recruiting",p:0},
{id:689,name:"Rippling",url:"rippling.com",desc:"All-in-one HR, IT, and finance operations.",r:4.6,cat:"HR & Recruiting",p:0},
{id:690,name:"Gusto",url:"gusto.com",desc:"Payroll, benefits, and HR for small businesses.",r:4.6,cat:"HR & Recruiting",p:0},
{id:691,name:"Workable",url:"workable.com",desc:"Hiring software with sourcing and ATS tools.",r:4.4,cat:"HR & Recruiting",p:0},
{id:692,name:"Breezy HR",url:"breezy.hr",desc:"Modern recruiting software with pipeline views.",r:4.3,cat:"HR & Recruiting",p:0},
{id:693,name:"Recruitee",url:"recruitee.com",desc:"Collaborative hiring platform for HR teams.",r:4.3,cat:"HR & Recruiting",p:0},
{id:694,name:"HireVue",url:"hirevue.com",desc:"Video interviewing and hiring assessment tool.",r:4.1,cat:"HR & Recruiting",p:0},
{id:695,name:"Codility",url:"codility.com",desc:"Technical screening and coding assessments.",r:4.4,cat:"HR & Recruiting",p:0},
{id:696,name:"HackerRank Work",url:"hackerrank.com",desc:"Developer skill assessments and coding tests.",r:4.4,cat:"HR & Recruiting",p:0},
{id:697,name:"Testlify",url:"testlify.com",desc:"Talent assessment platform for all job roles.",r:4.2,cat:"HR & Recruiting",p:0},
{id:698,name:"Personio",url:"personio.com",desc:"HR software for European SMEs and startups.",r:4.3,cat:"HR & Recruiting",p:0},
{id:699,name:"HiBob",url:"hibob.com",desc:"Modern HRIS for global fast-growing companies.",r:4.5,cat:"HR & Recruiting",p:0},
{id:700,name:"Lattice",url:"lattice.com",desc:"Performance management and employee growth.",r:4.4,cat:"HR & Recruiting",p:0},
{id:701,name:"15Five",url:"15five.com",desc:"Continuous performance management platform.",r:4.4,cat:"HR & Recruiting",p:0},
{id:702,name:"Culture Amp",url:"cultureamp.com",desc:"Employee feedback, engagement, and analytics.",r:4.5,cat:"HR & Recruiting",p:0},
{id:703,name:"Namely",url:"namely.com",desc:"HR platform for mid-sized companies.",r:4.1,cat:"HR & Recruiting",p:0},
{id:704,name:"Paychex",url:"paychex.com",desc:"Payroll and HR solutions for US businesses.",r:4.0,cat:"HR & Recruiting",p:0},
{id:705,name:"ADP",url:"adp.com",desc:"Global payroll and workforce management system.",r:4.0,cat:"HR & Recruiting",p:0},
// DevOps & Infra
{id:706,name:"Kubernetes",url:"kubernetes.io",desc:"Open-source container orchestration system.",r:4.8,cat:"DevOps & Infra",p:0},
{id:707,name:"Helm",url:"helm.sh",desc:"The package manager for Kubernetes clusters.",r:4.7,cat:"DevOps & Infra",p:0},
{id:708,name:"Rancher",url:"rancher.com",desc:"Kubernetes management platform for enterprises.",r:4.5,cat:"DevOps & Infra",p:0},
{id:709,name:"Portainer",url:"portainer.io",desc:"Container management UI for Docker and K8s.",r:4.6,cat:"DevOps & Infra",p:0},
{id:710,name:"Terraform",url:"terraform.io",desc:"Infrastructure as code for any cloud provider.",r:4.8,cat:"DevOps & Infra",p:0},
{id:711,name:"Ansible",url:"ansible.com",desc:"Agentless IT automation and configuration tool.",r:4.7,cat:"DevOps & Infra",p:0},
{id:712,name:"Pulumi",url:"pulumi.com",desc:"Infrastructure as code using real languages.",r:4.6,cat:"DevOps & Infra",p:0},
{id:713,name:"CircleCI",url:"circleci.com",desc:"Fast CI/CD platform for modern development.",r:4.5,cat:"DevOps & Infra",p:0},
{id:714,name:"Jenkins",url:"jenkins.io",desc:"Open-source automation server for CI/CD.",r:4.4,cat:"DevOps & Infra",p:0},
{id:715,name:"GitLab CI",url:"docs.gitlab.com/ee/ci",desc:"Built-in CI/CD pipelines for GitLab projects.",r:4.6,cat:"DevOps & Infra",p:0},
{id:716,name:"Buildkite",url:"buildkite.com",desc:"Fast self-hosted CI pipelines at any scale.",r:4.6,cat:"DevOps & Infra",p:0},
{id:717,name:"Datadog",url:"app.datadoghq.com",desc:"Cloud monitoring, APM, and security platform.",r:4.7,cat:"DevOps & Infra",p:0},
{id:718,name:"Grafana",url:"grafana.com",desc:"Open observability platform for metrics dashboards.",r:4.8,cat:"DevOps & Infra",p:0},
{id:719,name:"Prometheus",url:"prometheus.io",desc:"Open-source monitoring and alerting toolkit.",r:4.8,cat:"DevOps & Infra",p:0},
{id:720,name:"PagerDuty",url:"pagerduty.com",desc:"Incident management and on-call alerting.",r:4.5,cat:"DevOps & Infra",p:0},
{id:721,name:"OpsGenie",url:"opsgenie.com",desc:"Alert management and on-call scheduling tool.",r:4.4,cat:"DevOps & Infra",p:0},
{id:722,name:"Statuspage",url:"manage.statuspage.io",desc:"Communicate system status to users publicly.",r:4.6,cat:"DevOps & Infra",p:0},
{id:723,name:"UptimeRobot",url:"uptimerobot.com",desc:"Free uptime monitoring with instant alerts.",r:4.5,cat:"DevOps & Infra",p:0},
{id:724,name:"Pingdom",url:"pingdom.com",desc:"Website performance and uptime monitoring.",r:4.4,cat:"DevOps & Infra",p:0},
{id:725,name:"StatusCake",url:"statuscake.com",desc:"Website monitoring with page speed testing.",r:4.3,cat:"DevOps & Infra",p:0},
{id:726,name:"HashiCorp Vault",url:"vaultproject.io",desc:"Secrets management and data encryption tool.",r:4.7,cat:"DevOps & Infra",p:0},
{id:727,name:"Doppler",url:"doppler.com",desc:"Universal secrets manager for dev teams.",r:4.6,cat:"DevOps & Infra",p:0},
{id:728,name:"Infisical",url:"infisical.com",desc:"Open-source secrets management platform.",r:4.5,cat:"DevOps & Infra",p:0},
{id:729,name:"Linode",url:"cloud.linode.com",desc:"Akamai cloud compute for developers.",r:4.5,cat:"DevOps & Infra",p:0},
{id:730,name:"Vultr",url:"my.vultr.com",desc:"High-performance SSD cloud servers globally.",r:4.5,cat:"DevOps & Infra",p:0},
{id:731,name:"OVHcloud",url:"ovhcloud.com",desc:"European cloud infrastructure and hosting.",r:4.2,cat:"DevOps & Infra",p:0},
{id:732,name:"Hetzner Cloud",url:"console.hetzner.cloud",desc:"Affordable German cloud servers and storage.",r:4.7,cat:"DevOps & Infra",p:0},
{id:733,name:"Nginx",url:"nginx.org",desc:"High-performance web server and reverse proxy.",r:4.8,cat:"DevOps & Infra",p:0},
{id:734,name:"Caddy",url:"caddyserver.com",desc:"Auto HTTPS web server with simple config.",r:4.7,cat:"DevOps & Infra",p:0},
{id:735,name:"Traefik",url:"traefik.io",desc:"Cloud-native edge router for microservices.",r:4.6,cat:"DevOps & Infra",p:0},
// Blockchain & Web3
{id:736,name:"MetaMask",url:"metamask.io",desc:"Browser wallet for Ethereum and EVM chains.",r:4.5,cat:"Blockchain & Web3",p:0},
{id:737,name:"Phantom",url:"phantom.app",desc:"Crypto wallet for Solana, Ethereum, and more.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:738,name:"Rainbow",url:"rainbow.me",desc:"Beautiful Ethereum wallet with DeFi access.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:739,name:"Trust Wallet",url:"trustwallet.com",desc:"Multi-chain mobile crypto wallet by Binance.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:740,name:"Coinbase Wallet",url:"wallet.coinbase.com",desc:"Self-custody crypto wallet by Coinbase.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:741,name:"OpenSea",url:"opensea.io",desc:"World's largest NFT marketplace platform.",r:4.2,cat:"Blockchain & Web3",p:0},
{id:742,name:"Rarible",url:"rarible.com",desc:"Community-owned NFT marketplace and protocol.",r:4.1,cat:"Blockchain & Web3",p:0},
{id:743,name:"Foundation",url:"foundation.app",desc:"Curated NFT marketplace for digital creators.",r:4.3,cat:"Blockchain & Web3",p:0},
{id:744,name:"Manifold",url:"manifold.xyz",desc:"Create and deploy your own NFT contracts.",r:4.5,cat:"Blockchain & Web3",p:0},
{id:745,name:"SuperRare",url:"superrare.com",desc:"Premium digital art NFT collector's market.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:746,name:"Uniswap",url:"app.uniswap.org",desc:"Leading decentralized token exchange protocol.",r:4.5,cat:"Blockchain & Web3",p:0},
{id:747,name:"SushiSwap",url:"sushi.com",desc:"Multi-chain DEX with yield farming features.",r:4.2,cat:"Blockchain & Web3",p:0},
{id:748,name:"PancakeSwap",url:"pancakeswap.finance",desc:"Top DEX on BNB Chain with low fees.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:749,name:"dYdX",url:"dydx.exchange",desc:"Decentralized perpetual futures exchange.",r:4.3,cat:"Blockchain & Web3",p:0},
{id:750,name:"GMX",url:"gmx.io",desc:"On-chain perpetual trading with low fees.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:751,name:"Etherscan",url:"etherscan.io",desc:"Ethereum blockchain explorer and analytics.",r:4.8,cat:"Blockchain & Web3",p:0},
{id:752,name:"BscScan",url:"bscscan.com",desc:"BNB Smart Chain explorer and analytics.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:753,name:"Polygonscan",url:"polygonscan.com",desc:"Polygon network blockchain explorer.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:754,name:"Solscan",url:"solscan.io",desc:"Solana blockchain explorer and data portal.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:755,name:"Arbiscan",url:"arbiscan.io",desc:"Arbitrum network blockchain explorer tool.",r:4.5,cat:"Blockchain & Web3",p:0},
{id:756,name:"Remix IDE",url:"remix.ethereum.org",desc:"Browser-based Solidity smart contract IDE.",r:4.7,cat:"Blockchain & Web3",p:0},
{id:757,name:"Hardhat",url:"hardhat.org",desc:"Ethereum development environment for pros.",r:4.7,cat:"Blockchain & Web3",p:0},
{id:758,name:"Alchemy",url:"alchemy.com",desc:"Blockchain developer platform and node APIs.",r:4.7,cat:"Blockchain & Web3",p:0},
{id:759,name:"Infura",url:"infura.io",desc:"Ethereum and IPFS API infrastructure provider.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:760,name:"Thirdweb",url:"thirdweb.com",desc:"SDK and tools to build Web3 applications.",r:4.5,cat:"Blockchain & Web3",p:0},
{id:761,name:"Moralis",url:"moralis.io",desc:"Web3 backend with APIs for crypto data.",r:4.4,cat:"Blockchain & Web3",p:0},
{id:762,name:"QuickNode",url:"quicknode.com",desc:"Blazing-fast blockchain nodes and APIs.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:763,name:"Tenderly",url:"tenderly.co",desc:"Smart contract debugging and simulation tool.",r:4.6,cat:"Blockchain & Web3",p:0},
{id:764,name:"OpenZeppelin",url:"openzeppelin.com",desc:"Audited smart contract libraries and tools.",r:4.8,cat:"Blockchain & Web3",p:0},
{id:765,name:"DeFiLlama",url:"defillama.com",desc:"DeFi TVL tracker and protocol analytics.",r:4.7,cat:"Blockchain & Web3",p:0},
// Utilities & Tools
{id:766,name:"Carbon",url:"carbon.now.sh",desc:"Create beautiful code screenshot images.",r:4.8,cat:"Utilities & Tools",p:0},
{id:767,name:"Ray.so",url:"ray.so",desc:"Stunning code images by Raycast team.",r:4.7,cat:"Utilities & Tools",p:0},
{id:768,name:"Shots.so",url:"shots.so",desc:"Create mockups and device frame screenshots.",r:4.6,cat:"Utilities & Tools",p:0},
{id:769,name:"Regex101",url:"regex101.com",desc:"Online regex tester with explanation panel.",r:4.9,cat:"Utilities & Tools",p:0},
{id:770,name:"RegExr",url:"regexr.com",desc:"Regex editor with community patterns library.",r:4.7,cat:"Utilities & Tools",p:0},
{id:771,name:"crontab.guru",url:"crontab.guru",desc:"Visual cron expression editor and tester.",r:4.9,cat:"Utilities & Tools",p:0},
{id:772,name:"EpochConverter",url:"epochconverter.com",desc:"Convert Unix timestamps to human dates.",r:4.7,cat:"Utilities & Tools",p:0},
{id:773,name:"DiffChecker",url:"diffchecker.com",desc:"Compare text, images, and code differences.",r:4.6,cat:"Utilities & Tools",p:0},
{id:774,name:"JSONDiff",url:"jsondiff.com",desc:"Visual JSON diff checker for API responses.",r:4.5,cat:"Utilities & Tools",p:0},
{id:775,name:"CyberChef",url:"gchq.github.io/CyberChef",desc:"GCHQ's web app for data transformation tasks.",r:4.8,cat:"Utilities & Tools",p:0},
{id:776,name:"Downdetector",url:"downdetector.com",desc:"Check real-time outage reports for services.",r:4.6,cat:"Utilities & Tools",p:0},
{id:777,name:"Wayback Machine",url:"web.archive.org",desc:"Internet archive with 800B+ saved web pages.",r:4.8,cat:"Utilities & Tools",p:0},
{id:778,name:"QR Code Generator",url:"qr-code-generator.com",desc:"Free customizable QR code creation tool.",r:4.5,cat:"Utilities & Tools",p:0},
{id:779,name:"Bitly",url:"bitly.com",desc:"URL shortener with click tracking analytics.",r:4.4,cat:"Utilities & Tools",p:0},
{id:780,name:"Rebrandly",url:"rebrandly.com",desc:"Branded link management and tracking tool.",r:4.3,cat:"Utilities & Tools",p:0},
{id:781,name:"Short.io",url:"short.io",desc:"White-label URL shortener with custom domains.",r:4.4,cat:"Utilities & Tools",p:0},
{id:782,name:"TinyURL",url:"tinyurl.com",desc:"Classic simple URL shortening service.",r:4.2,cat:"Utilities & Tools",p:0},
{id:783,name:"PasteBin",url:"pastebin.com",desc:"Share text and code snippets with anyone.",r:4.3,cat:"Utilities & Tools",p:0},
{id:784,name:"HasteBin",url:"hastebin.com",desc:"Open-source minimal text sharing service.",r:4.2,cat:"Utilities & Tools",p:0},
{id:785,name:"Excalidraw",url:"excalidraw.com",desc:"Collaborative virtual whiteboard with sketchy style.",r:4.8,cat:"Utilities & Tools",p:0},
{id:786,name:"Whimsical",url:"whimsical.com",desc:"Flowcharts, wireframes, and mind maps tool.",r:4.6,cat:"Utilities & Tools",p:0},
{id:787,name:"FlatIcon",url:"flaticon.com",desc:"Huge library of free and premium icon packs.",r:4.5,cat:"Utilities & Tools",p:0},
{id:788,name:"SVG Repo",url:"svgrepo.com",desc:"500K+ open-licensed SVG vectors and icons.",r:4.6,cat:"Utilities & Tools",p:0},
{id:789,name:"Shapedivider",url:"shapedivider.app",desc:"Generate custom SVG section divider shapes.",r:4.6,cat:"Utilities & Tools",p:0},
{id:790,name:"Glassmorphism CSS",url:"hype4.academy/tools/glassmorphism-generator",desc:"Generate glassmorphism CSS with live preview.",r:4.4,cat:"Utilities & Tools",p:0},
{id:791,name:"Neumorphism",url:"neumorphism.io",desc:"CSS neumorphism soft-UI generator tool.",r:4.4,cat:"Utilities & Tools",p:0},
{id:792,name:"CSS Gradient",url:"cssgradient.io",desc:"Visual CSS gradient builder and collection.",r:4.7,cat:"Utilities & Tools",p:0},
{id:793,name:"Animista",url:"animista.net",desc:"CSS animation library with live preview code.",r:4.7,cat:"Utilities & Tools",p:0},
{id:794,name:"Keyframes",url:"keyframes.app",desc:"Visual CSS animation and shadow generators.",r:4.5,cat:"Utilities & Tools",p:0},
// Analytics
{id:795,name:"Plausible",url:"plausible.io",desc:"Privacy-friendly lightweight website analytics.",r:4.8,cat:"Analytics",p:0},
{id:796,name:"Fathom",url:"usefathom.com",desc:"Simple, privacy-first website analytics tool.",r:4.7,cat:"Analytics",p:0},
{id:797,name:"Matomo",url:"matomo.org",desc:"Open-source Google Analytics alternative.",r:4.5,cat:"Analytics",p:0},
{id:798,name:"Simple Analytics",url:"simpleanalytics.com",desc:"Cookie-free analytics that respects privacy.",r:4.6,cat:"Analytics",p:0},
{id:799,name:"Umami",url:"umami.is",desc:"Self-hosted privacy-focused analytics platform.",r:4.7,cat:"Analytics",p:0},
{id:800,name:"Counter.dev",url:"counter.dev",desc:"Free open-source minimal website analytics.",r:4.4,cat:"Analytics",p:0},
{id:801,name:"Mixpanel",url:"mixpanel.com",desc:"Event-based product analytics for growth teams.",r:4.5,cat:"Analytics",p:0},
{id:802,name:"Amplitude",url:"amplitude.com",desc:"Digital analytics platform for product teams.",r:4.6,cat:"Analytics",p:0},
{id:803,name:"Heap",url:"heapanalytics.com",desc:"Auto-capture all user events without coding.",r:4.4,cat:"Analytics",p:0},
{id:804,name:"Segment",url:"segment.com",desc:"Customer data platform for all your analytics.",r:4.6,cat:"Analytics",p:0},
{id:805,name:"RudderStack",url:"rudderstack.com",desc:"Open-source customer data infrastructure.",r:4.5,cat:"Analytics",p:0},
{id:806,name:"Looker Studio",url:"lookerstudio.google.com",desc:"Free Google data visualization and dashboards.",r:4.6,cat:"Analytics",p:0},
{id:807,name:"Metabase",url:"metabase.com",desc:"Open-source BI and data visualization tool.",r:4.6,cat:"Analytics",p:0},
{id:808,name:"Redash",url:"redash.io",desc:"Connect and query data sources with SQL.",r:4.4,cat:"Analytics",p:0},
{id:809,name:"Apache Superset",url:"superset.apache.org",desc:"Open-source modern data exploration platform.",r:4.5,cat:"Analytics",p:0},
{id:810,name:"Tableau Public",url:"public.tableau.com",desc:"Free data visualization publishing platform.",r:4.5,cat:"Analytics",p:0},
{id:811,name:"Power BI",url:"powerbi.microsoft.com",desc:"Microsoft's business intelligence analytics suite.",r:4.5,cat:"Analytics",p:0},
{id:812,name:"Qlik",url:"qlik.com",desc:"AI-powered data integration and analytics.",r:4.3,cat:"Analytics",p:0},
{id:813,name:"Retool BI",url:"retool.com",desc:"Build internal dashboards and analytics tools.",r:4.5,cat:"Analytics",p:0},
{id:814,name:"Pirsch",url:"pirsch.io",desc:"Cookie-free web analytics for developers.",r:4.5,cat:"Analytics",p:0},
{id:815,name:"Splitbee",url:"splitbee.io",desc:"User analytics and A/B testing platform.",r:4.3,cat:"Analytics",p:0},
{id:816,name:"Woopra",url:"woopra.com",desc:"Real-time customer journey analytics platform.",r:4.2,cat:"Analytics",p:0},
{id:817,name:"Kissmetrics",url:"kissmetrics.io",desc:"Behavioral analytics tied to individual users.",r:4.1,cat:"Analytics",p:0},
{id:818,name:"Pendo",url:"pendo.io",desc:"Product analytics with in-app guidance tools.",r:4.4,cat:"Analytics",p:0},
// Automation
{id:819,name:"Make",url:"make.com",desc:"Visual no-code workflow automation platform.",r:4.7,cat:"Automation",p:0},
{id:820,name:"n8n",url:"n8n.io",desc:"Open-source workflow automation with code.",r:4.8,cat:"Automation",p:0},
{id:821,name:"Pabbly Connect",url:"pabbly.com/connect",desc:"Affordable automation connecting 1000+ apps.",r:4.4,cat:"Automation",p:0},
{id:822,name:"Activepieces",url:"activepieces.com",desc:"Open-source Zapier alternative for teams.",r:4.5,cat:"Automation",p:0},
{id:823,name:"IFTTT",url:"ifttt.com",desc:"Simple if-this-then-that automation applets.",r:4.2,cat:"Automation",p:0},
{id:824,name:"Pipedream",url:"pipedream.com",desc:"Code-native integration platform for devs.",r:4.6,cat:"Automation",p:0},
{id:825,name:"Relay.app",url:"relay.app",desc:"Human-in-the-loop workflow automation tool.",r:4.4,cat:"Automation",p:0},
{id:826,name:"Workato",url:"workato.com",desc:"Enterprise integration and automation platform.",r:4.4,cat:"Automation",p:0},
{id:827,name:"Power Automate",url:"flow.microsoft.com",desc:"Microsoft's cloud flow automation service.",r:4.3,cat:"Automation",p:0},
{id:828,name:"Albato",url:"albato.com",desc:"No-code integration platform for 600+ apps.",r:4.3,cat:"Automation",p:0},
{id:829,name:"Node-RED",url:"nodered.org",desc:"Flow-based programming for IoT and APIs.",r:4.6,cat:"Automation",p:0},
{id:830,name:"Home Assistant",url:"home-assistant.io",desc:"Open-source home automation hub platform.",r:4.8,cat:"Automation",p:0},
{id:831,name:"Tray.io",url:"tray.io",desc:"Enterprise automation with universal connector.",r:4.3,cat:"Automation",p:0},
{id:832,name:"Boomi",url:"boomi.com",desc:"Cloud-native integration platform as a service.",r:4.2,cat:"Automation",p:0},
{id:833,name:"MuleSoft",url:"mulesoft.com",desc:"API-led connectivity and integration platform.",r:4.3,cat:"Automation",p:0},
{id:834,name:"Celonis",url:"celonis.com",desc:"Process mining and execution management tool.",r:4.3,cat:"Automation",p:0},
{id:835,name:"UiPath",url:"uipath.com",desc:"Enterprise robotic process automation platform.",r:4.4,cat:"Automation",p:0},
// Cloud Storage
{id:836,name:"Dropbox",url:"dropbox.com",desc:"Cloud storage with smart file sync and sharing.",r:4.4,cat:"Cloud Storage",p:0},
{id:837,name:"OneDrive",url:"onedrive.live.com",desc:"Microsoft cloud storage integrated with Office.",r:4.3,cat:"Cloud Storage",p:0},
{id:838,name:"Box",url:"app.box.com",desc:"Secure enterprise content management platform.",r:4.3,cat:"Cloud Storage",p:0},
{id:839,name:"iCloud Drive",url:"icloud.com",desc:"Apple cloud storage across all your devices.",r:4.2,cat:"Cloud Storage",p:0},
{id:840,name:"pCloud",url:"pcloud.com",desc:"Secure cloud storage with lifetime plan option.",r:4.5,cat:"Cloud Storage",p:0},
{id:841,name:"Mega",url:"mega.nz",desc:"End-to-end encrypted cloud storage service.",r:4.4,cat:"Cloud Storage",p:0},
{id:842,name:"Tresorit",url:"tresorit.com",desc:"Zero-knowledge encrypted cloud storage for teams.",r:4.6,cat:"Cloud Storage",p:0},
{id:843,name:"Internxt",url:"internxt.com",desc:"Privacy-first encrypted decentralized storage.",r:4.4,cat:"Cloud Storage",p:0},
{id:844,name:"Filen",url:"filen.io",desc:"End-to-end encrypted zero-knowledge cloud drive.",r:4.5,cat:"Cloud Storage",p:0},
{id:845,name:"Backblaze",url:"backblaze.com",desc:"Affordable cloud backup and B2 object storage.",r:4.6,cat:"Cloud Storage",p:0},
{id:846,name:"Wasabi",url:"wasabi.com",desc:"Hot cloud storage at fraction of S3 price.",r:4.6,cat:"Cloud Storage",p:0},
{id:847,name:"Storj",url:"storj.io",desc:"Decentralized encrypted S3-compatible storage.",r:4.4,cat:"Cloud Storage",p:0},
{id:848,name:"Filebase",url:"filebase.com",desc:"S3-compatible storage on decentralized networks.",r:4.3,cat:"Cloud Storage",p:0},
{id:849,name:"Sync.com",url:"sync.com",desc:"Encrypted Canadian cloud storage for privacy.",r:4.5,cat:"Cloud Storage",p:0},
{id:850,name:"SpiderOak",url:"spideroak.com",desc:"Zero-knowledge cloud backup and collaboration.",r:4.3,cat:"Cloud Storage",p:0},
{id:851,name:"NextCloud",url:"nextcloud.com",desc:"Self-hosted cloud storage and collaboration suite.",r:4.7,cat:"Cloud Storage",p:0},
{id:852,name:"Seafile",url:"seafile.com",desc:"Open-source file sync with encryption support.",r:4.5,cat:"Cloud Storage",p:0},
{id:853,name:"Syncthing",url:"syncthing.net",desc:"P2P open-source continuous file sync tool.",r:4.7,cat:"Cloud Storage",p:0},
// VPN & Privacy
{id:854,name:"ProtonVPN",url:"protonvpn.com",desc:"Swiss no-log VPN with free tier available.",r:4.7,cat:"VPN & Privacy",p:0},
{id:855,name:"NordVPN",url:"nordvpn.com",desc:"Leading VPN with double encryption features.",r:4.5,cat:"VPN & Privacy",p:0},
{id:856,name:"ExpressVPN",url:"expressvpn.com",desc:"Fast and reliable VPN across 90+ countries.",r:4.5,cat:"VPN & Privacy",p:0},
{id:857,name:"Mullvad",url:"mullvad.net",desc:"Anonymous VPN with no account required.",r:4.8,cat:"VPN & Privacy",p:0},
{id:858,name:"Surfshark",url:"surfshark.com",desc:"Unlimited devices VPN with clean web feature.",r:4.5,cat:"VPN & Privacy",p:0},
{id:859,name:"Windscribe",url:"windscribe.com",desc:"Privacy tools with 10GB free monthly data.",r:4.4,cat:"VPN & Privacy",p:0},
{id:860,name:"TunnelBear",url:"tunnelbear.com",desc:"Simple bear-themed VPN for everyday use.",r:4.3,cat:"VPN & Privacy",p:0},
{id:861,name:"Tor Project",url:"torproject.org",desc:"Anonymity network and privacy browser.",r:4.7,cat:"VPN & Privacy",p:0},
{id:862,name:"Tuta",url:"tuta.com",desc:"Encrypted email and calendar for privacy.",r:4.6,cat:"VPN & Privacy",p:0},
{id:863,name:"Mailfence",url:"mailfence.com",desc:"Secure email with digital signatures support.",r:4.4,cat:"VPN & Privacy",p:0},
{id:864,name:"SimpleLogin",url:"simplelogin.io",desc:"Email alias service to protect your inbox.",r:4.6,cat:"VPN & Privacy",p:0},
{id:865,name:"AnonAddy",url:"addy.io",desc:"Open-source anonymous email forwarding.",r:4.5,cat:"VPN & Privacy",p:0},
{id:866,name:"Firefox",url:"firefox.com",desc:"Mozilla's open-source privacy browser.",r:4.6,cat:"VPN & Privacy",p:0},
{id:867,name:"LibreWolf",url:"librewolf.net",desc:"Privacy-hardened Firefox fork browser.",r:4.6,cat:"VPN & Privacy",p:0},
{id:868,name:"DuckDuckGo",url:"duckduckgo.com",desc:"Privacy search engine that doesn't track you.",r:4.6,cat:"VPN & Privacy",p:0},
{id:869,name:"Startpage",url:"startpage.com",desc:"Anonymous Google search results proxy.",r:4.4,cat:"VPN & Privacy",p:0},
{id:870,name:"Searx",url:"searx.github.io",desc:"Open-source meta search engine for privacy.",r:4.3,cat:"VPN & Privacy",p:0},
{id:871,name:"uBlock Origin",url:"ublockorigin.com",desc:"Efficient browser ad and tracker blocker.",r:4.9,cat:"VPN & Privacy",p:0},
{id:872,name:"Privacy Badger",url:"privacybadger.org",desc:"EFF's automatic tracker learning blocker.",r:4.6,cat:"VPN & Privacy",p:0},
{id:873,name:"Cover Your Tracks",url:"coveryourtracks.eff.org",desc:"Test how well your browser blocks tracking.",r:4.5,cat:"VPN & Privacy",p:0},
// Fonts & Icons
{id:874,name:"Google Fonts",url:"fonts.google.com",desc:"1500+ free open-source web font families.",r:4.9,cat:"Fonts & Icons",p:0},
{id:875,name:"Adobe Fonts",url:"fonts.adobe.com",desc:"Thousands of quality fonts via Creative Cloud.",r:4.6,cat:"Fonts & Icons",p:0},
{id:876,name:"DaFont",url:"dafont.com",desc:"Free downloadable fonts sorted by category.",r:4.4,cat:"Fonts & Icons",p:0},
{id:877,name:"Font Squirrel",url:"fontsquirrel.com",desc:"Free fonts for commercial use by designers.",r:4.5,cat:"Fonts & Icons",p:0},
{id:878,name:"Fontshare",url:"fontshare.com",desc:"Quality free fonts by Indian Type Foundry.",r:4.7,cat:"Fonts & Icons",p:0},
{id:879,name:"Fontjoy",url:"fontjoy.com",desc:"AI-powered font pairing generator tool.",r:4.6,cat:"Fonts & Icons",p:0},
{id:880,name:"WhatTheFont",url:"myfonts.com/whatthefont",desc:"AI font identification from uploaded images.",r:4.5,cat:"Fonts & Icons",p:0},
{id:881,name:"Identifont",url:"identifont.com",desc:"Identify fonts through question-based system.",r:4.2,cat:"Fonts & Icons",p:0},
{id:882,name:"MyFonts",url:"myfonts.com",desc:"Largest font marketplace with 130K fonts.",r:4.5,cat:"Fonts & Icons",p:0},
{id:883,name:"Fonts In Use",url:"fontsinuse.com",desc:"Real-world typography usage examples archive.",r:4.6,cat:"Fonts & Icons",p:0},
{id:884,name:"Heroicons",url:"heroicons.com",desc:"Beautiful hand-crafted SVG icons by Tailwind.",r:4.8,cat:"Fonts & Icons",p:0},
{id:885,name:"Lucide",url:"lucide.dev",desc:"Clean and consistent open-source icon library.",r:4.7,cat:"Fonts & Icons",p:0},
{id:886,name:"Phosphor Icons",url:"phosphoricons.com",desc:"Flexible icon family with 6 weights.",r:4.8,cat:"Fonts & Icons",p:0},
{id:887,name:"Tabler Icons",url:"tabler.io/icons",desc:"5000+ free MIT-licensed SVG icon set.",r:4.8,cat:"Fonts & Icons",p:0},
{id:888,name:"Remix Icon",url:"remixicon.com",desc:"2800+ open-source neutral-style icons.",r:4.7,cat:"Fonts & Icons",p:0},
{id:889,name:"Bootstrap Icons",url:"icons.getbootstrap.com",desc:"Free SVG icons designed for Bootstrap.",r:4.7,cat:"Fonts & Icons",p:0},
{id:890,name:"Material Icons",url:"fonts.google.com/icons",desc:"Google's Material Design icon library.",r:4.7,cat:"Fonts & Icons",p:0},
{id:891,name:"Font Awesome",url:"fontawesome.com",desc:"Internet's most popular icon toolkit.",r:4.6,cat:"Fonts & Icons",p:0},
{id:892,name:"Streamline",url:"streamlinehq.com",desc:"180K+ icons, illustrations, and emoji set.",r:4.5,cat:"Fonts & Icons",p:0},
{id:893,name:"Iconfinder",url:"iconfinder.com",desc:"Millions of icons with SVG/PNG download.",r:4.4,cat:"Fonts & Icons",p:0},
{id:894,name:"Icons8",url:"icons8.com",desc:"Icons, photos, illustrations, and music.",r:4.5,cat:"Fonts & Icons",p:0},
{id:895,name:"Noun Project",url:"thenounproject.com",desc:"5M+ icons and photos for any concept.",r:4.5,cat:"Fonts & Icons",p:0},
{id:896,name:"Lordicon",url:"lordicon.com",desc:"Animated icons with JSON/Lottie format.",r:4.6,cat:"Fonts & Icons",p:0},
{id:897,name:"Iconscout",url:"iconscout.com",desc:"Icons, 3D assets, Lottie animations library.",r:4.5,cat:"Fonts & Icons",p:0},
// Sports & Fitness
{id:898,name:"ESPN",url:"espn.com",desc:"Live scores, news, and sports analysis.",r:4.4,cat:"Sports & Fitness",p:0},
{id:899,name:"Sky Sports",url:"skysports.com",desc:"UK sports news, scores, and live coverage.",r:4.3,cat:"Sports & Fitness",p:0},
{id:900,name:"BBC Sport",url:"bbc.com/sport",desc:"Free sports news and results from the BBC.",r:4.5,cat:"Sports & Fitness",p:0},
{id:901,name:"Goal.com",url:"goal.com",desc:"Global football news, results, and transfers.",r:4.3,cat:"Sports & Fitness",p:0},
{id:902,name:"Sofascore",url:"sofascore.com",desc:"Live scores and stats for 20+ sports.",r:4.7,cat:"Sports & Fitness",p:0},
{id:903,name:"FotMob",url:"fotmob.com",desc:"Fast football live scores and match data.",r:4.7,cat:"Sports & Fitness",p:0},
{id:904,name:"FlashScore",url:"flashscore.com",desc:"Live scores across 30+ sports worldwide.",r:4.6,cat:"Sports & Fitness",p:0},
{id:905,name:"365Scores",url:"365scores.com",desc:"Personalized live scores and sports news.",r:4.5,cat:"Sports & Fitness",p:0},
{id:906,name:"LiveScore",url:"livescore.com",desc:"Instant live scores for football and more.",r:4.5,cat:"Sports & Fitness",p:0},
{id:907,name:"OneFootball",url:"onefootball.com",desc:"Football news and personalized match center.",r:4.5,cat:"Sports & Fitness",p:0},
{id:908,name:"Transfermarkt",url:"transfermarkt.com",desc:"Football player values, transfers, and stats.",r:4.6,cat:"Sports & Fitness",p:0},
{id:909,name:"NBA.com",url:"nba.com",desc:"Official NBA news, stats, and live games.",r:4.4,cat:"Sports & Fitness",p:0},
{id:910,name:"NFL.com",url:"nfl.com",desc:"Official NFL football news and game center.",r:4.3,cat:"Sports & Fitness",p:0},
{id:911,name:"MLB.com",url:"mlb.com",desc:"Official Major League Baseball scores hub.",r:4.3,cat:"Sports & Fitness",p:0},
{id:912,name:"The Athletic",url:"theathletic.com",desc:"In-depth sports journalism and analysis.",r:4.6,cat:"Sports & Fitness",p:0},
{id:913,name:"Bleacher Report",url:"bleacherreport.com",desc:"Sports news and highlights for fans.",r:4.2,cat:"Sports & Fitness",p:0},
{id:914,name:"Nike",url:"nike.com",desc:"Sportswear, training gear, and Nike apps.",r:4.5,cat:"Sports & Fitness",p:0},
{id:915,name:"Adidas",url:"adidas.com",desc:"Athletic gear, running shoes, and apparel.",r:4.4,cat:"Sports & Fitness",p:0},
{id:916,name:"Under Armour",url:"underarmour.com",desc:"Performance sportswear and MapMyFitness apps.",r:4.3,cat:"Sports & Fitness",p:0},
// Open Source
{id:917,name:"Codeberg",url:"codeberg.org",desc:"Non-profit Git hosting for open-source projects.",r:4.6,cat:"Open Source",p:0},
{id:918,name:"Forgejo",url:"forgejo.org",desc:"Self-hostable Git platform, Gitea fork.",r:4.5,cat:"Open Source",p:0},
{id:919,name:"Sourcehut",url:"sr.ht",desc:"Minimal open-source software forge platform.",r:4.4,cat:"Open Source",p:0},
{id:920,name:"Open Collective",url:"opencollective.com",desc:"Transparent funding for open-source communities.",r:4.5,cat:"Open Source",p:0},
{id:921,name:"Linux Foundation",url:"linuxfoundation.org",desc:"Supporting collaborative open-source projects.",r:4.7,cat:"Open Source",p:0},
{id:922,name:"Apache",url:"apache.org",desc:"Home of Apache open-source software projects.",r:4.7,cat:"Open Source",p:0},
{id:923,name:"Mozilla",url:"mozilla.org",desc:"Non-profit behind Firefox and open web standards.",r:4.7,cat:"Open Source",p:0},
{id:924,name:"FSF",url:"fsf.org",desc:"Free Software Foundation promoting user freedom.",r:4.5,cat:"Open Source",p:0},
{id:925,name:"EFF",url:"eff.org",desc:"Electronic Frontier Foundation defends digital rights.",r:4.8,cat:"Open Source",p:0},
{id:926,name:"Creative Commons",url:"creativecommons.org",desc:"Free licensing tools for creative sharing.",r:4.7,cat:"Open Source",p:0},
{id:927,name:"OSI",url:"opensource.org",desc:"Open Source Initiative stewards the OSD.",r:4.6,cat:"Open Source",p:0},
{id:928,name:"SourceForge",url:"sourceforge.net",desc:"Legacy open-source software hosting platform.",r:4.0,cat:"Open Source",p:0},
{id:929,name:"GNU",url:"gnu.org",desc:"GNU Project's free software operating system.",r:4.6,cat:"Open Source",p:0},
{id:930,name:"LibreOffice",url:"libreoffice.org",desc:"Free powerful open-source office suite.",r:4.5,cat:"Open Source",p:0},
{id:931,name:"VLC",url:"videolan.org",desc:"Free open-source cross-platform media player.",r:4.9,cat:"Open Source",p:0},
{id:932,name:"Audacity",url:"audacityteam.org",desc:"Free open-source audio editing software.",r:4.7,cat:"Open Source",p:0},
{id:933,name:"GIMP",url:"gimp.org",desc:"Free open-source image manipulation program.",r:4.5,cat:"Open Source",p:0},
{id:934,name:"Inkscape",url:"inkscape.org",desc:"Free open-source vector graphics editor.",r:4.6,cat:"Open Source",p:0},
{id:935,name:"Blender",url:"blender.org",desc:"Free open-source 3D creation suite.",r:4.9,cat:"Open Source",p:0},
{id:936,name:"Krita",url:"krita.org",desc:"Free professional digital painting application.",r:4.8,cat:"Open Source",p:0},
{id:937,name:"FreeBSD",url:"freebsd.org",desc:"Advanced open-source Unix-like operating system.",r:4.6,cat:"Open Source",p:0},
{id:938,name:"Ubuntu",url:"ubuntu.com",desc:"Popular beginner-friendly Linux distribution.",r:4.7,cat:"Open Source",p:0},
{id:939,name:"Debian",url:"debian.org",desc:"Stable and universal open-source Linux distro.",r:4.7,cat:"Open Source",p:0},
{id:940,name:"Arch Linux",url:"archlinux.org",desc:"Lightweight rolling-release Linux distribution.",r:4.8,cat:"Open Source",p:0},
{id:941,name:"NixOS",url:"nixos.org",desc:"Reproducible declarative Linux configuration.",r:4.7,cat:"Open Source",p:0},
// Startup & Business
{id:942,name:"Product Hunt",url:"producthunt.com",desc:"Discover and launch new tech products daily.",r:4.7,cat:"Startup & Business",p:0},
{id:943,name:"Y Combinator",url:"ycombinator.com",desc:"World's top startup accelerator and community.",r:4.8,cat:"Startup & Business",p:0},
{id:944,name:"Techstars",url:"techstars.com",desc:"Global startup accelerator and investor network.",r:4.5,cat:"Startup & Business",p:0},
{id:945,name:"Crunchbase",url:"crunchbase.com",desc:"Startup and investor funding data platform.",r:4.5,cat:"Startup & Business",p:0},
{id:946,name:"AngelList",url:"angel.co",desc:"Platform for startup investing and fundraising.",r:4.4,cat:"Startup & Business",p:0},
{id:947,name:"Pitch",url:"pitch.com",desc:"Collaborative presentation software for teams.",r:4.5,cat:"Startup & Business",p:0},
{id:948,name:"Loom",url:"loom.com",desc:"Async video messaging for remote teams.",r:4.6,cat:"Startup & Business",p:0},
{id:949,name:"Gamma",url:"gamma.app",desc:"AI-powered presentation and doc creator.",r:4.6,cat:"Startup & Business",p:0},
{id:950,name:"Beautiful.ai",url:"beautiful.ai",desc:"Smart presentation design with AI layout.",r:4.4,cat:"Startup & Business",p:0},
{id:951,name:"Tome",url:"tome.app",desc:"AI-powered narrative and presentation tool.",r:4.3,cat:"Startup & Business",p:0},
{id:952,name:"DocuSign",url:"docusign.com",desc:"Electronic signature and agreement cloud.",r:4.5,cat:"Startup & Business",p:0},
{id:953,name:"HelloSign",url:"hellosign.com",desc:"Simple eSignature tool by Dropbox.",r:4.4,cat:"Startup & Business",p:0},
{id:954,name:"Stripe Atlas",url:"stripe.com/atlas",desc:"Incorporate your startup in the US online.",r:4.7,cat:"Startup & Business",p:0},
{id:955,name:"Carta",url:"carta.com",desc:"Equity management for startups and investors.",r:4.5,cat:"Startup & Business",p:0},
{id:956,name:"Pulley",url:"pulley.com",desc:"Simple cap table management for founders.",r:4.4,cat:"Startup & Business",p:0},
{id:957,name:"Clerky",url:"clerky.com",desc:"Legal paperwork automation for startups.",r:4.3,cat:"Startup & Business",p:0},
{id:958,name:"Gust",url:"gust.com",desc:"Startup funding and community platform.",r:4.1,cat:"Startup & Business",p:0},
{id:959,name:"Fondo",url:"tryfondo.com",desc:"Startup bookkeeping and financial reporting.",r:4.3,cat:"Startup & Business",p:0},
{id:960,name:"Pilot",url:"pilot.com",desc:"Bookkeeping and CFO services for startups.",r:4.4,cat:"Startup & Business",p:0},
{id:961,name:"Bench",url:"bench.co",desc:"Online bookkeeping with dedicated accountants.",r:4.3,cat:"Startup & Business",p:0},
{id:962,name:"Deel",url:"letsdeel.com",desc:"Global payroll and contractor management.",r:4.5,cat:"Startup & Business",p:0},
{id:963,name:"Remote",url:"remote.com",desc:"Hire and pay global employees compliantly.",r:4.5,cat:"Startup & Business",p:0},
{id:964,name:"Oyster",url:"oysterhr.com",desc:"Global employment platform for remote teams.",r:4.4,cat:"Startup & Business",p:0},
// Browser Tools
{id:965,name:"Chrome Web Store",url:"chrome.google.com/webstore",desc:"Extensions and themes for Chrome browser.",r:4.4,cat:"Browser Tools",p:0},
{id:966,name:"Firefox Add-ons",url:"addons.mozilla.org",desc:"Extensions and themes for Firefox browser.",r:4.5,cat:"Browser Tools",p:0},
{id:967,name:"Edge Add-ons",url:"microsoftedge.microsoft.com/addons",desc:"Extensions for Microsoft Edge browser.",r:4.3,cat:"Browser Tools",p:0},
{id:968,name:"Wappalyzer",url:"wappalyzer.com",desc:"Detect technologies used on any website.",r:4.6,cat:"Browser Tools",p:0},
{id:969,name:"BuiltWith",url:"builtwith.com",desc:"Technology profiler for websites and apps.",r:4.5,cat:"Browser Tools",p:0},
{id:970,name:"Lighthouse",url:"developers.google.com/web/tools/lighthouse",desc:"Google's web performance auditing tool.",r:4.8,cat:"Browser Tools",p:0},
{id:971,name:"PageSpeed Insights",url:"pagespeed.web.dev",desc:"Analyze page performance with Core Web Vitals.",r:4.7,cat:"Browser Tools",p:0},
{id:972,name:"Web Vitals",url:"web.dev/vitals",desc:"Google's metrics for great user experience.",r:4.7,cat:"Browser Tools",p:0},
{id:973,name:"GTmetrix",url:"gtmetrix.com",desc:"Website speed and performance testing tool.",r:4.6,cat:"Browser Tools",p:0},
{id:974,name:"WebPageTest",url:"webpagetest.org",desc:"Advanced web performance testing from anywhere.",r:4.7,cat:"Browser Tools",p:0},
{id:975,name:"Can I Use",url:"caniuse.com",desc:"Browser support tables for web technologies.",r:4.9,cat:"Browser Tools",p:0},
{id:976,name:"MDN",url:"developer.mozilla.org",desc:"Mozilla's comprehensive web developer reference.",r:4.9,cat:"Browser Tools",p:0},
{id:977,name:"W3Schools",url:"w3schools.com",desc:"Web development tutorials and references.",r:4.5,cat:"Browser Tools",p:0},
{id:978,name:"DevDocs",url:"devdocs.io",desc:"Unified API documentation for all languages.",r:4.8,cat:"Browser Tools",p:0},
{id:979,name:"CSS Tricks",url:"css-tricks.com",desc:"Web design and frontend development articles.",r:4.7,cat:"Browser Tools",p:0},
{id:980,name:"Smashing Magazine",url:"smashingmagazine.com",desc:"Expert web design and development articles.",r:4.7,cat:"Browser Tools",p:0},
{id:981,name:"CodePen",url:"codepen.io",desc:"Frontend code playground with live preview.",r:4.7,cat:"Browser Tools",p:0},
{id:982,name:"JSFiddle",url:"jsfiddle.net",desc:"Online JavaScript, HTML, CSS editor tool.",r:4.5,cat:"Browser Tools",p:0},
{id:983,name:"W3C Validator",url:"validator.w3.org",desc:"Validate HTML markup for W3C compliance.",r:4.6,cat:"Browser Tools",p:0},
// Email
{id:984,name:"Outlook",url:"outlook.live.com",desc:"Microsoft's free personal email and calendar.",r:4.3,cat:"Email",p:0},
{id:985,name:"Apple Mail (iCloud)",url:"icloud.com/mail",desc:"Apple's webmail interface for iCloud accounts.",r:4.1,cat:"Email",p:0},
{id:986,name:"Tuta",url:"tuta.com",desc:"Encrypted email and calendar for privacy.",r:4.6,cat:"Email",p:0},
{id:987,name:"Hey",url:"hey.com",desc:"Opinionated email service reimagined by Basecamp.",r:4.4,cat:"Email",p:0},
{id:988,name:"Fastmail",url:"fastmail.com",desc:"Fast, ad-free email with custom domain support.",r:4.6,cat:"Email",p:0},
{id:989,name:"Zoho Mail",url:"mail.zoho.com",desc:"Ad-free professional email for businesses.",r:4.3,cat:"Email",p:0},
{id:990,name:"Superhuman",url:"superhuman.com",desc:"Blazing-fast AI-powered email client.",r:4.5,cat:"Email",p:0},
{id:991,name:"Spike",url:"spike.email",desc:"Email as a chat-style conversational interface.",r:4.3,cat:"Email",p:0},
{id:992,name:"Postmark",url:"postmarkapp.com",desc:"Reliable transactional email delivery service.",r:4.7,cat:"Email",p:0},
{id:993,name:"Mailgun",url:"mailgun.com",desc:"Email API for sending, receiving, tracking.",r:4.5,cat:"Email",p:0},
{id:994,name:"SendGrid",url:"sendgrid.com",desc:"Cloud email delivery platform by Twilio.",r:4.5,cat:"Email",p:0},
{id:995,name:"Amazon SES",url:"aws.amazon.com/ses",desc:"Affordable cloud email sending by AWS.",r:4.5,cat:"Email",p:0},
{id:996,name:"SparkPost",url:"sparkpost.com",desc:"Email delivery with analytics and insights.",r:4.3,cat:"Email",p:0},
{id:997,name:"Resend",url:"resend.com",desc:"Email API built for developers by ex-Twilio.",r:4.7,cat:"Email",p:0},
{id:998,name:"Brevo",url:"brevo.com",desc:"Email, SMS, and marketing automation platform.",r:4.4,cat:"Email",p:0},
{id:999,name:"EmailOctopus",url:"emailoctopus.com",desc:"Simple and affordable email marketing tool.",r:4.4,cat:"Email",p:0},
{id:1000,name:"Mailjet",url:"mailjet.com",desc:"Email marketing and transactional email API.",r:4.2,cat:"Email",p:0},
// Documents & Office
{id:1001,name:"Google Docs",url:"docs.google.com",desc:"Collaborative cloud word processor by Google.",r:4.8,cat:"Documents & Office",p:0},
{id:1002,name:"Google Sheets",url:"sheets.google.com",desc:"Collaborative cloud spreadsheet by Google.",r:4.8,cat:"Documents & Office",p:0},
{id:1003,name:"Google Slides",url:"slides.google.com",desc:"Cloud presentation maker by Google.",r:4.7,cat:"Documents & Office",p:0},
{id:1004,name:"Google Forms",url:"forms.google.com",desc:"Free survey and form creation by Google.",r:4.7,cat:"Documents & Office",p:0},
{id:1005,name:"Microsoft Word Online",url:"office.live.com/start/word.aspx",desc:"Microsoft Word in the browser, free.",r:4.4,cat:"Documents & Office",p:0},
{id:1006,name:"Microsoft Excel Online",url:"office.live.com/start/excel.aspx",desc:"Microsoft Excel spreadsheet in browser.",r:4.4,cat:"Documents & Office",p:0},
{id:1007,name:"Coda",url:"coda.io",desc:"All-in-one doc platform with tables and apps.",r:4.6,cat:"Documents & Office",p:0},
{id:1008,name:"Quip",url:"quip.com",desc:"Collaborative docs and spreadsheets by Salesforce.",r:4.2,cat:"Documents & Office",p:0},
{id:1009,name:"Dropbox Paper",url:"paper.dropbox.com",desc:"Simple collaborative doc editing in Dropbox.",r:4.3,cat:"Documents & Office",p:0},
{id:1010,name:"ONLYOFFICE",url:"onlyoffice.com",desc:"Open-source Office suite with online editors.",r:4.4,cat:"Documents & Office",p:0},
{id:1011,name:"Zoho Docs",url:"docs.zoho.com",desc:"Online office suite by Zoho ecosystem.",r:4.2,cat:"Documents & Office",p:0},
{id:1012,name:"NocoDB",url:"nocodb.com",desc:"Open-source Airtable alternative, spreadsheet-DB.",r:4.6,cat:"Documents & Office",p:0},
{id:1013,name:"Baserow",url:"baserow.io",desc:"Open-source no-code database and spreadsheet.",r:4.5,cat:"Documents & Office",p:0},
{id:1014,name:"Grist",url:"getgrist.com",desc:"Modern spreadsheet meets relational database.",r:4.5,cat:"Documents & Office",p:0},
{id:1015,name:"Rows",url:"rows.com",desc:"Spreadsheet with built-in integrations and APIs.",r:4.4,cat:"Documents & Office",p:0},
{id:1016,name:"Lark Docs",url:"larksuite.com",desc:"Collaborative docs from ByteDance's Lark.",r:4.4,cat:"Documents & Office",p:0},
{id:1017,name:"Craft",url:"craft.do",desc:"Beautiful native docs for Apple ecosystem.",r:4.7,cat:"Documents & Office",p:0},
{id:1018,name:"Nuclino",url:"nuclino.com",desc:"Unified team wiki and docs workspace.",r:4.5,cat:"Documents & Office",p:0},
{id:1019,name:"Slite",url:"slite.com",desc:"AI-powered knowledge base for remote teams.",r:4.4,cat:"Documents & Office",p:0},
// Customer Support
{id:1020,name:"Zendesk",url:"zendesk.com",desc:"Customer service platform with ticketing system.",r:4.4,cat:"Customer Support",p:0},
{id:1021,name:"Intercom",url:"intercom.com",desc:"Conversational customer engagement platform.",r:4.5,cat:"Customer Support",p:0},
{id:1022,name:"Freshdesk",url:"freshdesk.com",desc:"Intuitive customer support help desk software.",r:4.4,cat:"Customer Support",p:0},
{id:1023,name:"Crisp",url:"crisp.chat",desc:"All-in-one business messaging platform.",r:4.4,cat:"Customer Support",p:0},
{id:1024,name:"Tidio",url:"tidio.com",desc:"Live chat and chatbot for small businesses.",r:4.4,cat:"Customer Support",p:0},
{id:1025,name:"LiveChat",url:"livechat.com",desc:"Premium live chat software for websites.",r:4.4,cat:"Customer Support",p:0},
{id:1026,name:"Tawk.to",url:"tawk.to",desc:"100% free live chat widget for websites.",r:4.3,cat:"Customer Support",p:0},
{id:1027,name:"Help Scout",url:"helpscout.com",desc:"Customer support tools that feel like email.",r:4.6,cat:"Customer Support",p:0},
{id:1028,name:"Groove",url:"groovehq.com",desc:"Simple helpdesk built for small businesses.",r:4.3,cat:"Customer Support",p:0},
{id:1029,name:"Gorgias",url:"gorgias.com",desc:"E-commerce customer support helpdesk tool.",r:4.5,cat:"Customer Support",p:0},
{id:1030,name:"Re:amaze",url:"reamaze.com",desc:"Integrated support and chat for e-commerce.",r:4.3,cat:"Customer Support",p:0},
{id:1031,name:"Gladly",url:"gladly.com",desc:"Customer service platform centered on people.",r:4.2,cat:"Customer Support",p:0},
{id:1032,name:"Kustomer",url:"kustomer.com",desc:"CRM-based customer service platform.",r:4.3,cat:"Customer Support",p:0},
{id:1033,name:"Canny",url:"canny.io",desc:"Collect and manage user feedback and roadmaps.",r:4.5,cat:"Customer Support",p:0},
{id:1034,name:"UserVoice",url:"uservoice.com",desc:"Product feedback management platform.",r:4.2,cat:"Customer Support",p:0},
{id:1035,name:"Productboard",url:"productboard.com",desc:"Product management system with user insights.",r:4.4,cat:"Customer Support",p:0},
{id:1036,name:"Aha!",url:"aha.io",desc:"Product roadmapping and strategy platform.",r:4.4,cat:"Customer Support",p:0},
// Data Science
{id:1037,name:"Google Colab",url:"colab.research.google.com",desc:"Free cloud Jupyter notebooks with GPU support.",r:4.7,cat:"Data Science",p:0},
{id:1038,name:"Deepnote",url:"deepnote.com",desc:"Collaborative data science notebooks for teams.",r:4.6,cat:"Data Science",p:0},
{id:1039,name:"Hex",url:"hex.tech",desc:"Collaborative data workspace and notebooks.",r:4.6,cat:"Data Science",p:0},
{id:1040,name:"Observable",url:"observablehq.com",desc:"JavaScript notebooks for interactive data viz.",r:4.5,cat:"Data Science",p:0},
{id:1041,name:"Kaggle",url:"kaggle.com",desc:"Data science competitions and open datasets.",r:4.7,cat:"Data Science",p:0},
{id:1042,name:"Weights & Biases",url:"wandb.ai",desc:"ML experiment tracking and model monitoring.",r:4.7,cat:"Data Science",p:0},
{id:1043,name:"MLflow",url:"mlflow.org",desc:"Open-source ML lifecycle management platform.",r:4.6,cat:"Data Science",p:0},
{id:1044,name:"DVC",url:"dvc.org",desc:"Data version control for ML projects.",r:4.5,cat:"Data Science",p:0},
{id:1045,name:"ClearML",url:"clear.ml",desc:"MLOps platform for experiment and pipeline.",r:4.4,cat:"Data Science",p:0},
{id:1046,name:"Paperspace",url:"console.paperspace.com",desc:"Cloud GPU machines for ML and data science.",r:4.4,cat:"Data Science",p:0},
{id:1047,name:"Saturn Cloud",url:"saturncloud.io",desc:"Scalable data science on cloud infrastructure.",r:4.3,cat:"Data Science",p:0},
{id:1048,name:"Databricks",url:"databricks.com",desc:"Unified data analytics and AI platform.",r:4.6,cat:"Data Science",p:0},
{id:1049,name:"Snowflake",url:"app.snowflake.com",desc:"Cloud data warehouse for all workloads.",r:4.6,cat:"Data Science",p:0},
{id:1050,name:"dbt",url:"getdbt.com",desc:"Transform data in your warehouse with SQL.",r:4.7,cat:"Data Science",p:0},
{id:1051,name:"Airbyte",url:"airbyte.com",desc:"Open-source ELT data integration platform.",r:4.5,cat:"Data Science",p:0},
{id:1052,name:"Fivetran",url:"fivetran.com",desc:"Automated data pipeline and ELT connectors.",r:4.5,cat:"Data Science",p:0},
{id:1053,name:"Stitch",url:"stitchdata.com",desc:"Simple cloud ETL for data warehouse loading.",r:4.3,cat:"Data Science",p:0},
{id:1054,name:"Streamlit",url:"streamlit.io",desc:"Turn Python scripts into shareable web apps.",r:4.7,cat:"Data Science",p:0},
{id:1055,name:"Gradio",url:"gradio.app",desc:"Build ML demos and web UIs in Python.",r:4.6,cat:"Data Science",p:0},
{id:1056,name:"HuggingFace Spaces",url:"huggingface.co/spaces",desc:"Host and demo ML models publicly for free.",r:4.7,cat:"Data Science",p:0},
{id:1057,name:"Roboflow",url:"roboflow.com",desc:"Computer vision data management platform.",r:4.5,cat:"Data Science",p:0},
{id:1058,name:"Label Studio",url:"labelstud.io",desc:"Open-source data labeling for ML projects.",r:4.5,cat:"Data Science",p:0},
{id:1059,name:"Scale AI",url:"scale.com",desc:"Data labeling and AI training data platform.",r:4.4,cat:"Data Science",p:0},
// No-Code & Low-Code
{id:1060,name:"Bubble",url:"bubble.io",desc:"Full-stack no-code app development platform.",r:4.5,cat:"No-Code & Low-Code",p:0},
{id:1061,name:"Adalo",url:"adalo.com",desc:"Build mobile and web apps without coding.",r:4.3,cat:"No-Code & Low-Code",p:0},
{id:1062,name:"Glide",url:"glideapps.com",desc:"Create apps from Google Sheets easily.",r:4.4,cat:"No-Code & Low-Code",p:0},
{id:1063,name:"Softr",url:"softr.io",desc:"Build client portals and apps on Airtable.",r:4.4,cat:"No-Code & Low-Code",p:0},
{id:1064,name:"Thunkable",url:"thunkable.com",desc:"Drag-and-drop mobile app builder platform.",r:4.2,cat:"No-Code & Low-Code",p:0},
{id:1065,name:"Webflow",url:"webflow.com",desc:"Visual web design tool with CMS and hosting.",r:4.7,cat:"No-Code & Low-Code",p:0},
{id:1066,name:"Framer",url:"framer.com",desc:"Interactive design and website builder tool.",r:4.6,cat:"No-Code & Low-Code",p:0},
{id:1067,name:"WeWeb",url:"weweb.io",desc:"No-code frontend builder for any backend.",r:4.4,cat:"No-Code & Low-Code",p:0},
{id:1068,name:"Plasmic",url:"plasmic.app",desc:"Visual builder that integrates into codebases.",r:4.5,cat:"No-Code & Low-Code",p:0},
{id:1069,name:"Retool",url:"retool.com",desc:"Build internal tools and dashboards quickly.",r:4.7,cat:"No-Code & Low-Code",p:0},
{id:1070,name:"Appsmith",url:"appsmith.com",desc:"Open-source low-code internal tool builder.",r:4.6,cat:"No-Code & Low-Code",p:0},
{id:1071,name:"Budibase",url:"budibase.com",desc:"Open-source low-code platform for businesses.",r:4.5,cat:"No-Code & Low-Code",p:0},
{id:1072,name:"Forest Admin",url:"forestadmin.com",desc:"Admin panel generator for any database.",r:4.3,cat:"No-Code & Low-Code",p:0},
{id:1073,name:"Pory",url:"pory.io",desc:"Build portals and apps from Airtable data.",r:4.2,cat:"No-Code & Low-Code",p:0},
{id:1074,name:"Memberstack",url:"memberstack.com",desc:"Add memberships and payments to any site.",r:4.4,cat:"No-Code & Low-Code",p:0},
{id:1075,name:"OutSystems",url:"outsystems.com",desc:"Enterprise low-code development platform.",r:4.3,cat:"No-Code & Low-Code",p:0},
{id:1076,name:"Mendix",url:"mendix.com",desc:"Low-code platform for enterprise app development.",r:4.2,cat:"No-Code & Low-Code",p:0},
{id:1077,name:"Betty Blocks",url:"bettyblocks.com",desc:"Enterprise no-code application development.",r:4.1,cat:"No-Code & Low-Code",p:0},
// 3D & AR/VR
{id:1078,name:"Spline",url:"app.spline.design",desc:"3D design tool for the browser and apps.",r:4.7,cat:"3D & AR/VR",p:0},
{id:1079,name:"Sketchfab",url:"sketchfab.com",desc:"3D model marketplace and publishing platform.",r:4.6,cat:"3D & AR/VR",p:0},
{id:1080,name:"TurboSquid",url:"turbosquid.com",desc:"Largest 3D model marketplace online.",r:4.4,cat:"3D & AR/VR",p:0},
{id:1081,name:"Poly Haven",url:"polyhaven.com",desc:"Free HDRI textures and 3D model assets.",r:4.8,cat:"3D & AR/VR",p:0},
{id:1082,name:"CGTrader",url:"cgtrader.com",desc:"3D models marketplace with royalty-free assets.",r:4.3,cat:"3D & AR/VR",p:0},
{id:1083,name:"Free3D",url:"free3d.com",desc:"Free 3D models for personal and commercial use.",r:4.2,cat:"3D & AR/VR",p:0},
{id:1084,name:"Three.js",url:"threejs.org",desc:"JavaScript 3D WebGL library and editor.",r:4.8,cat:"3D & AR/VR",p:0},
{id:1085,name:"Babylon.js",url:"babylonjs.com",desc:"Powerful open-source 3D web engine.",r:4.7,cat:"3D & AR/VR",p:0},
{id:1086,name:"A-Frame",url:"aframe.io",desc:"Web framework for building VR experiences.",r:4.5,cat:"3D & AR/VR",p:0},
{id:1087,name:"Unity Learn",url:"learn.unity.com",desc:"Free tutorials for Unity game development.",r:4.6,cat:"3D & AR/VR",p:0},
{id:1088,name:"Unreal Engine",url:"unrealengine.com",desc:"Epic's powerful free game and VR engine.",r:4.8,cat:"3D & AR/VR",p:0},
{id:1089,name:"Godot",url:"godotengine.org",desc:"Free open-source 2D and 3D game engine.",r:4.8,cat:"3D & AR/VR",p:0},
{id:1090,name:"Vuforia",url:"developer.vuforia.com",desc:"Leading AR development platform for apps.",r:4.3,cat:"3D & AR/VR",p:0},
{id:1091,name:"8th Wall",url:"8thwall.com",desc:"Web AR platform for browser-based experiences.",r:4.4,cat:"3D & AR/VR",p:0},
{id:1092,name:"Niantic Lightship",url:"lightship.dev",desc:"AR developer platform by Pokémon GO makers.",r:4.3,cat:"3D & AR/VR",p:0},
{id:1093,name:"ZapWorks",url:"zap.works",desc:"AR creation platform for marketing campaigns.",r:4.2,cat:"3D & AR/VR",p:0},
{id:1094,name:"Lens Studio",url:"ar.snap.com/lens-studio",desc:"Create AR lenses for Snapchat platform.",r:4.4,cat:"3D & AR/VR",p:0},
{id:1095,name:"Spark AR",url:"sparkar.facebook.com",desc:"Build AR effects for Instagram and Facebook.",r:4.3,cat:"3D & AR/VR",p:0},
{id:1096,name:"Reality Composer",url:"developer.apple.com/augmented-reality",desc:"Apple AR development tools and frameworks.",r:4.4,cat:"3D & AR/VR",p:0},
// Podcasts & Audio
{id:1097,name:"Pocket Casts",url:"pocketcasts.com",desc:"Powerful cross-platform podcast player app.",r:4.7,cat:"Podcasts & Audio",p:0},
{id:1098,name:"Overcast",url:"overcast.fm",desc:"Smart speed and voice boost podcast player.",r:4.6,cat:"Podcasts & Audio",p:0},
{id:1099,name:"Anchor",url:"anchor.fm",desc:"Free podcast creation and hosting by Spotify.",r:4.3,cat:"Podcasts & Audio",p:0},
{id:1100,name:"Buzzsprout",url:"buzzsprout.com",desc:"Simple podcast hosting for new podcasters.",r:4.5,cat:"Podcasts & Audio",p:0},
{id:1101,name:"Podbean",url:"podbean.com",desc:"Podcast hosting with monetization features.",r:4.3,cat:"Podcasts & Audio",p:0},
{id:1102,name:"Transistor",url:"transistor.fm",desc:"Professional podcast hosting for businesses.",r:4.7,cat:"Podcasts & Audio",p:0},
{id:1103,name:"Captivate",url:"captivate.fm",desc:"Growth-focused podcast hosting platform.",r:4.5,cat:"Podcasts & Audio",p:0},
{id:1104,name:"Riverside.fm",url:"riverside.fm",desc:"Record studio-quality remote podcast interviews.",r:4.6,cat:"Podcasts & Audio",p:0},
{id:1105,name:"Zencastr",url:"zencastr.com",desc:"High-quality remote podcast recording tool.",r:4.4,cat:"Podcasts & Audio",p:0},
{id:1106,name:"Adobe Podcast",url:"podcast.adobe.com",desc:"AI audio enhancement and recording tool.",r:4.5,cat:"Podcasts & Audio",p:0},
{id:1107,name:"Descript",url:"web.descript.com",desc:"Edit audio and video like a document.",r:4.7,cat:"Podcasts & Audio",p:0},
{id:1108,name:"Reaper",url:"reaper.fm",desc:"Affordable professional DAW for audio.",r:4.7,cat:"Podcasts & Audio",p:0},
{id:1109,name:"Simplecast",url:"simplecast.com",desc:"Podcast hosting with powerful analytics.",r:4.4,cat:"Podcasts & Audio",p:0},
{id:1110,name:"Spreaker",url:"spreaker.com",desc:"Live podcast broadcasting and hosting.",r:4.2,cat:"Podcasts & Audio",p:0},
{id:1111,name:"Libsyn",url:"libsyn.com",desc:"Pioneer podcast hosting and distribution.",r:4.3,cat:"Podcasts & Audio",p:0},
{id:1112,name:"SoundCloud Podcasts",url:"soundcloud.com",desc:"Audio hosting with massive discovery network.",r:4.3,cat:"Podcasts & Audio",p:0},
{id:1113,name:"ListenNotes",url:"listennotes.com",desc:"Best podcast search engine database.",r:4.6,cat:"Podcasts & Audio",p:0},
// Language & Translation
{id:1114,name:"Google Translate",url:"translate.google.com",desc:"Instant translation for 130+ languages.",r:4.5,cat:"Language & Translation",p:0},
{id:1115,name:"DeepL",url:"deepl.com",desc:"AI translator that beats Google in accuracy.",r:4.8,cat:"Language & Translation",p:0},
{id:1116,name:"Microsoft Translator",url:"translator.microsoft.com",desc:"Real-time translation for conversations.",r:4.4,cat:"Language & Translation",p:0},
{id:1117,name:"Reverso",url:"reverso.net",desc:"Translation with context and conjugations.",r:4.5,cat:"Language & Translation",p:0},
{id:1118,name:"Papago",url:"papago.naver.com",desc:"Naver's high-quality Korean-focused translator.",r:4.5,cat:"Language & Translation",p:0},
{id:1119,name:"Dict.cc",url:"dict.cc",desc:"Community-built German-English dictionary.",r:4.5,cat:"Language & Translation",p:0},
{id:1120,name:"WordReference",url:"wordreference.com",desc:"Language dictionaries with active forums.",r:4.6,cat:"Language & Translation",p:0},
{id:1121,name:"Linguee",url:"linguee.com",desc:"Translation with real-world usage examples.",r:4.6,cat:"Language & Translation",p:0},
{id:1122,name:"Merriam-Webster",url:"merriam-webster.com",desc:"America's most trusted English dictionary.",r:4.7,cat:"Language & Translation",p:0},
{id:1123,name:"Cambridge Dictionary",url:"dictionary.cambridge.org",desc:"British English dictionary with audio.",r:4.7,cat:"Language & Translation",p:0},
{id:1124,name:"Oxford Learner's",url:"oxfordlearnersdictionaries.com",desc:"Oxford dictionary for English learners.",r:4.6,cat:"Language & Translation",p:0},
{id:1125,name:"Collins",url:"collinsdictionary.com",desc:"Dictionary with thesaurus and language tools.",r:4.5,cat:"Language & Translation",p:0},
{id:1126,name:"Forvo",url:"forvo.com",desc:"Pronunciation dictionary by native speakers.",r:4.6,cat:"Language & Translation",p:0},
{id:1127,name:"Tatoeba",url:"tatoeba.org",desc:"Multilingual sentence examples database.",r:4.4,cat:"Language & Translation",p:0},
{id:1128,name:"Anki",url:"ankiweb.net",desc:"Spaced repetition flashcard learning system.",r:4.7,cat:"Language & Translation",p:0},
{id:1129,name:"Babbel",url:"babbel.com",desc:"Subscription language learning with lessons.",r:4.3,cat:"Language & Translation",p:0},
{id:1130,name:"Rosetta Stone",url:"rosettastone.com",desc:"Immersive language learning software.",r:4.1,cat:"Language & Translation",p:0},
{id:1131,name:"Pimsleur",url:"pimsleur.com",desc:"Audio-based language learning method.",r:4.2,cat:"Language & Translation",p:0},
{id:1132,name:"italki",url:"italki.com",desc:"Connect with native language tutors online.",r:4.6,cat:"Language & Translation",p:0},
{id:1133,name:"Preply",url:"preply.com",desc:"Online tutoring marketplace for languages.",r:4.4,cat:"Language & Translation",p:0},
];
