window.APPS_2 = [
// AI Tools
{id:81,name:"Stable Diffusion",url:"stablediffusionweb.com",desc:"Generate stunning AI images from text prompts.",r:4.6,cat:"AI Tools",p:0},
{id:82,name:"DALL-E 3",url:"openai.com/dall-e-3",desc:"OpenAI's most capable image generation model.",r:4.7,cat:"AI Tools",p:0},
{id:83,name:"Adobe Firefly",url:"firefly.adobe.com",desc:"Adobe's generative AI for creative professionals.",r:4.5,cat:"AI Tools",p:0},
{id:84,name:"Ideogram",url:"ideogram.ai",desc:"AI image generation with excellent text rendering.",r:4.5,cat:"AI Tools",p:0},
{id:85,name:"Leonardo.ai",url:"leonardo.ai",desc:"AI art generation for game assets and creative work.",r:4.6,cat:"AI Tools",p:0},
{id:86,name:"Krea",url:"krea.ai",desc:"Real-time AI image generation and enhancement.",r:4.4,cat:"AI Tools",p:0},
{id:87,name:"NightCafe",url:"creator.nightcafe.studio",desc:"AI art generator with community and daily challenges.",r:4.3,cat:"AI Tools",p:0},
{id:88,name:"Lexica",url:"lexica.art",desc:"Stable Diffusion image search and generation engine.",r:4.4,cat:"AI Tools",p:0},
{id:89,name:"Artbreeder",url:"artbreeder.com",desc:"Blend and evolve images using generative AI.",r:4.3,cat:"AI Tools",p:0},
{id:90,name:"Pika",url:"pika.art",desc:"AI video generation from text and image prompts.",r:4.5,cat:"AI Tools",p:0},
{id:91,name:"Kling AI",url:"klingai.com",desc:"High-quality AI video generation platform.",r:4.4,cat:"AI Tools",p:0},
{id:92,name:"HeyGen",url:"app.heygen.com",desc:"AI video generation with realistic avatars.",r:4.5,cat:"AI Tools",p:0},
{id:93,name:"Synthesia",url:"synthesia.io",desc:"Create AI videos with lifelike digital presenters.",r:4.6,cat:"AI Tools",p:0},
{id:94,name:"D-ID",url:"studio.d-id.com",desc:"Animate photos and create AI talking head videos.",r:4.4,cat:"AI Tools",p:0},
{id:95,name:"Captions.ai",url:"captions.ai",desc:"AI-powered video captions and editing tool.",r:4.4,cat:"AI Tools",p:0},
{id:96,name:"Descript",url:"web.descript.com",desc:"Edit video and audio by editing text transcript.",r:4.6,cat:"AI Tools",p:0},
{id:97,name:"Pictory",url:"app.pictory.ai",desc:"Turn long-form content into short shareable videos.",r:4.3,cat:"AI Tools",p:0},
{id:98,name:"InVideo",url:"invideo.io",desc:"AI-powered online video creation and editing.",r:4.4,cat:"AI Tools",p:0},
{id:99,name:"PlayHT",url:"play.ht",desc:"AI text-to-speech with ultra-realistic voices.",r:4.5,cat:"AI Tools",p:0},
{id:100,name:"Murf",url:"murf.ai",desc:"Studio-quality AI voiceover for any content.",r:4.5,cat:"AI Tools",p:0},
{id:101,name:"Speechify",url:"speechify.com",desc:"Text-to-speech tool to listen to any content.",r:4.4,cat:"AI Tools",p:0},
{id:102,name:"Luma AI",url:"lumalabs.ai",desc:"Capture and generate 3D models with AI.",r:4.5,cat:"AI Tools",p:0},
{id:103,name:"Udio",url:"udio.com",desc:"Generate original music tracks with AI.",r:4.4,cat:"AI Tools",p:0},
{id:104,name:"Character.ai",url:"character.ai",desc:"Chat with AI characters and create your own.",r:4.5,cat:"AI Tools",p:0},
{id:105,name:"Replika",url:"replika.com",desc:"Your personal AI companion for meaningful chat.",r:4.2,cat:"AI Tools",p:0},
{id:106,name:"Pi.ai",url:"pi.ai",desc:"Personal AI that listens, thinks, and responds.",r:4.4,cat:"AI Tools",p:0},
{id:107,name:"LM Studio",url:"lmstudio.ai",desc:"Run local LLMs on your laptop, offline.",r:4.7,cat:"AI Tools",p:0},
{id:108,name:"Ollama",url:"ollama.ai",desc:"Run large language models locally with ease.",r:4.7,cat:"AI Tools",p:0},
{id:109,name:"Dify",url:"dify.ai",desc:"Open-source LLM app development platform.",r:4.6,cat:"AI Tools",p:0},
{id:110,name:"Flowise",url:"flowiseai.com",desc:"Build LLM flows visually with drag-and-drop.",r:4.5,cat:"AI Tools",p:0},
{id:111,name:"Gamma",url:"gamma.app",desc:"Create beautiful AI-powered presentations fast.",r:4.5,cat:"AI Tools",p:0},
{id:112,name:"Beautiful.ai",url:"beautiful.ai",desc:"Smart presentation software with AI design.",r:4.4,cat:"AI Tools",p:0},
{id:113,name:"Tome",url:"tome.app",desc:"AI-native storytelling and presentation tool.",r:4.3,cat:"AI Tools",p:0},
{id:114,name:"Otter.ai",url:"otter.ai",desc:"AI meeting transcription and note-taking.",r:4.5,cat:"AI Tools",p:0},
{id:115,name:"Fireflies.ai",url:"fireflies.ai",desc:"AI notetaker that records and transcribes meetings.",r:4.5,cat:"AI Tools",p:0},
{id:116,name:"Consensus",url:"consensus.app",desc:"Search scientific papers with AI-powered answers.",r:4.5,cat:"AI Tools",p:0},
{id:117,name:"Elicit",url:"elicit.org",desc:"AI research assistant for literature review.",r:4.5,cat:"AI Tools",p:0},
{id:118,name:"Phind",url:"phind.com",desc:"AI search engine for developers and coders.",r:4.6,cat:"AI Tools",p:0},
{id:119,name:"You.com",url:"you.com",desc:"AI-powered search engine with chat interface.",r:4.3,cat:"AI Tools",p:0},
{id:120,name:"Mistral AI",url:"console.mistral.ai",desc:"Access and deploy Mistral's efficient LLMs.",r:4.6,cat:"AI Tools",p:0},
{id:121,name:"Together AI",url:"api.together.xyz",desc:"Run open-source AI models in the cloud fast.",r:4.5,cat:"AI Tools",p:0},
{id:122,name:"Replicate",url:"replicate.com",desc:"Run AI models with a simple API in the cloud.",r:4.6,cat:"AI Tools",p:0},
{id:123,name:"Cohere",url:"dashboard.cohere.com",desc:"Enterprise AI platform for NLP and generation.",r:4.5,cat:"AI Tools",p:0},
{id:124,name:"Google AI Studio",url:"aistudio.google.com",desc:"Build and prototype with Google's Gemini models.",r:4.6,cat:"AI Tools",p:0},
{id:125,name:"Stability AI",url:"platform.stability.ai",desc:"API access to Stable Diffusion and other models.",r:4.4,cat:"AI Tools",p:0},
// Developers
{id:126,name:"GitLab",url:"gitlab.com/dashboard",desc:"DevSecOps platform for the entire SDLC.",r:4.6,cat:"Developers",p:0},
{id:127,name:"Bitbucket",url:"bitbucket.org",desc:"Git code hosting with Jira and CI/CD integration.",r:4.3,cat:"Developers",p:0},
{id:128,name:"Gitea",url:"gitea.io",desc:"Lightweight self-hosted Git service.",r:4.5,cat:"Developers",p:0},
{id:129,name:"Sourcehut",url:"sr.ht",desc:"Minimal, privacy-focused software forge.",r:4.3,cat:"Developers",p:0},
{id:130,name:"CodePen",url:"codepen.io",desc:"Social development environment for front-end.",r:4.6,cat:"Developers",p:0},
{id:131,name:"JSFiddle",url:"jsfiddle.net",desc:"Online playground for HTML, CSS, and JavaScript.",r:4.3,cat:"Developers",p:0},
{id:132,name:"StackBlitz",url:"stackblitz.com",desc:"Instant full-stack web IDE in the browser.",r:4.6,cat:"Developers",p:0},
{id:133,name:"CodeSandbox",url:"codesandbox.io",desc:"Online sandbox for rapid web development.",r:4.5,cat:"Developers",p:0},
{id:134,name:"Glitch",url:"glitch.com",desc:"Friendly community for building web apps.",r:4.3,cat:"Developers",p:0},
{id:135,name:"Bolt.new",url:"bolt.new",desc:"AI-powered full-stack web development in browser.",r:4.7,cat:"Developers",p:0},
{id:136,name:"v0.dev",url:"v0.dev",desc:"Generate UI components with AI from Vercel.",r:4.7,cat:"Developers",p:0},
{id:137,name:"Lovable",url:"lovable.dev",desc:"Build full-stack apps by chatting with AI.",r:4.6,cat:"Developers",p:0},
{id:138,name:"DigitalOcean",url:"cloud.digitalocean.com",desc:"Simple cloud hosting for developers and startups.",r:4.6,cat:"Developers",p:0},
{id:139,name:"Hetzner Cloud",url:"console.hetzner.cloud",desc:"Affordable, high-performance cloud servers.",r:4.7,cat:"Developers",p:0},
{id:140,name:"Vultr",url:"my.vultr.com",desc:"High-performance SSD cloud servers worldwide.",r:4.5,cat:"Developers",p:0},
{id:141,name:"Render",url:"dashboard.render.com",desc:"Unified cloud platform for apps and databases.",r:4.5,cat:"Developers",p:0},
{id:142,name:"Fly.io",url:"fly.io/dashboard",desc:"Deploy full-stack apps close to your users.",r:4.6,cat:"Developers",p:0},
{id:143,name:"Coolify",url:"coolify.io",desc:"Open-source self-hostable Heroku/Netlify alt.",r:4.6,cat:"Developers",p:0},
{id:144,name:"PlanetScale",url:"app.planetscale.com",desc:"Serverless MySQL database with branching workflow.",r:4.7,cat:"Developers",p:0},
{id:145,name:"Neon",url:"console.neon.tech",desc:"Serverless Postgres with branching and autoscaling.",r:4.7,cat:"Developers",p:0},
{id:146,name:"MongoDB Atlas",url:"cloud.mongodb.com",desc:"Fully managed cloud MongoDB database service.",r:4.6,cat:"Developers",p:0},
{id:147,name:"Redis Cloud",url:"app.redislabs.com",desc:"Managed Redis and NoSQL cloud database.",r:4.5,cat:"Developers",p:0},
{id:148,name:"Turso",url:"turso.tech",desc:"Edge SQLite database built on libSQL.",r:4.5,cat:"Developers",p:0},
{id:149,name:"CockroachDB",url:"cockroachlabs.cloud",desc:"Distributed SQL database for global apps.",r:4.5,cat:"Developers",p:0},
{id:150,name:"Prisma",url:"prisma.io",desc:"Next-generation ORM for Node.js and TypeScript.",r:4.7,cat:"Developers",p:0},
{id:151,name:"Hoppscotch",url:"hoppscotch.io",desc:"Open-source lightweight API development tool.",r:4.6,cat:"Developers",p:0},
{id:152,name:"Insomnia",url:"insomnia.rest",desc:"Collaborative API client for REST and GraphQL.",r:4.4,cat:"Developers",p:0},
{id:153,name:"Bruno",url:"usebruno.com",desc:"Fast Git-friendly open-source API client.",r:4.6,cat:"Developers",p:0},
{id:154,name:"HTTPie",url:"httpie.io",desc:"Human-friendly API testing tool and client.",r:4.5,cat:"Developers",p:0},
{id:155,name:"RapidAPI",url:"rapidapi.com",desc:"World's largest API hub and marketplace.",r:4.4,cat:"Developers",p:0},
{id:156,name:"BrowserStack",url:"browserstack.com",desc:"Test on real browsers and devices in the cloud.",r:4.5,cat:"Developers",p:0},
{id:157,name:"LambdaTest",url:"lambdatest.com",desc:"Cross-browser testing cloud platform.",r:4.4,cat:"Developers",p:0},
{id:158,name:"Gitpod",url:"gitpod.io",desc:"Cloud development environments for teams.",r:4.5,cat:"Developers",p:0},
{id:159,name:"GitHub Codespaces",url:"github.com/codespaces",desc:"Full VS Code dev environment in the browser.",r:4.6,cat:"Developers",p:0},
{id:160,name:"Zed",url:"zed.dev",desc:"High-performance multiplayer code editor.",r:4.7,cat:"Developers",p:0},
{id:161,name:"Fleet",url:"fleet.jetbrains.com",desc:"Next-generation IDE from JetBrains.",r:4.4,cat:"Developers",p:0},
{id:162,name:"Codeium",url:"codeium.com",desc:"Free AI code completion and chat for devs.",r:4.6,cat:"Developers",p:0},
{id:163,name:"Kaggle",url:"kaggle.com",desc:"Data science competitions and free datasets.",r:4.6,cat:"Developers",p:0},
{id:164,name:"npm",url:"npmjs.com",desc:"The world's largest JavaScript package registry.",r:4.5,cat:"Developers",p:0},
{id:165,name:"Bun",url:"bun.sh",desc:"Fast all-in-one JavaScript runtime and toolkit.",r:4.7,cat:"Developers",p:0},
{id:166,name:"pnpm",url:"pnpm.io",desc:"Fast, disk-efficient Node.js package manager.",r:4.7,cat:"Developers",p:0},
{id:167,name:"Playwright",url:"playwright.dev",desc:"Reliable end-to-end testing for web apps.",r:4.7,cat:"Developers",p:0},
{id:168,name:"Cypress",url:"cypress.io",desc:"Fast, reliable testing for modern web apps.",r:4.6,cat:"Developers",p:0},
{id:169,name:"Wappalyzer",url:"wappalyzer.com",desc:"Identify tech stacks used on any website.",r:4.4,cat:"Developers",p:0},
{id:170,name:"BuiltWith",url:"builtwith.com",desc:"Discover what technology websites are built with.",r:4.3,cat:"Developers",p:0},
// Cyber Security
{id:171,name:"Shodan",url:"shodan.io",desc:"Search engine for Internet-connected devices.",r:4.7,cat:"Cyber Security",p:0},
{id:172,name:"Censys",url:"search.censys.io",desc:"Internet-wide scan data and attack surface mgmt.",r:4.6,cat:"Cyber Security",p:0},
{id:173,name:"VirusTotal",url:"virustotal.com",desc:"Analyze suspicious files, URLs, and IPs.",r:4.8,cat:"Cyber Security",p:0},
{id:174,name:"HaveIBeenPwned",url:"haveibeenpwned.com",desc:"Check if your email was in a data breach.",r:4.8,cat:"Cyber Security",p:0},
{id:175,name:"Hack The Box",url:"app.hackthebox.com",desc:"Hands-on cybersecurity training platform.",r:4.8,cat:"Cyber Security",p:0},
{id:176,name:"PicoCTF",url:"picoctf.org",desc:"Free CTF platform for beginner security learners.",r:4.7,cat:"Cyber Security",p:0},
{id:177,name:"OverTheWire",url:"overthewire.org",desc:"Learn security via wargame challenges.",r:4.7,cat:"Cyber Security",p:0},
{id:178,name:"NVD",url:"nvd.nist.gov",desc:"US national vulnerability database by NIST.",r:4.7,cat:"Cyber Security",p:0},
{id:179,name:"Exploit-DB",url:"exploit-db.com",desc:"Archive of public exploits and vulnerable software.",r:4.7,cat:"Cyber Security",p:0},
{id:180,name:"URLScan.io",url:"urlscan.io",desc:"Scan and analyze suspicious URLs safely.",r:4.7,cat:"Cyber Security",p:0},
{id:181,name:"OSINT Framework",url:"osintframework.com",desc:"Collection of OSINT tools organized by category.",r:4.6,cat:"Cyber Security",p:0},
{id:182,name:"GreyNoise",url:"viz.greynoise.io",desc:"Visualize and block internet background noise.",r:4.6,cat:"Cyber Security",p:0},
{id:183,name:"AlienVault OTX",url:"otx.alienvault.com",desc:"Open threat intelligence community platform.",r:4.6,cat:"Cyber Security",p:0},
{id:184,name:"AbuseIPDB",url:"abuseipdb.com",desc:"Report and check IP addresses for abuse.",r:4.6,cat:"Cyber Security",p:0},
{id:185,name:"Hybrid Analysis",url:"hybrid-analysis.com",desc:"Free malware analysis and sandbox service.",r:4.6,cat:"Cyber Security",p:0},
{id:186,name:"Any.run",url:"app.any.run",desc:"Interactive online malware sandbox tool.",r:4.6,cat:"Cyber Security",p:0},
{id:187,name:"Maltego",url:"maltego.com",desc:"OSINT and link analysis investigation platform.",r:4.5,cat:"Cyber Security",p:0},
{id:188,name:"SpiderFoot",url:"spiderfoot.net",desc:"Automate OSINT for threat intelligence gathering.",r:4.5,cat:"Cyber Security",p:0},
{id:189,name:"MISP",url:"misp-project.org",desc:"Open-source threat intelligence sharing platform.",r:4.5,cat:"Cyber Security",p:0},
{id:190,name:"Snyk",url:"app.snyk.io",desc:"Find and fix vulnerabilities in your code and deps.",r:4.6,cat:"Cyber Security",p:0},
{id:191,name:"Socket.dev",url:"socket.dev",desc:"Protect against supply chain attacks in npm.",r:4.6,cat:"Cyber Security",p:0},
{id:192,name:"OWASP ZAP",url:"zaproxy.org",desc:"Open-source web app security scanner tool.",r:4.6,cat:"Cyber Security",p:0},
{id:193,name:"Burp Suite",url:"portswigger.net",desc:"Leading toolkit for web application security testing.",r:4.8,cat:"Cyber Security",p:0},
{id:194,name:"Wireshark",url:"wireshark.org",desc:"The world's most popular network protocol analyzer.",r:4.8,cat:"Cyber Security",p:0},
{id:195,name:"Metasploit",url:"metasploit.com",desc:"World's most used penetration testing framework.",r:4.7,cat:"Cyber Security",p:0},
{id:196,name:"Nikto",url:"cirt.net/nikto2",desc:"Open-source web server vulnerability scanner.",r:4.4,cat:"Cyber Security",p:0},
{id:197,name:"DeHashed",url:"dehashed.com",desc:"Search compromised credentials and data breaches.",r:4.5,cat:"Cyber Security",p:0},
{id:198,name:"IntelX",url:"intelx.io",desc:"Intelligence X search engine for OSINT.",r:4.5,cat:"Cyber Security",p:0},
{id:199,name:"Triage",url:"tria.ge",desc:"Fast public malware sandbox analysis platform.",r:4.5,cat:"Cyber Security",p:0},
{id:200,name:"FOFA",url:"fofa.info",desc:"Cyberspace asset search engine for security.",r:4.4,cat:"Cyber Security",p:0},
{id:201,name:"BinaryEdge",url:"app.binaryedge.io",desc:"Internet scanning and cyber threat intelligence.",r:4.4,cat:"Cyber Security",p:0},
{id:202,name:"CVE Mitre",url:"cve.mitre.org",desc:"Common Vulnerabilities and Exposures database.",r:4.7,cat:"Cyber Security",p:0},
{id:203,name:"PacketStorm",url:"packetstormsecurity.com",desc:"Security tools, exploits, and advisories.",r:4.4,cat:"Cyber Security",p:0},
{id:204,name:"Pentest-Tools",url:"pentest-tools.com",desc:"Online pentesting toolkit for security pros.",r:4.4,cat:"Cyber Security",p:0},
{id:205,name:"CyberChef",url:"gchq.github.io/CyberChef",desc:"Web app for encryption, encoding, and analysis.",r:4.8,cat:"Cyber Security",p:0},
// Design
{id:206,name:"Spline",url:"app.spline.design",desc:"Design and collaborate on 3D web experiences.",r:4.7,cat:"Design",p:0},
{id:207,name:"Webflow",url:"webflow.com/dashboard",desc:"Visual web design and CMS platform.",r:4.6,cat:"Design",p:0},
{id:208,name:"Excalidraw",url:"excalidraw.com",desc:"Virtual whiteboard for hand-drawn style diagrams.",r:4.8,cat:"Design",p:0},
{id:209,name:"Whimsical",url:"whimsical.com",desc:"Flowcharts, wireframes, and mind maps tool.",r:4.6,cat:"Design",p:0},
{id:210,name:"Penpot",url:"design.penpot.app",desc:"Open-source design and prototyping platform.",r:4.5,cat:"Design",p:0},
{id:211,name:"LottieFiles",url:"lottiefiles.com",desc:"Create and share lightweight Lottie animations.",r:4.6,cat:"Design",p:0},
{id:212,name:"Rive",url:"rive.app",desc:"Design and ship interactive animations anywhere.",r:4.7,cat:"Design",p:0},
{id:213,name:"Sketch",url:"sketch.com",desc:"Digital design toolkit for Mac and the web.",r:4.5,cat:"Design",p:0},
{id:214,name:"Adobe XD",url:"xd.adobe.com",desc:"UI/UX design and prototyping from Adobe.",r:4.3,cat:"Design",p:0},
{id:215,name:"Lunacy",url:"icons8.com/lunacy",desc:"Free graphic design software with built-in assets.",r:4.5,cat:"Design",p:0},
{id:216,name:"Plasmic",url:"plasmic.app",desc:"Visual builder for React apps and websites.",r:4.5,cat:"Design",p:0},
{id:217,name:"Visme",url:"visme.co",desc:"Create infographics, presentations, and visuals.",r:4.4,cat:"Design",p:0},
{id:218,name:"ColorHunt",url:"colorhunt.co",desc:"Curated collection of beautiful color palettes.",r:4.6,cat:"Design",p:0},
{id:219,name:"Coolors",url:"coolors.co",desc:"Super-fast color scheme generator for designers.",r:4.7,cat:"Design",p:0},
{id:220,name:"Adobe Color",url:"color.adobe.com",desc:"Create color palettes from the color wheel.",r:4.6,cat:"Design",p:0},
{id:221,name:"Khroma",url:"khroma.co",desc:"AI color tool to generate palettes you love.",r:4.5,cat:"Design",p:0},
{id:222,name:"Unsplash",url:"unsplash.com",desc:"Beautiful free photos from talented photographers.",r:4.7,cat:"Design",p:0},
{id:223,name:"Pexels",url:"pexels.com",desc:"Free stock photos and videos by creators.",r:4.7,cat:"Design",p:0},
{id:224,name:"Pixabay",url:"pixabay.com",desc:"Free images, videos, and music for any project.",r:4.6,cat:"Design",p:0},
{id:225,name:"Remove.bg",url:"remove.bg",desc:"Remove image backgrounds automatically with AI.",r:4.7,cat:"Design",p:0},
{id:226,name:"Cleanup.pictures",url:"cleanup.pictures",desc:"Remove unwanted objects from photos with AI.",r:4.6,cat:"Design",p:0},
{id:227,name:"Smartmockups",url:"smartmockups.com",desc:"Create stunning product mockups in seconds.",r:4.5,cat:"Design",p:0},
{id:228,name:"Mockuuups",url:"mockuuups.studio",desc:"Beautiful device mockup generator for designers.",r:4.5,cat:"Design",p:0},
{id:229,name:"Rotato",url:"rotato.app",desc:"3D device mockups and animated product videos.",r:4.6,cat:"Design",p:0},
{id:230,name:"Awwwards",url:"awwwards.com",desc:"Awards recognizing the best web design talent.",r:4.7,cat:"Design",p:0},
{id:231,name:"CSS Design Awards",url:"cssdesignawards.com",desc:"Award platform celebrating exceptional CSS design.",r:4.5,cat:"Design",p:0},
{id:232,name:"Muzli",url:"muz.li",desc:"Design inspiration hub for creatives.",r:4.6,cat:"Design",p:0},
{id:233,name:"Figma Community",url:"figma.com/community",desc:"Templates, plugins, and resources from designers.",r:4.7,cat:"Design",p:0},
{id:234,name:"Noun Project",url:"thenounproject.com",desc:"Millions of icons and stock photos collection.",r:4.5,cat:"Design",p:0},
{id:235,name:"Flaticon",url:"flaticon.com",desc:"Largest database of free icons and stickers.",r:4.6,cat:"Design",p:0},
{id:236,name:"Lucide",url:"lucide.dev",desc:"Beautiful and consistent open-source icon set.",r:4.7,cat:"Design",p:0},
{id:237,name:"Heroicons",url:"heroicons.com",desc:"Hand-crafted SVG icons by the Tailwind team.",r:4.7,cat:"Design",p:0},
{id:238,name:"Phosphor Icons",url:"phosphoricons.com",desc:"Flexible icon family for interfaces and more.",r:4.7,cat:"Design",p:0},
{id:239,name:"Tabler Icons",url:"tabler.io/icons",desc:"4000+ free MIT-licensed high-quality SVG icons.",r:4.7,cat:"Design",p:0},
{id:240,name:"Feather Icons",url:"feathericons.com",desc:"Simply beautiful open-source icon collection.",r:4.6,cat:"Design",p:0},
// Productivity
{id:241,name:"Logseq",url:"logseq.com",desc:"Privacy-first open-source knowledge base tool.",r:4.7,cat:"Productivity",p:0},
{id:242,name:"Roam Research",url:"roamresearch.com",desc:"Note-taking tool for networked thought.",r:4.5,cat:"Productivity",p:0},
{id:243,name:"Todoist",url:"app.todoist.com",desc:"Simple yet powerful task management app.",r:4.6,cat:"Productivity",p:0},
{id:244,name:"Things",url:"culturedcode.com/things",desc:"Award-winning task manager for Apple devices.",r:4.7,cat:"Productivity",p:0},
{id:245,name:"Akiflow",url:"akiflow.com",desc:"Task management and time blocking for power users.",r:4.5,cat:"Productivity",p:0},
{id:246,name:"Toggl Track",url:"track.toggl.com",desc:"Simple time tracking for teams and freelancers.",r:4.6,cat:"Productivity",p:0},
{id:247,name:"Clockify",url:"clockify.me",desc:"Free time tracker and timesheet app for teams.",r:4.5,cat:"Productivity",p:0},
{id:248,name:"Harvest",url:"harvestapp.com",desc:"Time tracking and invoicing for businesses.",r:4.4,cat:"Productivity",p:0},
{id:249,name:"Timely",url:"memory.ai/timely",desc:"Automatic AI time tracking with zero effort.",r:4.4,cat:"Productivity",p:0},
{id:250,name:"RescueTime",url:"rescuetime.com",desc:"Automatic time tracking and focus tool.",r:4.4,cat:"Productivity",p:0},
{id:251,name:"Calendly",url:"calendly.com",desc:"Easy scheduling software for busy professionals.",r:4.6,cat:"Productivity",p:0},
{id:252,name:"Cal.com",url:"cal.com",desc:"Open-source scheduling infrastructure for all.",r:4.6,cat:"Productivity",p:0},
{id:253,name:"Doodle",url:"doodle.com",desc:"Simple scheduling and meeting planning tool.",r:4.3,cat:"Productivity",p:0},
{id:254,name:"Fantastical",url:"fantastical.app",desc:"Powerful calendar app with natural language input.",r:4.6,cat:"Productivity",p:0},
{id:255,name:"1Password",url:"1password.com",desc:"Secure password manager for individuals and teams.",r:4.7,cat:"Productivity",p:0},
{id:256,name:"Bitwarden",url:"bitwarden.com",desc:"Open-source password manager for everyone.",r:4.8,cat:"Productivity",p:0},
{id:257,name:"Dashlane",url:"dashlane.com",desc:"Password manager with real-time dark web alerts.",r:4.4,cat:"Productivity",p:0},
{id:258,name:"Loom",url:"loom.com",desc:"Record and share video messages for your team.",r:4.6,cat:"Productivity",p:0},
{id:259,name:"Scribe",url:"scribehow.com",desc:"Auto-generate step-by-step process documentation.",r:4.6,cat:"Productivity",p:0},
{id:260,name:"Tango",url:"tango.us",desc:"Capture workflows and create guides automatically.",r:4.5,cat:"Productivity",p:0},
{id:261,name:"Coda",url:"coda.io",desc:"All-in-one doc that brings words and data together.",r:4.5,cat:"Productivity",p:0},
{id:262,name:"Nuclino",url:"nuclino.com",desc:"Team wiki and collaborative workspace for docs.",r:4.5,cat:"Productivity",p:0},
{id:263,name:"Slite",url:"slite.com",desc:"AI-powered knowledge base for remote teams.",r:4.4,cat:"Productivity",p:0},
{id:264,name:"Pocket",url:"getpocket.com",desc:"Save articles and content to read later.",r:4.5,cat:"Productivity",p:0},
{id:265,name:"Raindrop.io",url:"raindrop.io",desc:"All-in-one bookmark manager for the web.",r:4.6,cat:"Productivity",p:0},
{id:266,name:"Readwise",url:"readwise.io",desc:"Review and retain your reading highlights.",r:4.6,cat:"Productivity",p:0},
{id:267,name:"Make",url:"make.com",desc:"Visual automation platform for connecting apps.",r:4.6,cat:"Productivity",p:0},
{id:268,name:"n8n",url:"n8n.io",desc:"Extendable workflow automation for technical teams.",r:4.7,cat:"Productivity",p:0},
{id:269,name:"Quip",url:"quip.com",desc:"Collaborative productivity suite by Salesforce.",r:4.3,cat:"Productivity",p:0},
{id:270,name:"Tettra",url:"tettra.com",desc:"AI-powered knowledge management for Slack teams.",r:4.3,cat:"Productivity",p:0},
{id:271,name:"Guru",url:"getguru.com",desc:"Company wiki that lives in your workflow.",r:4.4,cat:"Productivity",p:0},
{id:272,name:"Notion Calendar",url:"calendar.notion.so",desc:"Calendar that connects to your Notion workspace.",r:4.5,cat:"Productivity",p:0},
{id:273,name:"Craft",url:"craft.do",desc:"Beautiful document editor for Mac and iPad.",r:4.7,cat:"Productivity",p:0},
{id:274,name:"Capacities",url:"capacities.io",desc:"Object-based note-taking and knowledge system.",r:4.6,cat:"Productivity",p:0},
{id:275,name:"Reflect",url:"reflect.app",desc:"Networked note-taking app with AI assistance.",r:4.6,cat:"Productivity",p:0},
// Communication
{id:276,name:"Skype",url:"web.skype.com",desc:"Video calls, messaging and collaboration tool.",r:4.0,cat:"Communication",p:0},
{id:277,name:"Viber",url:"viber.com",desc:"Free messaging and calling app for everyone.",r:4.2,cat:"Communication",p:0},
{id:278,name:"Line",url:"line.me",desc:"Popular messaging app in Asia and Japan.",r:4.3,cat:"Communication",p:0},
{id:279,name:"WeChat",url:"web.wechat.com",desc:"China's super-app for messaging and payments.",r:4.1,cat:"Communication",p:0},
{id:280,name:"KakaoTalk",url:"web.kakaotalk.com",desc:"South Korea's leading mobile messenger.",r:4.2,cat:"Communication",p:0},
{id:281,name:"Wire",url:"app.wire.com",desc:"End-to-end encrypted messaging for enterprises.",r:4.4,cat:"Communication",p:0},
{id:282,name:"Element",url:"app.element.io",desc:"Secure decentralized communication on Matrix.",r:4.4,cat:"Communication",p:0},
{id:283,name:"Session",url:"getsession.org",desc:"Private messenger that requires no phone number.",r:4.5,cat:"Communication",p:0},
{id:284,name:"Keybase",url:"keybase.io",desc:"Secure messaging with end-to-end encryption.",r:4.4,cat:"Communication",p:0},
{id:285,name:"Mattermost",url:"mattermost.com",desc:"Open-source self-hosted team messaging platform.",r:4.5,cat:"Communication",p:0},
{id:286,name:"Rocket.Chat",url:"rocket.chat",desc:"Open-source team chat and omnichannel platform.",r:4.4,cat:"Communication",p:0},
{id:287,name:"Zulip",url:"zulip.com",desc:"Open-source team chat with threaded conversations.",r:4.5,cat:"Communication",p:0},
{id:288,name:"Lark",url:"larksuite.com",desc:"Collaborative suite with messaging, docs and video.",r:4.4,cat:"Communication",p:0},
{id:289,name:"Webex",url:"webex.com",desc:"Cisco's enterprise video conferencing platform.",r:4.3,cat:"Communication",p:0},
{id:290,name:"BlueJeans",url:"bluejeans.com",desc:"Cloud-based video conferencing service.",r:4.1,cat:"Communication",p:0},
{id:291,name:"GoTo Meeting",url:"gotomeeting.com",desc:"Online meeting and web conferencing solution.",r:4.2,cat:"Communication",p:0},
{id:292,name:"Crisp",url:"crisp.chat",desc:"Customer messaging platform for startups.",r:4.5,cat:"Communication",p:0},
{id:293,name:"Intercom",url:"intercom.com",desc:"AI-first customer service platform.",r:4.5,cat:"Communication",p:0},
{id:294,name:"Drift",url:"drift.com",desc:"Conversational marketing and sales platform.",r:4.3,cat:"Communication",p:0},
{id:295,name:"Zendesk",url:"zendesk.com",desc:"Customer service software and support ticketing.",r:4.4,cat:"Communication",p:0},
{id:296,name:"Twilio",url:"console.twilio.com",desc:"Cloud communications platform and messaging API.",r:4.6,cat:"Communication",p:0},
{id:297,name:"Sendbird",url:"dashboard.sendbird.com",desc:"Chat and messaging API for apps.",r:4.5,cat:"Communication",p:0},
{id:298,name:"Vonage",url:"dashboard.nexmo.com",desc:"Cloud communications and messaging APIs.",r:4.3,cat:"Communication",p:0},
{id:299,name:"Pusher",url:"pusher.com/channels",desc:"Realtime messaging and events for web apps.",r:4.5,cat:"Communication",p:0},
{id:300,name:"Ably",url:"ably.com",desc:"Realtime data delivery platform for developers.",r:4.5,cat:"Communication",p:0},
{id:301,name:"MessageBird",url:"messagebird.com",desc:"Omnichannel communication platform for business.",r:4.3,cat:"Communication",p:0},
{id:302,name:"Bandwidth",url:"bandwidth.com",desc:"CPaaS platform for voice, messaging and 911.",r:4.3,cat:"Communication",p:0},
{id:303,name:"Plivo",url:"plivo.com",desc:"SMS and voice API platform for businesses.",r:4.3,cat:"Communication",p:0},
{id:304,name:"8x8",url:"8x8.com",desc:"Unified communications and contact center cloud.",r:4.2,cat:"Communication",p:0},
{id:305,name:"RingCentral",url:"app.ringcentral.com",desc:"Cloud-based business phone and messaging system.",r:4.3,cat:"Communication",p:0},
// Social Media
{id:306,name:"Mastodon",url:"mastodon.social",desc:"Decentralized open-source social network.",r:4.4,cat:"Social Media",p:0},
{id:307,name:"Bluesky",url:"bsky.app",desc:"Decentralized social networking built on AT Protocol.",r:4.5,cat:"Social Media",p:0},
{id:308,name:"Threads",url:"threads.net",desc:"Instagram's text-based conversation app.",r:4.2,cat:"Social Media",p:0},
{id:309,name:"Tumblr",url:"tumblr.com",desc:"Microblogging and social networking platform.",r:4.0,cat:"Social Media",p:0},
{id:310,name:"BeReal",url:"bere.al",desc:"Authentic social app for real daily moments.",r:4.0,cat:"Social Media",p:0},
{id:311,name:"Snapchat",url:"web.snapchat.com",desc:"Camera and messaging app for real-time sharing.",r:4.1,cat:"Social Media",p:0},
{id:312,name:"Clubhouse",url:"clubhouse.com",desc:"Social audio app for live conversations.",r:3.9,cat:"Social Media",p:0},
{id:313,name:"Vero",url:"vero.co",desc:"Ad-free social network for authentic sharing.",r:4.1,cat:"Social Media",p:0},
{id:314,name:"MeWe",url:"mewe.com",desc:"Privacy-first social network and groups.",r:4.0,cat:"Social Media",p:0},
{id:315,name:"Quora",url:"quora.com",desc:"Q&A platform to share and grow the world's knowledge.",r:4.3,cat:"Social Media",p:0},
{id:316,name:"Medium",url:"medium.com",desc:"Publishing platform for ideas and stories.",r:4.4,cat:"Social Media",p:0},
{id:317,name:"Substack",url:"substack.com",desc:"Platform for independent writers and newsletters.",r:4.5,cat:"Social Media",p:0},
{id:318,name:"Ghost",url:"ghost.org",desc:"Open-source publishing platform for creators.",r:4.6,cat:"Social Media",p:0},
{id:319,name:"Dev.to",url:"dev.to",desc:"Community of developers sharing ideas and code.",r:4.5,cat:"Social Media",p:0},
{id:320,name:"Hacker News",url:"news.ycombinator.com",desc:"Social news for hackers and startups by YC.",r:4.6,cat:"Social Media",p:0},
{id:321,name:"Product Hunt",url:"producthunt.com",desc:"Discover the best new products every day.",r:4.6,cat:"Social Media",p:0},
{id:322,name:"Indie Hackers",url:"indiehackers.com",desc:"Community for bootstrapped founders and builders.",r:4.6,cat:"Social Media",p:0},
{id:323,name:"BetaList",url:"betalist.com",desc:"Discover upcoming internet startups early.",r:4.2,cat:"Social Media",p:0},
{id:324,name:"AngelList",url:"wellfound.com",desc:"Startup jobs and investment platform.",r:4.4,cat:"Social Media",p:0},
{id:325,name:"Goodreads",url:"goodreads.com",desc:"Book reviews and reading tracking community.",r:4.3,cat:"Social Media",p:0},
{id:326,name:"Letterboxd",url:"letterboxd.com",desc:"Social film diary for movie lovers.",r:4.6,cat:"Social Media",p:0},
{id:327,name:"Strava",url:"strava.com",desc:"Social fitness app for runners and cyclists.",r:4.5,cat:"Social Media",p:0},
{id:328,name:"Flickr",url:"flickr.com",desc:"Photo sharing and community for photographers.",r:4.1,cat:"Social Media",p:0},
{id:329,name:"SoundCloud",url:"soundcloud.com",desc:"Audio platform for music and podcasts.",r:4.3,cat:"Social Media",p:0},
{id:330,name:"Bandcamp",url:"bandcamp.com",desc:"Platform for independent musicians to sell music.",r:4.6,cat:"Social Media",p:0},
{id:331,name:"Cohost",url:"cohost.org",desc:"Artist-friendly alternative social media platform.",r:4.0,cat:"Social Media",p:0},
{id:332,name:"Pixelfed",url:"pixelfed.org",desc:"Decentralized photo sharing social network.",r:4.3,cat:"Social Media",p:0},
{id:333,name:"Lemmy",url:"lemmy.world",desc:"Open-source federated Reddit alternative.",r:4.4,cat:"Social Media",p:0},
{id:334,name:"Diaspora",url:"joindiaspora.com",desc:"Decentralized social network you control.",r:4.0,cat:"Social Media",p:0},
// Music
{id:335,name:"Apple Music",url:"music.apple.com",desc:"Apple's streaming service with 100M+ songs.",r:4.5,cat:"Music",p:0},
{id:336,name:"YouTube Music",url:"music.youtube.com",desc:"Google's music streaming with YouTube content.",r:4.3,cat:"Music",p:0},
{id:337,name:"Tidal",url:"tidal.com",desc:"HiFi music streaming with lossless audio.",r:4.4,cat:"Music",p:0},
{id:338,name:"Deezer",url:"deezer.com",desc:"Music streaming with Flow personalized radio.",r:4.3,cat:"Music",p:0},
{id:339,name:"Amazon Music",url:"music.amazon.com",desc:"Music streaming included with Amazon Prime.",r:4.2,cat:"Music",p:0},
{id:340,name:"SoundCloud Stream",url:"soundcloud.com/stream",desc:"Listen to music and creator uploads on SoundCloud.",r:4.3,cat:"Music",p:0},
{id:341,name:"Bandcamp",url:"bandcamp.com",desc:"Buy and stream music directly from artists.",r:4.6,cat:"Music",p:0},
{id:342,name:"Last.fm",url:"last.fm",desc:"Music tracking and social recommendations platform.",r:4.3,cat:"Music",p:0},
{id:343,name:"Audiomack",url:"audiomack.com",desc:"Music streaming platform for emerging artists.",r:4.3,cat:"Music",p:0},
{id:344,name:"Mixcloud",url:"mixcloud.com",desc:"Stream and upload DJ mixes and radio shows.",r:4.3,cat:"Music",p:0},
{id:345,name:"Beatport",url:"beatport.com",desc:"Electronic music store for DJs and producers.",r:4.4,cat:"Music",p:0},
{id:346,name:"Traxsource",url:"traxsource.com",desc:"Download house and electronic music for DJs.",r:4.3,cat:"Music",p:0},
{id:347,name:"Shazam",url:"shazam.com",desc:"Identify any song playing around you instantly.",r:4.6,cat:"Music",p:0},
{id:348,name:"Musixmatch",url:"musixmatch.com",desc:"Largest lyrics platform and real-time lyrics app.",r:4.4,cat:"Music",p:0},
{id:349,name:"BandLab",url:"bandlab.com",desc:"Free music creation and collaboration platform.",r:4.5,cat:"Music",p:0},
{id:350,name:"Soundtrap",url:"soundtrap.com",desc:"Online music studio for recording and production.",r:4.4,cat:"Music",p:0},
{id:351,name:"Splice",url:"splice.com",desc:"Music samples, presets, and creator tools.",r:4.5,cat:"Music",p:0},
{id:352,name:"BeatStars",url:"beatstars.com",desc:"Marketplace for producers to sell beats online.",r:4.4,cat:"Music",p:0},
{id:353,name:"Landr",url:"landr.com",desc:"AI mastering and music distribution platform.",r:4.3,cat:"Music",p:0},
{id:354,name:"DistroKid",url:"distrokid.com",desc:"Upload unlimited music to streaming platforms.",r:4.5,cat:"Music",p:0},
{id:355,name:"TuneCore",url:"tunecore.com",desc:"Distribute your music to all major platforms.",r:4.3,cat:"Music",p:0},
{id:356,name:"CD Baby",url:"cdbaby.com",desc:"Music distribution and sync licensing for artists.",r:4.2,cat:"Music",p:0},
{id:357,name:"Amuse",url:"amuse.io",desc:"Free music distribution app for independent artists.",r:4.2,cat:"Music",p:0},
{id:358,name:"Stem",url:"stem.is",desc:"Modern music distribution and payment splitting.",r:4.3,cat:"Music",p:0},
{id:359,name:"ReverbNation",url:"reverbnation.com",desc:"Tools for musicians to grow their music career.",r:4.0,cat:"Music",p:0},
// Video & Streaming
{id:360,name:"Disney+",url:"disneyplus.com",desc:"Stream Disney, Marvel, Star Wars, and Pixar.",r:4.5,cat:"Video & Streaming",p:0},
{id:361,name:"Prime Video",url:"primevideo.com",desc:"Amazon's streaming service with originals.",r:4.4,cat:"Video & Streaming",p:0},
{id:362,name:"Apple TV+",url:"tv.apple.com",desc:"Apple's original series and film streaming.",r:4.5,cat:"Video & Streaming",p:0},
{id:363,name:"Max",url:"max.com",desc:"HBO Max streaming with premium content.",r:4.4,cat:"Video & Streaming",p:0},
{id:364,name:"Peacock",url:"peacocktv.com",desc:"NBCUniversal streaming with live sports.",r:4.0,cat:"Video & Streaming",p:0},
{id:365,name:"Hulu",url:"hulu.com",desc:"Stream TV shows, movies, and live TV.",r:4.3,cat:"Video & Streaming",p:0},
{id:366,name:"Paramount+",url:"paramountplus.com",desc:"Stream Paramount's movies, shows, and sports.",r:4.1,cat:"Video & Streaming",p:0},
{id:367,name:"Crunchyroll",url:"crunchyroll.com",desc:"The best place to watch anime online.",r:4.5,cat:"Video & Streaming",p:0},
{id:368,name:"Funimation",url:"funimation.com",desc:"Dubbed and subbed anime streaming service.",r:4.2,cat:"Video & Streaming",p:0},
{id:369,name:"Vimeo",url:"vimeo.com",desc:"High-quality video hosting for creators.",r:4.5,cat:"Video & Streaming",p:0},
{id:370,name:"Plex",url:"app.plex.tv/desktop",desc:"Organize and stream your personal media library.",r:4.5,cat:"Video & Streaming",p:0},
{id:371,name:"Dailymotion",url:"dailymotion.com",desc:"Video platform for sharing and discovering content.",r:4.0,cat:"Video & Streaming",p:0},
{id:372,name:"Rumble",url:"rumble.com",desc:"Video platform for creators and free speech.",r:3.9,cat:"Video & Streaming",p:0},
{id:373,name:"Odysee",url:"odysee.com",desc:"Decentralized video platform on blockchain.",r:4.1,cat:"Video & Streaming",p:0},
{id:374,name:"Kick",url:"kick.com",desc:"Live streaming platform with creator-first focus.",r:4.2,cat:"Video & Streaming",p:0},
{id:375,name:"StreamYard",url:"streamyard.com",desc:"Live streaming studio in your browser.",r:4.6,cat:"Video & Streaming",p:0},
{id:376,name:"Restream",url:"restream.io",desc:"Stream to 30+ platforms simultaneously.",r:4.5,cat:"Video & Streaming",p:0},
{id:377,name:"Wistia",url:"wistia.com",desc:"Video hosting for business and marketing.",r:4.4,cat:"Video & Streaming",p:0},
{id:378,name:"Vidyard",url:"vidyard.com",desc:"Video platform for business and sales teams.",r:4.4,cat:"Video & Streaming",p:0},
{id:379,name:"Loom",url:"loom.com",desc:"Async video messaging for remote teams.",r:4.6,cat:"Video & Streaming",p:0},
{id:380,name:"Veed.io",url:"veed.io",desc:"Online video editing with subtitles and effects.",r:4.5,cat:"Video & Streaming",p:0},
{id:381,name:"Kapwing",url:"kapwing.com",desc:"Online video editor for content creators.",r:4.4,cat:"Video & Streaming",p:0},
{id:382,name:"Clipchamp",url:"clipchamp.com",desc:"Microsoft's free online video editor.",r:4.3,cat:"Video & Streaming",p:0},
{id:383,name:"DaVinci Resolve",url:"blackmagicdesign.com",desc:"Professional video editing and color grading.",r:4.8,cat:"Video & Streaming",p:0},
{id:384,name:"Kdenlive",url:"kdenlive.org",desc:"Free and open-source video editor.",r:4.4,cat:"Video & Streaming",p:0},
{id:385,name:"Jellyfin",url:"jellyfin.org",desc:"Free open-source media server solution.",r:4.7,cat:"Video & Streaming",p:0},
{id:386,name:"Emby",url:"emby.media",desc:"Personal media server for streaming at home.",r:4.4,cat:"Video & Streaming",p:0},
{id:387,name:"Stremio",url:"stremio.com",desc:"One-place video content aggregator and player.",r:4.5,cat:"Video & Streaming",p:0},
{id:388,name:"Mubi",url:"mubi.com",desc:"Curated streaming for indie and arthouse films.",r:4.5,cat:"Video & Streaming",p:0},
{id:389,name:"Criterion Channel",url:"criterionchannel.com",desc:"Stream classic and contemporary films.",r:4.7,cat:"Video & Streaming",p:0},
// Science & Research
{id:390,name:"arXiv",url:"arxiv.org",desc:"Open access preprints in STEM disciplines.",r:4.8,cat:"Science & Research",p:0},
{id:391,name:"Semantic Scholar",url:"semanticscholar.org",desc:"AI-powered tool for scientific literature.",r:4.7,cat:"Science & Research",p:0},
{id:392,name:"PubMed",url:"pubmed.ncbi.nlm.nih.gov",desc:"Biomedical literature database by NCBI.",r:4.7,cat:"Science & Research",p:0},
{id:393,name:"Google Scholar",url:"scholar.google.com",desc:"Search across all scholarly literature freely.",r:4.8,cat:"Science & Research",p:0},
{id:394,name:"ResearchGate",url:"researchgate.net",desc:"Network for scientists to share research papers.",r:4.5,cat:"Science & Research",p:0},
{id:395,name:"Connected Papers",url:"connectedpapers.com",desc:"Explore connected academic papers visually.",r:4.6,cat:"Science & Research",p:0},
{id:396,name:"Inciteful",url:"inciteful.xyz",desc:"Build academic paper network from a seed paper.",r:4.5,cat:"Science & Research",p:0},
{id:397,name:"Open Knowledge Maps",url:"openknowledgemaps.org",desc:"Visual interface for scientific knowledge.",r:4.5,cat:"Science & Research",p:0},
{id:398,name:"Wolfram Alpha",url:"wolframalpha.com",desc:"Computational intelligence for math and science.",r:4.7,cat:"Science & Research",p:0},
{id:399,name:"Symbolab",url:"symbolab.com",desc:"Math problem solver with step-by-step solutions.",r:4.5,cat:"Science & Research",p:0},
{id:400,name:"Desmos",url:"desmos.com",desc:"Interactive graphing calculator for mathematics.",r:4.8,cat:"Science & Research",p:0},
{id:401,name:"GeoGebra",url:"geogebra.org",desc:"Dynamic math tools for all levels of education.",r:4.7,cat:"Science & Research",p:0},
{id:402,name:"Mathway",url:"mathway.com",desc:"Math problem solver for algebra through calculus.",r:4.4,cat:"Science & Research",p:0},
{id:403,name:"JSTOR",url:"jstor.org",desc:"Digital library of academic journals and books.",r:4.5,cat:"Science & Research",p:0},
{id:404,name:"OpenAlex",url:"openalex.org",desc:"Free and open catalog of scholarly works.",r:4.5,cat:"Science & Research",p:0},
{id:405,name:"Crossref",url:"crossref.org",desc:"Official DOI registration agency for research.",r:4.4,cat:"Science & Research",p:0},
{id:406,name:"Nature",url:"nature.com",desc:"International journal of science and research.",r:4.7,cat:"Science & Research",p:0},
{id:407,name:"PLOS ONE",url:"journals.plos.org",desc:"Open access peer-reviewed scientific journal.",r:4.6,cat:"Science & Research",p:0},
{id:408,name:"eLife",url:"elifesciences.org",desc:"Open-access journal for life and biomedical science.",r:4.6,cat:"Science & Research",p:0},
{id:409,name:"PhET Simulations",url:"phet.colorado.edu",desc:"Interactive science and math simulations.",r:4.8,cat:"Science & Research",p:0},
{id:410,name:"NASA",url:"nasa.gov",desc:"Space exploration, science, and aeronautics.",r:4.8,cat:"Science & Research",p:0},
{id:411,name:"CERN",url:"home.cern",desc:"European laboratory for particle physics research.",r:4.7,cat:"Science & Research",p:0},
{id:412,name:"NIH",url:"nih.gov",desc:"National Institutes of Health research and funding.",r:4.6,cat:"Science & Research",p:0},
{id:413,name:"Scite",url:"scite.ai",desc:"See how research has been cited and analyzed.",r:4.5,cat:"Science & Research",p:0},
{id:414,name:"ResearchRabbit",url:"researchrabbit.ai",desc:"AI tool to discover related research papers.",r:4.6,cat:"Science & Research",p:0},
{id:415,name:"Iris.ai",url:"iris.ai",desc:"AI workspace for scientific research.",r:4.4,cat:"Science & Research",p:0},
{id:416,name:"Mendeley",url:"mendeley.com",desc:"Reference manager and academic social network.",r:4.4,cat:"Science & Research",p:0},
{id:417,name:"Zotero",url:"zotero.org",desc:"Free open-source reference management software.",r:4.7,cat:"Science & Research",p:0},
{id:418,name:"Papers",url:"papersapp.com",desc:"Reference manager for researchers and students.",r:4.3,cat:"Science & Research",p:0},
// Health & Fitness
{id:419,name:"MyFitnessPal",url:"myfitnesspal.com",desc:"Calorie counter and diet tracker app.",r:4.5,cat:"Health & Fitness",p:0},
{id:420,name:"Cronometer",url:"cronometer.com",desc:"Track nutrition and micronutrients accurately.",r:4.6,cat:"Health & Fitness",p:0},
{id:421,name:"Lose It!",url:"loseit.com",desc:"Calorie counting and weight loss tracking app.",r:4.4,cat:"Health & Fitness",p:0},
{id:422,name:"Noom",url:"noom.com",desc:"Psychology-based weight loss and health program.",r:4.1,cat:"Health & Fitness",p:0},
{id:423,name:"MacroFactor",url:"macrofactorapp.com",desc:"Smart nutrition coaching with adaptive feedback.",r:4.7,cat:"Health & Fitness",p:0},
{id:424,name:"Headspace",url:"headspace.com",desc:"Guided meditation and mindfulness for everyone.",r:4.6,cat:"Health & Fitness",p:0},
{id:425,name:"Calm",url:"calm.com",desc:"App for sleep, meditation, and relaxation.",r:4.6,cat:"Health & Fitness",p:0},
{id:426,name:"Waking Up",url:"wakingup.com",desc:"Meditation app with deep philosophy content.",r:4.7,cat:"Health & Fitness",p:0},
{id:427,name:"Insight Timer",url:"insighttimer.com",desc:"Free meditation app with largest teacher library.",r:4.7,cat:"Health & Fitness",p:0},
{id:428,name:"Ten Percent Happier",url:"tenpercent.com",desc:"Meditation for skeptics with expert teachers.",r:4.6,cat:"Health & Fitness",p:0},
{id:429,name:"Nike Run Club",url:"nrc.nike.com",desc:"Free running app with guided runs from coaches.",r:4.6,cat:"Health & Fitness",p:0},
{id:430,name:"Garmin Connect",url:"connect.garmin.com",desc:"Track and analyze your sports activities.",r:4.5,cat:"Health & Fitness",p:0},
{id:431,name:"Polar Flow",url:"flow.polar.com",desc:"Training platform for Polar sports watches.",r:4.4,cat:"Health & Fitness",p:0},
{id:432,name:"Whoop",url:"app.whoop.com",desc:"Wearable fitness tracker focused on recovery.",r:4.5,cat:"Health & Fitness",p:0},
{id:433,name:"Sleep Cycle",url:"sleepcycle.com",desc:"Smart alarm clock that tracks your sleep patterns.",r:4.5,cat:"Health & Fitness",p:0},
{id:434,name:"Oura Ring",url:"cloud.ouraring.com",desc:"Sleep and health tracking with Oura smart ring.",r:4.6,cat:"Health & Fitness",p:0},
{id:435,name:"Fitbit",url:"fitbit.com/dashboard",desc:"Activity and health tracking by Google.",r:4.3,cat:"Health & Fitness",p:0},
{id:436,name:"Teladoc",url:"teladoc.com",desc:"Virtual healthcare and online doctor visits.",r:4.2,cat:"Health & Fitness",p:0},
{id:437,name:"Zocdoc",url:"zocdoc.com",desc:"Book in-person and virtual doctor appointments.",r:4.5,cat:"Health & Fitness",p:0},
{id:438,name:"GoodRx",url:"goodrx.com",desc:"Find lowest prescription drug prices near you.",r:4.5,cat:"Health & Fitness",p:0},
{id:439,name:"Healthline",url:"healthline.com",desc:"Trusted health information and medical advice.",r:4.5,cat:"Health & Fitness",p:0},
{id:440,name:"WebMD",url:"webmd.com",desc:"Health information, symptoms, and doctor finder.",r:4.3,cat:"Health & Fitness",p:0},
{id:441,name:"Clue",url:"helloclue.com",desc:"Period and cycle tracking app for women.",r:4.6,cat:"Health & Fitness",p:0},
{id:442,name:"Flo",url:"flo.health",desc:"Period tracker and women's health app.",r:4.5,cat:"Health & Fitness",p:0},
{id:443,name:"8fit",url:"8fit.com",desc:"Personalized workout and meal plan app.",r:4.3,cat:"Health & Fitness",p:0},
{id:444,name:"Freeletics",url:"freeletics.com",desc:"AI personal trainer for bodyweight training.",r:4.4,cat:"Health & Fitness",p:0},
{id:445,name:"Peloton",url:"onepeloton.com",desc:"Live and on-demand cycling and fitness classes.",r:4.5,cat:"Health & Fitness",p:0},
{id:446,name:"Zwift",url:"zwift.com",desc:"Virtual cycling and running training platform.",r:4.5,cat:"Health & Fitness",p:0},
// Law & Legal
{id:447,name:"Westlaw",url:"westlaw.com",desc:"Comprehensive legal research platform by Thomson.",r:4.5,cat:"Law & Legal",p:0},
{id:448,name:"LexisNexis",url:"lexisnexis.com",desc:"Legal research and business intelligence data.",r:4.4,cat:"Law & Legal",p:0},
{id:449,name:"CourtListener",url:"courtlistener.com",desc:"Free legal research with millions of opinions.",r:4.5,cat:"Law & Legal",p:0},
{id:450,name:"Casetext",url:"casetext.com",desc:"AI-powered legal research and document drafting.",r:4.5,cat:"Law & Legal",p:0},
{id:451,name:"Fastcase",url:"fastcase.com",desc:"Legal research software with visualizations.",r:4.3,cat:"Law & Legal",p:0},
{id:452,name:"Justia",url:"justia.com",desc:"Free US law, cases, codes, and legal information.",r:4.5,cat:"Law & Legal",p:0},
{id:453,name:"Oyez",url:"oyez.org",desc:"Supreme Court multimedia database and oral args.",r:4.6,cat:"Law & Legal",p:0},
{id:454,name:"FindLaw",url:"findlaw.com",desc:"Free legal information and attorney finder.",r:4.3,cat:"Law & Legal",p:0},
{id:455,name:"Nolo",url:"nolo.com",desc:"DIY legal guides and attorney directory.",r:4.3,cat:"Law & Legal",p:0},
{id:456,name:"DocuSign",url:"docusign.com",desc:"eSignature and agreement cloud platform.",r:4.6,cat:"Law & Legal",p:0},
{id:457,name:"HelloSign",url:"hellosign.com",desc:"Simple eSignature and document workflow tool.",r:4.5,cat:"Law & Legal",p:0},
{id:458,name:"PandaDoc",url:"pandadoc.com",desc:"Document automation with eSignature and payments.",r:4.5,cat:"Law & Legal",p:0},
{id:459,name:"Ironclad",url:"ironclad.com",desc:"Digital contracting platform for legal teams.",r:4.4,cat:"Law & Legal",p:0},
{id:460,name:"Contractbook",url:"contractbook.com",desc:"Contract lifecycle management for modern teams.",r:4.4,cat:"Law & Legal",p:0},
{id:461,name:"UpCounsel",url:"upcounsel.com",desc:"On-demand legal services from top attorneys.",r:4.2,cat:"Law & Legal",p:0},
{id:462,name:"Rocket Lawyer",url:"rocketlawyer.com",desc:"Affordable legal documents and attorney access.",r:4.2,cat:"Law & Legal",p:0},
{id:463,name:"LegalZoom",url:"legalzoom.com",desc:"Online legal services for business and personal.",r:4.1,cat:"Law & Legal",p:0},
{id:464,name:"Clerky",url:"clerky.com",desc:"Legal paperwork for startups raising funding.",r:4.4,cat:"Law & Legal",p:0},
{id:465,name:"Formaliti",url:"formaliti.com",desc:"Company formation and legal compliance tool.",r:4.1,cat:"Law & Legal",p:0},
// Finance & Crypto
{id:466,name:"PayPal",url:"paypal.com",desc:"Send money and shop securely online.",r:4.2,cat:"Finance & Crypto",p:0},
{id:467,name:"Wise",url:"wise.com",desc:"International money transfers at low fees.",r:4.7,cat:"Finance & Crypto",p:0},
{id:468,name:"Revolut",url:"revolut.com",desc:"Digital banking and financial super-app.",r:4.5,cat:"Finance & Crypto",p:0},
{id:469,name:"N26",url:"n26.com",desc:"Mobile bank account with no hidden fees.",r:4.3,cat:"Finance & Crypto",p:0},
{id:470,name:"Monzo",url:"monzo.com",desc:"Smart bank account with instant notifications.",r:4.5,cat:"Finance & Crypto",p:0},
{id:471,name:"Robinhood",url:"robinhood.com",desc:"Commission-free stocks and crypto investing.",r:4.1,cat:"Finance & Crypto",p:0},
{id:472,name:"Webull",url:"webull.com",desc:"Advanced trading platform for investors.",r:4.3,cat:"Finance & Crypto",p:0},
{id:473,name:"eToro",url:"etoro.com",desc:"Social trading and multi-asset investment platform.",r:4.2,cat:"Finance & Crypto",p:0},
{id:474,name:"Interactive Brokers",url:"interactivebrokers.com",desc:"Professional trading for active investors.",r:4.4,cat:"Finance & Crypto",p:0},
{id:475,name:"CoinGecko",url:"coingecko.com",desc:"Crypto market data, prices, and charts.",r:4.6,cat:"Finance & Crypto",p:0},
{id:476,name:"CoinMarketCap",url:"coinmarketcap.com",desc:"Cryptocurrency prices, charts, and market cap.",r:4.5,cat:"Finance & Crypto",p:0},
{id:477,name:"Messari",url:"messari.io",desc:"Crypto research, data, and analytics platform.",r:4.5,cat:"Finance & Crypto",p:0},
{id:478,name:"Glassnode",url:"studio.glassnode.com",desc:"On-chain metrics and blockchain intelligence.",r:4.5,cat:"Finance & Crypto",p:0},
{id:479,name:"MetaMask",url:"metamask.io",desc:"Crypto wallet and gateway to blockchain apps.",r:4.4,cat:"Finance & Crypto",p:0},
{id:480,name:"Phantom",url:"phantom.app",desc:"Crypto wallet for Solana and multi-chain.",r:4.5,cat:"Finance & Crypto",p:0},
{id:481,name:"Exodus",url:"exodus.com",desc:"Beautiful multi-asset crypto wallet.",r:4.4,cat:"Finance & Crypto",p:0},
{id:482,name:"QuickBooks",url:"quickbooks.intuit.com",desc:"Accounting software for small businesses.",r:4.4,cat:"Finance & Crypto",p:0},
{id:483,name:"FreshBooks",url:"freshbooks.com",desc:"Easy invoicing and accounting for freelancers.",r:4.4,cat:"Finance & Crypto",p:0},
{id:484,name:"Wave",url:"waveapps.com",desc:"Free accounting software for small businesses.",r:4.4,cat:"Finance & Crypto",p:0},
{id:485,name:"Xero",url:"xero.com",desc:"Cloud accounting software for businesses.",r:4.5,cat:"Finance & Crypto",p:0},
{id:486,name:"Mint",url:"mint.intuit.com",desc:"Free budgeting and personal finance tracker.",r:4.1,cat:"Finance & Crypto",p:0},
{id:487,name:"YNAB",url:"app.youneedabudget.com",desc:"Zero-based budgeting app to manage money.",r:4.6,cat:"Finance & Crypto",p:0},
{id:488,name:"Mercury",url:"mercury.com",desc:"Banking for startups with powerful features.",r:4.6,cat:"Finance & Crypto",p:0},
{id:489,name:"Brex",url:"brex.com",desc:"Corporate cards and finance for startups.",r:4.4,cat:"Finance & Crypto",p:0},
{id:490,name:"Ramp",url:"ramp.com",desc:"Corporate card and expense management platform.",r:4.5,cat:"Finance & Crypto",p:0},
{id:491,name:"Expensify",url:"expensify.com",desc:"Expense reporting made easy for teams.",r:4.2,cat:"Finance & Crypto",p:0},
{id:492,name:"Plaid",url:"plaid.com",desc:"Connect bank accounts to financial apps via API.",r:4.4,cat:"Finance & Crypto",p:0},
{id:493,name:"Carta",url:"carta.com",desc:"Equity management platform for startups.",r:4.4,cat:"Finance & Crypto",p:0},
{id:494,name:"AngelList",url:"angel.co",desc:"Startup fundraising and equity management.",r:4.4,cat:"Finance & Crypto",p:0},
{id:495,name:"Crunchbase",url:"crunchbase.com",desc:"Business information on companies and investments.",r:4.5,cat:"Finance & Crypto",p:0},
{id:496,name:"Bloomberg",url:"bloomberg.com",desc:"Global business and financial news and data.",r:4.6,cat:"Finance & Crypto",p:0},
{id:497,name:"Yahoo Finance",url:"finance.yahoo.com",desc:"Stock quotes, financial news and portfolio tools.",r:4.4,cat:"Finance & Crypto",p:0},
{id:498,name:"Morningstar",url:"morningstar.com",desc:"Investment research, ratings, and fund data.",r:4.5,cat:"Finance & Crypto",p:0},
{id:499,name:"Seeking Alpha",url:"seekingalpha.com",desc:"Stock market analysis and investment news.",r:4.3,cat:"Finance & Crypto",p:0},
{id:500,name:"Bankrate",url:"bankrate.com",desc:"Compare rates for banking and financial products.",r:4.3,cat:"Finance & Crypto",p:0},
// Education & Learning
{id:501,name:"Udemy",url:"udemy.com",desc:"Online courses on virtually every topic.",r:4.5,cat:"Education & Learning",p:0},
{id:502,name:"edX",url:"edx.org",desc:"Online courses from top universities worldwide.",r:4.5,cat:"Education & Learning",p:0},
{id:503,name:"Skillshare",url:"skillshare.com",desc:"Creative classes for curious people online.",r:4.4,cat:"Education & Learning",p:0},
{id:504,name:"LinkedIn Learning",url:"linkedin.com/learning",desc:"Professional skills courses from LinkedIn.",r:4.3,cat:"Education & Learning",p:0},
{id:505,name:"Pluralsight",url:"pluralsight.com",desc:"Tech skill development platform for teams.",r:4.4,cat:"Education & Learning",p:0},
{id:506,name:"Khan Academy",url:"khanacademy.org",desc:"Free world-class education for anyone anywhere.",r:4.8,cat:"Education & Learning",p:0},
{id:507,name:"The Odin Project",url:"theodinproject.com",desc:"Free full-stack web development curriculum.",r:4.8,cat:"Education & Learning",p:0},
{id:508,name:"Duolingo",url:"duolingo.com",desc:"Free fun language learning app with gamification.",r:4.6,cat:"Education & Learning",p:0},
{id:509,name:"Babbel",url:"babbel.com",desc:"Learn a language with real-world conversations.",r:4.4,cat:"Education & Learning",p:0},
{id:510,name:"Rosetta Stone",url:"rosettastone.com",desc:"Language learning with immersive technology.",r:4.2,cat:"Education & Learning",p:0},
{id:511,name:"Brilliant",url:"brilliant.org",desc:"Learn math and science with guided problem solving.",r:4.7,cat:"Education & Learning",p:0},
{id:512,name:"Quizlet",url:"quizlet.com",desc:"Flashcards and study tools for learning anything.",r:4.5,cat:"Education & Learning",p:0},
{id:513,name:"Anki Web",url:"ankiweb.net",desc:"Powerful spaced repetition flashcard system.",r:4.7,cat:"Education & Learning",p:0},
{id:514,name:"Brainscape",url:"brainscape.com",desc:"Smart flashcards for faster and better learning.",r:4.3,cat:"Education & Learning",p:0},
{id:515,name:"MIT OpenCourseWare",url:"ocw.mit.edu",desc:"Free MIT course materials available online.",r:4.8,cat:"Education & Learning",p:0},
{id:516,name:"Stanford Online",url:"online.stanford.edu",desc:"Online courses and degrees from Stanford.",r:4.7,cat:"Education & Learning",p:0},
{id:517,name:"Harvard Online",url:"online.harvard.edu",desc:"Free and paid courses from Harvard faculty.",r:4.7,cat:"Education & Learning",p:0},
{id:518,name:"Codecademy",url:"codecademy.com",desc:"Learn to code interactively for free.",r:4.5,cat:"Education & Learning",p:0},
{id:519,name:"LeetCode",url:"leetcode.com",desc:"Coding challenges for interview preparation.",r:4.6,cat:"Education & Learning",p:0},
{id:520,name:"HackerRank",url:"hackerrank.com",desc:"Coding challenges and technical interview prep.",r:4.5,cat:"Education & Learning",p:0},
{id:521,name:"Codewars",url:"codewars.com",desc:"Train with coding challenges called kata.",r:4.6,cat:"Education & Learning",p:0},
{id:522,name:"Exercism",url:"exercism.org",desc:"Free coding practice with mentor feedback.",r:4.7,cat:"Education & Learning",p:0},
{id:523,name:"DataCamp",url:"datacamp.com",desc:"Learn data science and analytics online.",r:4.4,cat:"Education & Learning",p:0},
{id:524,name:"Fast.ai",url:"fast.ai",desc:"Practical deep learning for coders course.",r:4.8,cat:"Education & Learning",p:0},
{id:525,name:"DeepLearning.ai",url:"deeplearning.ai",desc:"AI education by Andrew Ng for developers.",r:4.7,cat:"Education & Learning",p:0},
{id:526,name:"Kaggle Learn",url:"kaggle.com/learn",desc:"Free micro-courses for data science skills.",r:4.6,cat:"Education & Learning",p:0},
{id:527,name:"Udacity",url:"udacity.com",desc:"Nanodegrees in tech skills with career services.",r:4.3,cat:"Education & Learning",p:0},
{id:528,name:"Frontend Masters",url:"frontendmasters.com",desc:"Expert-led courses for front-end developers.",r:4.7,cat:"Education & Learning",p:0},
{id:529,name:"Egghead",url:"egghead.io",desc:"Bite-sized developer screencasts for web devs.",r:4.6,cat:"Education & Learning",p:0},
{id:530,name:"Scrimba",url:"scrimba.com",desc:"Interactive coding screencasts for learners.",r:4.6,cat:"Education & Learning",p:0},
{id:531,name:"Chegg",url:"chegg.com",desc:"Homework help and textbook solutions.",r:4.0,cat:"Education & Learning",p:0},
{id:532,name:"Photomath",url:"photomath.com",desc:"Solve math by taking a photo of the problem.",r:4.5,cat:"Education & Learning",p:0},
{id:533,name:"Wolfram MathWorld",url:"mathworld.wolfram.com",desc:"The web's most extensive mathematics resource.",r:4.7,cat:"Education & Learning",p:0},
{id:534,name:"Crash Course",url:"thecrashcourse.com",desc:"Free educational video series on many subjects.",r:4.7,cat:"Education & Learning",p:0},
{id:535,name:"TED",url:"ted.com",desc:"Ideas worth spreading through short powerful talks.",r:4.7,cat:"Education & Learning",p:0},
// Gaming
{id:536,name:"Steam",url:"store.steampowered.com",desc:"Largest PC gaming platform and storefront.",r:4.7,cat:"Gaming",p:0},
{id:537,name:"Epic Games Store",url:"store.epicgames.com",desc:"PC game store with regular free game giveaways.",r:4.3,cat:"Gaming",p:0},
{id:538,name:"itch.io",url:"itch.io",desc:"Indie game marketplace for developers and players.",r:4.7,cat:"Gaming",p:0},
{id:539,name:"GOG",url:"gog.com",desc:"DRM-free games for PC and Mac.",r:4.6,cat:"Gaming",p:0},
{id:540,name:"Xbox Play",url:"xbox.com/en-US/play",desc:"Stream Xbox games in your browser.",r:4.3,cat:"Gaming",p:0},
{id:541,name:"PlayStation",url:"playstation.com",desc:"Sony PlayStation gaming platform and store.",r:4.5,cat:"Gaming",p:0},
{id:542,name:"Nintendo",url:"nintendo.com",desc:"Nintendo Switch games and entertainment.",r:4.6,cat:"Gaming",p:0},
{id:543,name:"EA App",url:"ea.com",desc:"Electronic Arts games platform and storefront.",r:4.0,cat:"Gaming",p:0},
{id:544,name:"Ubisoft Connect",url:"ubisoft.com",desc:"Ubisoft ecosystem for games and rewards.",r:4.0,cat:"Gaming",p:0},
{id:545,name:"Battle.net",url:"battle.net",desc:"Blizzard's game launcher for WoW, Overwatch etc.",r:4.4,cat:"Gaming",p:0},
{id:546,name:"GeForce NOW",url:"nvidia.com/en-us/geforce-now",desc:"Stream PC games from NVIDIA's cloud servers.",r:4.4,cat:"Gaming",p:0},
{id:547,name:"Boosteroid",url:"boosteroid.com",desc:"Cloud gaming service for PC games streaming.",r:4.1,cat:"Gaming",p:0},
{id:548,name:"YouTube Gaming",url:"gaming.youtube.com",desc:"Watch and stream gaming content on YouTube.",r:4.3,cat:"Gaming",p:0},
{id:549,name:"Facebook Gaming",url:"fb.gg",desc:"Watch live game streams on Facebook.",r:3.8,cat:"Gaming",p:0},
{id:550,name:"Speedrun.com",url:"speedrun.com",desc:"Leaderboards for speedrunning video games.",r:4.6,cat:"Gaming",p:0},
{id:551,name:"HowLongToBeat",url:"howlongtobeat.com",desc:"Find out how long it takes to beat any game.",r:4.7,cat:"Gaming",p:0},
{id:552,name:"IsThereAnyDeal",url:"isthereanydeal.com",desc:"Compare game prices and track deals.",r:4.6,cat:"Gaming",p:0},
{id:553,name:"Humble Bundle",url:"humblebundle.com",desc:"Game bundles supporting charity causes.",r:4.6,cat:"Gaming",p:0},
{id:554,name:"Fanatical",url:"fanatical.com",desc:"PC game deals, bundles, and sales.",r:4.3,cat:"Gaming",p:0},
{id:555,name:"RAWG",url:"rawg.io",desc:"Largest video game database and discovery engine.",r:4.4,cat:"Gaming",p:0},
{id:556,name:"OpenCritic",url:"opencritic.com",desc:"Aggregated game reviews from top critics.",r:4.5,cat:"Gaming",p:0},
{id:557,name:"Metacritic",url:"metacritic.com",desc:"Game, movie, and TV reviews aggregated.",r:4.3,cat:"Gaming",p:0},
{id:558,name:"Backloggd",url:"backloggd.com",desc:"Track your video game backlog and reviews.",r:4.5,cat:"Gaming",p:0},
{id:559,name:"GG.deals",url:"gg.deals",desc:"Game price comparison and historical tracker.",r:4.6,cat:"Gaming",p:0},
// News & Media
{id:560,name:"Google News",url:"news.google.com",desc:"Personalized news aggregator by Google.",r:4.4,cat:"News & Media",p:0},
{id:561,name:"Feedly",url:"feedly.com",desc:"RSS reader and content aggregator for teams.",r:4.5,cat:"News & Media",p:0},
{id:562,name:"Flipboard",url:"flipboard.com",desc:"Social magazine for personalized news.",r:4.2,cat:"News & Media",p:0},
{id:563,name:"BBC News",url:"bbc.com/news",desc:"International news from BBC journalists worldwide.",r:4.5,cat:"News & Media",p:0},
{id:564,name:"CNN",url:"cnn.com",desc:"Breaking news, latest news, and videos from CNN.",r:4.1,cat:"News & Media",p:0},
{id:565,name:"Reuters",url:"reuters.com",desc:"International news agency and media company.",r:4.6,cat:"News & Media",p:0},
{id:566,name:"Associated Press",url:"apnews.com",desc:"Trusted global news and fact-checking source.",r:4.6,cat:"News & Media",p:0},
{id:567,name:"The Guardian",url:"theguardian.com",desc:"Independent news from the UK and worldwide.",r:4.5,cat:"News & Media",p:0},
{id:568,name:"TechCrunch",url:"techcrunch.com",desc:"Technology news, startups, and venture capital.",r:4.5,cat:"News & Media",p:0},
{id:569,name:"The Verge",url:"theverge.com",desc:"Tech, science, culture, and entertainment news.",r:4.5,cat:"News & Media",p:0},
{id:570,name:"Wired",url:"wired.com",desc:"How technology changes everything around us.",r:4.5,cat:"News & Media",p:0},
{id:571,name:"Ars Technica",url:"arstechnica.com",desc:"Technology news and analysis for geeks.",r:4.6,cat:"News & Media",p:0},
{id:572,name:"Engadget",url:"engadget.com",desc:"Consumer electronics and technology news.",r:4.3,cat:"News & Media",p:0},
{id:573,name:"VentureBeat",url:"venturebeat.com",desc:"Tech news and events for enterprise and AI.",r:4.3,cat:"News & Media",p:0},
{id:574,name:"Morning Brew",url:"morningbrew.com",desc:"Daily business newsletter for modern professionals.",r:4.6,cat:"News & Media",p:0},
{id:575,name:"TLDR Newsletter",url:"tldr.tech",desc:"Daily newsletter for developers and tech workers.",r:4.7,cat:"News & Media",p:0},
{id:576,name:"Axios",url:"axios.com",desc:"Smart brevity news and trusted journalism.",r:4.5,cat:"News & Media",p:0},
{id:577,name:"Stratechery",url:"stratechery.com",desc:"Tech and business strategy analysis newsletter.",r:4.7,cat:"News & Media",p:0},
{id:578,name:"AllSides",url:"allsides.com",desc:"See news across left, center, and right perspectives.",r:4.4,cat:"News & Media",p:0},
{id:579,name:"Ground News",url:"ground.news",desc:"Compare news coverage across different outlets.",r:4.5,cat:"News & Media",p:0},
{id:580,name:"Newsela",url:"newsela.com",desc:"News content adapted for classroom learning.",r:4.3,cat:"News & Media",p:0},
// Travel & Maps
{id:581,name:"Google Maps",url:"maps.google.com",desc:"Navigation, local search, and street view maps.",r:4.8,cat:"Travel & Maps",p:0},
{id:582,name:"Waze",url:"waze.com",desc:"Community-based GPS traffic and navigation.",r:4.6,cat:"Travel & Maps",p:0},
{id:583,name:"OpenStreetMap",url:"openstreetmap.org",desc:"Free editable map of the whole world.",r:4.6,cat:"Travel & Maps",p:0},
{id:584,name:"HERE Maps",url:"here.com",desc:"Mapping and location platform for businesses.",r:4.3,cat:"Travel & Maps",p:0},
{id:585,name:"Airbnb",url:"airbnb.com",desc:"Book unique homes and experiences worldwide.",r:4.5,cat:"Travel & Maps",p:0},
{id:586,name:"Booking.com",url:"booking.com",desc:"Hotels, apartments, and vacation rentals.",r:4.5,cat:"Travel & Maps",p:0},
{id:587,name:"Hotels.com",url:"hotels.com",desc:"Book hotels with rewards and best price guarantee.",r:4.3,cat:"Travel & Maps",p:0},
{id:588,name:"Expedia",url:"expedia.com",desc:"Book flights, hotels, and travel packages.",r:4.2,cat:"Travel & Maps",p:0},
{id:589,name:"Agoda",url:"agoda.com",desc:"Hotels and vacation rentals across Asia.",r:4.3,cat:"Travel & Maps",p:0},
{id:590,name:"Skyscanner",url:"skyscanner.com",desc:"Compare flights, hotels, and car rentals.",r:4.5,cat:"Travel & Maps",p:0},
{id:591,name:"Google Flights",url:"flights.google.com",desc:"Search and compare flight prices from Google.",r:4.7,cat:"Travel & Maps",p:0},
{id:592,name:"Kayak",url:"kayak.com",desc:"Search hundreds of travel sites at once.",r:4.3,cat:"Travel & Maps",p:0},
{id:593,name:"Hopper",url:"hopper.com",desc:"AI-powered app to predict and track flight prices.",r:4.4,cat:"Travel & Maps",p:0},
{id:594,name:"TripAdvisor",url:"tripadvisor.com",desc:"Travel reviews, booking, and destination guides.",r:4.3,cat:"Travel & Maps",p:0},
{id:595,name:"Yelp",url:"yelp.com",desc:"Find and review local businesses and restaurants.",r:4.2,cat:"Travel & Maps",p:0},
{id:596,name:"Atlas Obscura",url:"atlasobscura.com",desc:"Discover the world's hidden wonders and places.",r:4.7,cat:"Travel & Maps",p:0},
{id:597,name:"Culture Trip",url:"theculturetrip.com",desc:"Travel inspiration and unique local experiences.",r:4.2,cat:"Travel & Maps",p:0},
{id:598,name:"Uber",url:"uber.com",desc:"Request rides, food delivery, and more.",r:4.3,cat:"Travel & Maps",p:0},
{id:599,name:"Lyft",url:"lyft.com",desc:"Ridesharing and bike rentals across the US.",r:4.2,cat:"Travel & Maps",p:0},
{id:600,name:"Grab",url:"grab.com",desc:"Southeast Asia's leading super-app.",r:4.3,cat:"Travel & Maps",p:0},
{id:601,name:"Bolt",url:"bolt.eu",desc:"Affordable rides and scooters across Europe.",r:4.2,cat:"Travel & Maps",p:0},
{id:602,name:"Rome2rio",url:"rome2rio.com",desc:"Discover how to get anywhere by any transport.",r:4.5,cat:"Travel & Maps",p:0},
{id:603,name:"Hostelworld",url:"hostelworld.com",desc:"Book hostels and budget accommodation worldwide.",r:4.3,cat:"Travel & Maps",p:0},
{id:604,name:"Viator",url:"viator.com",desc:"Book tours, activities, and experiences globally.",r:4.4,cat:"Travel & Maps",p:0},
{id:605,name:"GetYourGuide",url:"getyourguide.com",desc:"Book tours and experiences around the world.",r:4.4,cat:"Travel & Maps",p:0},
// E-commerce
{id:606,name:"WooCommerce",url:"woocommerce.com",desc:"Customizable open-source eCommerce for WordPress.",r:4.4,cat:"E-commerce",p:0},
{id:607,name:"BigCommerce",url:"bigcommerce.com",desc:"Enterprise eCommerce platform for growing brands.",r:4.3,cat:"E-commerce",p:0},
{id:608,name:"Squarespace",url:"squarespace.com",desc:"Beautiful website builder with integrated commerce.",r:4.4,cat:"E-commerce",p:0},
{id:609,name:"Wix Stores",url:"wix.com",desc:"Create and manage an online store with Wix.",r:4.2,cat:"E-commerce",p:0},
{id:610,name:"Amazon Seller",url:"sellercentral.amazon.com",desc:"Sell products to millions on Amazon marketplace.",r:4.3,cat:"E-commerce",p:0},
{id:611,name:"Etsy Sell",url:"etsy.com/sell",desc:"Sell handmade and vintage goods on Etsy.",r:4.5,cat:"E-commerce",p:0},
{id:612,name:"eBay Seller",url:"ebay.com/sell",desc:"Sell new and used items on eBay's marketplace.",r:4.2,cat:"E-commerce",p:0},
{id:613,name:"Poshmark",url:"poshmark.com",desc:"Buy and sell fashion in a social marketplace.",r:4.3,cat:"E-commerce",p:0},
{id:614,name:"Depop",url:"depop.com",desc:"Fashion marketplace for unique second-hand items.",r:4.2,cat:"E-commerce",p:0},
{id:615,name:"Vinted",url:"vinted.com",desc:"Buy and sell pre-owned clothing online.",r:4.3,cat:"E-commerce",p:0},
{id:616,name:"Gumroad",url:"gumroad.com",desc:"Sell digital products directly to your audience.",r:4.5,cat:"E-commerce",p:0},
{id:617,name:"Ko-fi",url:"ko-fi.com",desc:"Accept donations and sell to your supporters.",r:4.6,cat:"E-commerce",p:0},
{id:618,name:"Buy Me a Coffee",url:"buymeacoffee.com",desc:"Simple way to accept support from your fans.",r:4.5,cat:"E-commerce",p:0},
{id:619,name:"Patreon",url:"patreon.com",desc:"Membership platform for creators and fans.",r:4.4,cat:"E-commerce",p:0},
{id:620,name:"Paddle",url:"vendors.paddle.com",desc:"Revenue delivery platform for SaaS companies.",r:4.4,cat:"E-commerce",p:0},
{id:621,name:"Lemon Squeezy",url:"app.lemonsqueezy.com",desc:"Payments, subscriptions, and licensing for SaaS.",r:4.6,cat:"E-commerce",p:0},
{id:622,name:"Printful",url:"printful.com",desc:"Print-on-demand dropshipping for your store.",r:4.5,cat:"E-commerce",p:0},
{id:623,name:"Printify",url:"printify.com",desc:"Print-on-demand network for e-commerce sellers.",r:4.4,cat:"E-commerce",p:0},
{id:624,name:"Gelato",url:"gelato.com",desc:"Global print-on-demand production and delivery.",r:4.4,cat:"E-commerce",p:0},
{id:625,name:"ShipStation",url:"shipstation.com",desc:"Multi-channel shipping and order management.",r:4.4,cat:"E-commerce",p:0},
{id:626,name:"Shippo",url:"goshippo.com",desc:"Multi-carrier shipping API and dashboard.",r:4.4,cat:"E-commerce",p:0},
{id:627,name:"AfterShip",url:"aftership.com",desc:"Shipment tracking and returns management platform.",r:4.3,cat:"E-commerce",p:0},
{id:628,name:"Narvar",url:"narvar.com",desc:"Post-purchase customer experience platform.",r:4.2,cat:"E-commerce",p:0},
{id:629,name:"Klaviyo",url:"klaviyo.com",desc:"Email and SMS marketing platform for e-commerce.",r:4.5,cat:"E-commerce",p:0},
{id:630,name:"Omnisend",url:"omnisend.com",desc:"Marketing automation for e-commerce businesses.",r:4.5,cat:"E-commerce",p:0},
// Food & Delivery
{id:631,name:"DoorDash",url:"doordash.com",desc:"Food delivery from local restaurants near you.",r:4.2,cat:"Food & Delivery",p:0},
{id:632,name:"Uber Eats",url:"ubereats.com",desc:"Order food delivery from restaurants nearby.",r:4.2,cat:"Food & Delivery",p:0},
{id:633,name:"Grubhub",url:"grubhub.com",desc:"Food delivery and takeout from local places.",r:4.0,cat:"Food & Delivery",p:0},
{id:634,name:"Instacart",url:"instacart.com",desc:"Same-day grocery delivery from local stores.",r:4.2,cat:"Food & Delivery",p:0},
{id:635,name:"Zomato",url:"zomato.com",desc:"Restaurant discovery and food delivery app.",r:4.3,cat:"Food & Delivery",p:0},
{id:636,name:"Swiggy",url:"swiggy.com",desc:"Food delivery, grocery, and more across India.",r:4.3,cat:"Food & Delivery",p:0},
{id:637,name:"Deliveroo",url:"deliveroo.com",desc:"Restaurant food delivery across Europe.",r:4.1,cat:"Food & Delivery",p:0},
{id:638,name:"Wolt",url:"wolt.com",desc:"Food delivery with great restaurant selection.",r:4.4,cat:"Food & Delivery",p:0},
{id:639,name:"OpenTable",url:"opentable.com",desc:"Restaurant reservations at thousands of places.",r:4.4,cat:"Food & Delivery",p:0},
{id:640,name:"Resy",url:"resy.com",desc:"Book tables at America's best restaurants.",r:4.4,cat:"Food & Delivery",p:0},
{id:641,name:"Allrecipes",url:"allrecipes.com",desc:"Largest community of home cooks worldwide.",r:4.5,cat:"Food & Delivery",p:0},
{id:642,name:"Food Network",url:"foodnetwork.com",desc:"Recipes, shows, and food content from TV.",r:4.3,cat:"Food & Delivery",p:0},
{id:643,name:"Tasty",url:"tasty.co",desc:"BuzzFeed's video recipe and food content platform.",r:4.4,cat:"Food & Delivery",p:0},
{id:644,name:"Yummly",url:"yummly.com",desc:"Personalized recipe recommendations for cooks.",r:4.3,cat:"Food & Delivery",p:0},
{id:645,name:"Whisk",url:"whisk.com",desc:"Recipe management and meal planning tool.",r:4.3,cat:"Food & Delivery",p:0},
{id:646,name:"HelloFresh",url:"hellofresh.com",desc:"Meal kit delivery with pre-portioned ingredients.",r:4.2,cat:"Food & Delivery",p:0},
{id:647,name:"Blue Apron",url:"blueapron.com",desc:"Chef-designed meal kits delivered to your door.",r:4.0,cat:"Food & Delivery",p:0},
{id:648,name:"Goldbelly",url:"goldbelly.com",desc:"Ship iconic foods from restaurants nationwide.",r:4.4,cat:"Food & Delivery",p:0},
];
