window.APPS_1 = [
{id:1,name:"ChatGPT",url:"chat.openai.com",desc:"The world's most popular AI chatbot.",r:4.9,cat:"AI Tools",p:1},
{id:2,name:"Claude",url:"claude.ai/chat",desc:"Anthropic's helpful and harmless AI assistant.",r:4.9,cat:"AI Tools",p:1},
{id:3,name:"Gemini",url:"gemini.google.com/app",desc:"Google's multimodal AI assistant.",r:4.8,cat:"AI Tools",p:1},
{id:4,name:"DeepSeek",url:"chat.deepseek.com",desc:"Powerful open-source AI reasoning model.",r:4.8,cat:"AI Tools",p:1},
{id:5,name:"Grok",url:"grok.com",desc:"xAI's witty and real-time AI assistant.",r:4.7,cat:"AI Tools",p:1},
{id:6,name:"Perplexity",url:"perplexity.ai",desc:"AI-powered answer engine with citations.",r:4.8,cat:"AI Tools",p:1},
{id:7,name:"Microsoft Copilot",url:"copilot.microsoft.com",desc:"Microsoft's AI assistant powered by GPT-4.",r:4.6,cat:"AI Tools",p:1},
{id:8,name:"Poe",url:"poe.com",desc:"Chat with multiple AI models in one place.",r:4.6,cat:"AI Tools",p:1},
{id:9,name:"GitHub",url:"github.com/dashboard",desc:"World's leading platform for code hosting.",r:4.9,cat:"Developers",p:1},
{id:10,name:"Vercel",url:"vercel.com/dashboard",desc:"Deploy frontend apps with zero configuration.",r:4.9,cat:"Developers",p:1},
{id:11,name:"Cursor",url:"cursor.sh",desc:"AI-first code editor built on VS Code.",r:4.9,cat:"Developers",p:1},
{id:12,name:"Supabase",url:"app.supabase.com",desc:"Open source Firebase alternative with Postgres.",r:4.9,cat:"Developers",p:1},
{id:13,name:"VS Code Web",url:"vscode.dev",desc:"Run Visual Studio Code in your browser.",r:4.9,cat:"Developers",p:1},
{id:14,name:"Linear",url:"linear.app",desc:"Fast, beautiful issue tracker for dev teams.",r:4.9,cat:"Developers",p:1},
{id:15,name:"Stack Overflow",url:"stackoverflow.com",desc:"Q&A community for programmers worldwide.",r:4.8,cat:"Developers",p:1},
{id:16,name:"Cloudflare",url:"dash.cloudflare.com",desc:"Manage DNS, CDN, and security for your sites.",r:4.8,cat:"Developers",p:1},
{id:17,name:"Replit",url:"replit.com",desc:"Browser-based IDE for coding and deploying.",r:4.6,cat:"Developers",p:1},
{id:18,name:"Railway",url:"railway.app/dashboard",desc:"Instant deployments with automatic scaling.",r:4.8,cat:"Developers",p:1},
{id:19,name:"Netlify",url:"app.netlify.com",desc:"Deploy and host modern web projects easily.",r:4.7,cat:"Developers",p:1},
{id:20,name:"Docker Hub",url:"hub.docker.com",desc:"Find and share container images globally.",r:4.6,cat:"Developers",p:1},
{id:21,name:"Postman",url:"web.postman.co",desc:"API development and testing platform.",r:4.7,cat:"Developers",p:1},
{id:22,name:"Figma",url:"figma.com",desc:"Collaborative UI and product design tool.",r:4.9,cat:"Design",p:1},
{id:23,name:"Framer",url:"framer.com",desc:"Design and publish interactive websites fast.",r:4.8,cat:"Design",p:1},
{id:24,name:"Canva",url:"canva.com",desc:"Easy graphic design for everyone online.",r:4.7,cat:"Design",p:1},
{id:25,name:"Miro",url:"miro.com",desc:"Online collaborative whiteboard for teams.",r:4.7,cat:"Design",p:1},
{id:26,name:"Dribbble",url:"dribbble.com",desc:"Showcase and discover creative design work.",r:4.7,cat:"Design",p:1},
{id:27,name:"Behance",url:"behance.net",desc:"Adobe's platform to showcase creative portfolios.",r:4.6,cat:"Design",p:1},
{id:28,name:"Notion",url:"notion.so/login",desc:"All-in-one workspace for notes and projects.",r:4.8,cat:"Productivity",p:1},
{id:29,name:"Obsidian",url:"obsidian.md",desc:"Local-first knowledge base with linked notes.",r:4.9,cat:"Productivity",p:1},
{id:30,name:"ClickUp",url:"app.clickup.com",desc:"All-in-one project management and productivity.",r:4.7,cat:"Productivity",p:1},
{id:31,name:"Asana",url:"app.asana.com",desc:"Manage team projects and tasks efficiently.",r:4.6,cat:"Productivity",p:1},
{id:32,name:"Trello",url:"trello.com/app",desc:"Visual boards for organizing any project.",r:4.5,cat:"Productivity",p:1},
{id:33,name:"Airtable",url:"airtable.com",desc:"Spreadsheet-database hybrid for team workflows.",r:4.7,cat:"Productivity",p:1},
{id:34,name:"Zapier",url:"zapier.com/app/dashboard",desc:"Automate workflows between your favorite apps.",r:4.7,cat:"Productivity",p:1},
{id:35,name:"Monday.com",url:"monday.com",desc:"Work OS to manage teams and projects.",r:4.6,cat:"Productivity",p:1},
{id:36,name:"Confluence",url:"confluence.atlassian.com",desc:"Team wiki and knowledge management by Atlassian.",r:4.4,cat:"Productivity",p:1},
{id:37,name:"Google Drive",url:"drive.google.com",desc:"Cloud storage and file sharing by Google.",r:4.7,cat:"Productivity",p:1},
{id:38,name:"WhatsApp",url:"web.whatsapp.com",desc:"Fast and private messaging app by Meta.",r:4.8,cat:"Communication",p:1},
{id:39,name:"Telegram",url:"web.telegram.org",desc:"Secure and fast cloud-based messaging app.",r:4.8,cat:"Communication",p:1},
{id:40,name:"Signal",url:"signal.org",desc:"Private end-to-end encrypted messaging app.",r:4.9,cat:"Communication",p:1},
{id:41,name:"Discord",url:"discord.com/channels/@me",desc:"Voice, video, and text for communities.",r:4.8,cat:"Communication",p:1},
{id:42,name:"Slack",url:"app.slack.com",desc:"Team messaging and collaboration platform.",r:4.7,cat:"Communication",p:1},
{id:43,name:"Zoom",url:"zoom.us",desc:"Video conferencing and virtual meetings.",r:4.6,cat:"Communication",p:1},
{id:44,name:"Microsoft Teams",url:"teams.microsoft.com",desc:"Chat, meet, and collaborate with your team.",r:4.5,cat:"Communication",p:1},
{id:45,name:"Google Meet",url:"meet.google.com",desc:"Secure video meetings by Google Workspace.",r:4.6,cat:"Communication",p:1},
{id:46,name:"Gmail",url:"mail.google.com",desc:"Google's powerful and widely used email service.",r:4.7,cat:"Email",p:1},
{id:47,name:"ProtonMail",url:"mail.proton.me",desc:"End-to-end encrypted email for your privacy.",r:4.8,cat:"Email",p:1},
{id:48,name:"YouTube",url:"youtube.com",desc:"World's largest video sharing platform.",r:4.8,cat:"Video & Streaming",p:1},
{id:49,name:"Netflix",url:"netflix.com/browse",desc:"Stream movies and TV shows on demand.",r:4.6,cat:"Video & Streaming",p:1},
{id:50,name:"Twitch",url:"twitch.tv",desc:"Live streaming platform for gaming and more.",r:4.5,cat:"Video & Streaming",p:1},
{id:51,name:"Spotify",url:"open.spotify.com",desc:"Stream music, podcasts, and audiobooks.",r:4.8,cat:"Music",p:1},
{id:52,name:"Suno",url:"suno.com",desc:"AI music generation from text prompts.",r:4.7,cat:"AI Tools",p:1},
{id:53,name:"Midjourney",url:"midjourney.com",desc:"AI art generation from text descriptions.",r:4.8,cat:"AI Tools",p:1},
{id:54,name:"ElevenLabs",url:"elevenlabs.io",desc:"Realistic AI voice cloning and text-to-speech.",r:4.8,cat:"AI Tools",p:1},
{id:55,name:"Runway",url:"runwayml.com",desc:"AI-powered video generation and editing tools.",r:4.7,cat:"AI Tools",p:1},
{id:56,name:"Groq",url:"console.groq.com",desc:"Ultra-fast AI inference API platform.",r:4.8,cat:"AI Tools",p:1},
{id:57,name:"HuggingFace",url:"huggingface.co",desc:"Open-source hub for AI models and datasets.",r:4.9,cat:"AI Tools",p:1},
{id:58,name:"Twitter/X",url:"x.com/home",desc:"Real-time news and social conversations.",r:4.3,cat:"Social Media",p:1},
{id:59,name:"Instagram",url:"instagram.com",desc:"Share photos, reels, and stories socially.",r:4.5,cat:"Social Media",p:1},
{id:60,name:"LinkedIn",url:"linkedin.com/feed",desc:"Professional network for jobs and careers.",r:4.6,cat:"Social Media",p:1},
{id:61,name:"Facebook",url:"facebook.com",desc:"Connect with friends, family, and groups.",r:4.2,cat:"Social Media",p:1},
{id:62,name:"TikTok",url:"tiktok.com",desc:"Short-form video platform for creators.",r:4.4,cat:"Social Media",p:1},
{id:63,name:"Pinterest",url:"pinterest.com",desc:"Discover and save ideas for inspiration.",r:4.5,cat:"Social Media",p:1},
{id:64,name:"Reddit",url:"reddit.com",desc:"Communities for every topic and interest.",r:4.6,cat:"Social Media",p:1},
{id:65,name:"TryHackMe",url:"tryhackme.com",desc:"Learn cybersecurity with hands-on challenges.",r:4.9,cat:"Cyber Security",p:1},
{id:66,name:"Stripe Dashboard",url:"dashboard.stripe.com",desc:"Manage payments, billing, and subscriptions.",r:4.8,cat:"Finance & Crypto",p:1},
{id:67,name:"Binance",url:"binance.com/en/trade",desc:"World's largest crypto trading exchange.",r:4.5,cat:"Finance & Crypto",p:1},
{id:68,name:"Coinbase",url:"coinbase.com",desc:"Buy, sell, and manage cryptocurrency easily.",r:4.6,cat:"Finance & Crypto",p:1},
{id:69,name:"TradingView",url:"tradingview.com",desc:"Advanced charting and trading analysis tools.",r:4.8,cat:"Finance & Crypto",p:1},
{id:70,name:"AWS Console",url:"console.aws.amazon.com",desc:"Manage all Amazon Web Services resources.",r:4.7,cat:"DevOps & Infra",p:1},
{id:71,name:"GCP Console",url:"console.cloud.google.com",desc:"Manage Google Cloud Platform infrastructure.",r:4.7,cat:"DevOps & Infra",p:1},
{id:72,name:"Azure Portal",url:"portal.azure.com",desc:"Manage Microsoft Azure cloud resources.",r:4.6,cat:"DevOps & Infra",p:1},
{id:73,name:"Jira",url:"jira.atlassian.com",desc:"Issue and project tracking for dev teams.",r:4.5,cat:"Project Management",p:1},
{id:74,name:"Shopify",url:"shopify.com",desc:"Build and manage your online store.",r:4.7,cat:"E-commerce",p:1},
{id:75,name:"WordPress.com",url:"wordpress.com",desc:"Create blogs and websites with ease.",r:4.5,cat:"Writing & Blogging",p:1},
{id:76,name:"Coursera",url:"coursera.org",desc:"Online courses from top universities worldwide.",r:4.7,cat:"Education & Learning",p:1},
{id:77,name:"freeCodeCamp",url:"freecodecamp.org",desc:"Free coding curriculum and certifications.",r:4.9,cat:"Education & Learning",p:1},
{id:78,name:"Google Analytics",url:"analytics.google.com",desc:"Track and analyze website traffic data.",r:4.7,cat:"Analytics",p:1},
{id:79,name:"Sentry",url:"sentry.io",desc:"Monitor and fix application errors in real time.",r:4.7,cat:"Analytics",p:1},
{id:80,name:"Brave",url:"brave.com",desc:"Privacy-first browser with built-in ad blocking.",r:4.7,cat:"VPN & Privacy",p:1},
/* ── Google Apps ── */
{id:81,name:"Google",url:"google.com",desc:"World's most used search engine.",r:4.9,cat:"Utilities & Tools",p:1},
{id:82,name:"Google Maps",url:"maps.google.com",desc:"Navigate anywhere with Google Maps.",r:4.8,cat:"Travel & Maps",p:1},
{id:83,name:"Google Docs",url:"docs.google.com",desc:"Create and edit documents online with Google.",r:4.8,cat:"Documents & Office",p:1},
{id:84,name:"Google Sheets",url:"sheets.google.com",desc:"Create and edit spreadsheets online.",r:4.8,cat:"Documents & Office",p:1},
{id:85,name:"Google Slides",url:"slides.google.com",desc:"Create and present slideshows online.",r:4.7,cat:"Documents & Office",p:1},
{id:86,name:"Google Calendar",url:"calendar.google.com",desc:"Schedule and manage your time with Google.",r:4.8,cat:"Productivity",p:1},
{id:87,name:"Google Photos",url:"photos.google.com",desc:"Store and organize your photos automatically.",r:4.7,cat:"Photography",p:1},
{id:88,name:"Google Translate",url:"translate.google.com",desc:"Translate text and speech in 100+ languages.",r:4.7,cat:"Language & Translation",p:1},
{id:89,name:"Google Forms",url:"forms.google.com",desc:"Build surveys and forms with Google.",r:4.6,cat:"Documents & Office",p:1},
{id:90,name:"Google Classroom",url:"classroom.google.com",desc:"Virtual classroom platform for students and teachers.",r:4.6,cat:"Education & Learning",p:1},
{id:91,name:"Google Keep",url:"keep.google.com",desc:"Quick notes, lists, and reminders from Google.",r:4.6,cat:"Productivity",p:1},
{id:92,name:"Google News",url:"news.google.com",desc:"Personalized news from trusted sources.",r:4.5,cat:"News & Media",p:1},
{id:93,name:"Google Ads",url:"ads.google.com",desc:"Advertise your business across Google's network.",r:4.5,cat:"Marketing & SEO",p:1},
{id:94,name:"Search Console",url:"search.google.com/search-console",desc:"Monitor your site's search performance.",r:4.7,cat:"Marketing & SEO",p:1},
{id:95,name:"Google Play",url:"play.google.com",desc:"Apps, games, movies, and books by Google.",r:4.5,cat:"Utilities & Tools",p:1},
/* ── Microsoft Apps ── */
{id:96,name:"Microsoft 365",url:"microsoft365.com",desc:"Suite of productivity apps by Microsoft.",r:4.7,cat:"Documents & Office",p:1},
{id:97,name:"Word Online",url:"microsoft365.com/launch/word",desc:"Create and edit Word documents in the browser.",r:4.7,cat:"Documents & Office",p:1},
{id:98,name:"Excel Online",url:"microsoft365.com/launch/excel",desc:"Build and edit spreadsheets online.",r:4.7,cat:"Documents & Office",p:1},
{id:99,name:"PowerPoint",url:"microsoft365.com/launch/powerpoint",desc:"Create presentations in the browser.",r:4.6,cat:"Documents & Office",p:1},
{id:100,name:"OneDrive",url:"onedrive.live.com",desc:"Microsoft's cloud storage for your files.",r:4.6,cat:"Cloud Storage",p:1},
{id:101,name:"OneNote",url:"onenote.com",desc:"Digital notebook for capturing ideas and notes.",r:4.6,cat:"Productivity",p:1},
{id:102,name:"Outlook",url:"outlook.live.com",desc:"Email and calendar by Microsoft.",r:4.6,cat:"Email",p:1},
{id:103,name:"SharePoint",url:"sharepoint.com",desc:"Collaborate and share content across teams.",r:4.4,cat:"Productivity",p:1},
{id:104,name:"Bing",url:"bing.com",desc:"Microsoft's web search engine.",r:4.3,cat:"Utilities & Tools",p:1},
{id:105,name:"Skype",url:"web.skype.com",desc:"Free video and voice calls online.",r:4.2,cat:"Communication",p:1},
{id:106,name:"GitHub Copilot",url:"github.com/copilot",desc:"AI pair programmer integrated into your editor.",r:4.8,cat:"AI Tools",p:1},
{id:107,name:"Azure DevOps",url:"dev.azure.com",desc:"Plan, develop, test, and ship code faster.",r:4.6,cat:"DevOps & Infra",p:1},
{id:108,name:"Microsoft Store",url:"apps.microsoft.com",desc:"Apps and games for Windows.",r:4.3,cat:"Utilities & Tools",p:1},
];
