window.WS_TOOLS = [
// Code & Editors
{name:"VS Code Web",url:"vscode.dev",desc:"Full VS Code editor running in the browser.",cat:"Code & Editors"},
{name:"Cursor",url:"cursor.com",desc:"AI-first code editor built on VS Code.",cat:"Code & Editors"},
{name:"Zed",url:"zed.dev",desc:"High-performance multiplayer code editor.",cat:"Code & Editors"},
{name:"StackBlitz",url:"stackblitz.com",desc:"Online IDE with Node.js runtime in browser.",cat:"Code & Editors"},
{name:"CodeSandbox",url:"codesandbox.io",desc:"Instant cloud dev environments for web.",cat:"Code & Editors"},
{name:"Gitpod",url:"gitpod.io",desc:"Ephemeral cloud dev environments from git.",cat:"Code & Editors"},
{name:"Replit",url:"replit.com",desc:"Collaborative browser-based coding platform.",cat:"Code & Editors"},
{name:"GitHub Codespaces",url:"github.com/codespaces",desc:"Full VS Code dev environment in the cloud.",cat:"Code & Editors"},
{name:"CodePen",url:"codepen.io",desc:"Frontend playground with live HTML/CSS/JS.",cat:"Code & Editors"},
{name:"JSFiddle",url:"jsfiddle.net",desc:"Quick JavaScript and HTML testing sandbox.",cat:"Code & Editors"},
{name:"Glitch",url:"glitch.com",desc:"Collaborative coding with instant deployment.",cat:"Code & Editors"},
// Version Control
{name:"GitHub",url:"github.com",desc:"World's largest code hosting and collaboration.",cat:"Version Control"},
{name:"GitLab",url:"gitlab.com",desc:"DevSecOps platform with built-in CI/CD.",cat:"Version Control"},
{name:"Bitbucket",url:"bitbucket.org",desc:"Git hosting with Jira and Trello integration.",cat:"Version Control"},
{name:"Gitea",url:"gitea.io",desc:"Lightweight self-hosted Git service.",cat:"Version Control"},
{name:"Codeberg",url:"codeberg.org",desc:"Non-profit community Git hosting platform.",cat:"Version Control"},
{name:"Sourcehut",url:"sr.ht",desc:"Minimalist open-source software forge.",cat:"Version Control"},
{name:"Perforce",url:"perforce.com",desc:"Enterprise version control for large assets.",cat:"Version Control"},
{name:"Plastic SCM",url:"plasticscm.com",desc:"Version control for game and large assets.",cat:"Version Control"},
{name:"GitHub Desktop",url:"desktop.github.com",desc:"Visual Git client for GitHub repositories.",cat:"Version Control"},
// APIs & Testing
{name:"Postman",url:"postman.com",desc:"API design, testing, and documentation tool.",cat:"APIs & Testing"},
{name:"Hoppscotch",url:"hoppscotch.io",desc:"Open-source lightweight API testing tool.",cat:"APIs & Testing"},
{name:"Insomnia",url:"insomnia.rest",desc:"API client for REST, GraphQL, and gRPC.",cat:"APIs & Testing"},
{name:"Bruno",url:"usebruno.com",desc:"Fast Git-friendly offline API client.",cat:"APIs & Testing"},
{name:"Thunder Client",url:"thunderclient.com",desc:"Lightweight VS Code REST API client.",cat:"APIs & Testing"},
{name:"RapidAPI",url:"rapidapi.com",desc:"API marketplace and testing hub.",cat:"APIs & Testing"},
{name:"Swagger Editor",url:"editor.swagger.io",desc:"Design and document APIs with OpenAPI spec.",cat:"APIs & Testing"},
{name:"Paw",url:"paw.cloud",desc:"Full-featured Mac-native API client.",cat:"APIs & Testing"},
{name:"Mockoon",url:"mockoon.com",desc:"Mock REST APIs locally without backend.",cat:"APIs & Testing"},
{name:"HTTPie",url:"httpie.io",desc:"User-friendly HTTP client for APIs.",cat:"APIs & Testing"},
// Databases
{name:"Supabase",url:"supabase.com",desc:"Open-source Firebase alternative with Postgres.",cat:"Databases"},
{name:"PlanetScale",url:"planetscale.com",desc:"Serverless MySQL with branching workflows.",cat:"Databases"},
{name:"Neon",url:"neon.tech",desc:"Serverless Postgres with branching and scale.",cat:"Databases"},
{name:"MongoDB Atlas",url:"cloud.mongodb.com",desc:"Fully managed MongoDB cloud database.",cat:"Databases"},
{name:"Redis Cloud",url:"redis.com/cloud",desc:"Fully managed Redis database as a service.",cat:"Databases"},
{name:"Turso",url:"turso.tech",desc:"SQLite at the edge with libSQL protocol.",cat:"Databases"},
{name:"Prisma",url:"prisma.io",desc:"Next-gen ORM for Node.js and TypeScript.",cat:"Databases"},
{name:"CockroachDB",url:"cockroachlabs.com",desc:"Distributed SQL database for global apps.",cat:"Databases"},
{name:"Xata",url:"xata.io",desc:"Serverless database platform with search.",cat:"Databases"},
{name:"Fauna",url:"fauna.com",desc:"Distributed document-relational serverless DB.",cat:"Databases"},
{name:"Upstash",url:"upstash.com",desc:"Serverless Redis and Kafka for edge apps.",cat:"Databases"},
// Cloud & Infra
{name:"Vercel",url:"vercel.com",desc:"Frontend cloud for frameworks and edge.",cat:"Cloud & Infra"},
{name:"Netlify",url:"netlify.com",desc:"Composable web platform for modern apps.",cat:"Cloud & Infra"},
{name:"Railway",url:"railway.app",desc:"Deploy anything from GitHub instantly.",cat:"Cloud & Infra"},
{name:"Render",url:"render.com",desc:"Unified cloud for apps, sites, and services.",cat:"Cloud & Infra"},
{name:"Fly.io",url:"fly.io",desc:"Run full-stack apps and databases near users.",cat:"Cloud & Infra"},
{name:"Cloudflare",url:"cloudflare.com",desc:"CDN, security, and edge computing platform.",cat:"Cloud & Infra"},
{name:"AWS",url:"aws.amazon.com",desc:"Amazon's comprehensive cloud services.",cat:"Cloud & Infra"},
{name:"GCP",url:"cloud.google.com",desc:"Google's suite of cloud computing services.",cat:"Cloud & Infra"},
{name:"Azure",url:"azure.microsoft.com",desc:"Microsoft's cloud computing platform.",cat:"Cloud & Infra"},
{name:"DigitalOcean",url:"digitalocean.com",desc:"Developer-friendly cloud infrastructure.",cat:"Cloud & Infra"},
{name:"Hetzner Cloud",url:"console.hetzner.cloud",desc:"Affordable German cloud with great performance.",cat:"Cloud & Infra"},
{name:"Coolify",url:"coolify.io",desc:"Open-source self-hosted Heroku/Netlify alternative.",cat:"Cloud & Infra"},
// CI/CD
{name:"GitHub Actions",url:"github.com/features/actions",desc:"Automate CI/CD directly in GitHub repos.",cat:"CI/CD"},
{name:"CircleCI",url:"circleci.com",desc:"Fast and flexible CI/CD pipeline platform.",cat:"CI/CD"},
{name:"Jenkins",url:"jenkins.io",desc:"Open-source automation server for CI/CD.",cat:"CI/CD"},
{name:"Buildkite",url:"buildkite.com",desc:"Fast hybrid CI using your own agents.",cat:"CI/CD"},
{name:"GitLab CI",url:"docs.gitlab.com/ee/ci",desc:"Native CI/CD built into GitLab platform.",cat:"CI/CD"},
{name:"Travis CI",url:"travis-ci.com",desc:"Hosted CI service for open-source projects.",cat:"CI/CD"},
{name:"Drone CI",url:"drone.io",desc:"Container-native CI/CD platform.",cat:"CI/CD"},
{name:"Woodpecker CI",url:"woodpecker-ci.org",desc:"Community fork of Drone CI server.",cat:"CI/CD"},
{name:"Dagger",url:"dagger.io",desc:"Portable CI/CD pipelines as code.",cat:"CI/CD"},
{name:"Earthly",url:"earthly.dev",desc:"Repeatable CI builds with Dockerfile syntax.",cat:"CI/CD"},
// Monitoring
{name:"Sentry",url:"sentry.io",desc:"Error tracking and performance monitoring.",cat:"Monitoring"},
{name:"Datadog",url:"datadoghq.com",desc:"Full-stack cloud monitoring and observability.",cat:"Monitoring"},
{name:"PostHog",url:"posthog.com",desc:"Open-source product analytics platform.",cat:"Monitoring"},
{name:"Plausible",url:"plausible.io",desc:"Privacy-friendly lightweight analytics.",cat:"Monitoring"},
{name:"Grafana",url:"grafana.com",desc:"Open observability dashboards and alerting.",cat:"Monitoring"},
{name:"New Relic",url:"newrelic.com",desc:"Observability platform for all your systems.",cat:"Monitoring"},
{name:"Prometheus",url:"prometheus.io",desc:"Open-source monitoring with time-series DB.",cat:"Monitoring"},
{name:"Better Uptime",url:"betterstack.com",desc:"Uptime monitoring with beautiful status pages.",cat:"Monitoring"},
{name:"UptimeRobot",url:"uptimerobot.com",desc:"Free website uptime monitoring service.",cat:"Monitoring"},
{name:"LogRocket",url:"logrocket.com",desc:"Session replay and frontend performance.",cat:"Monitoring"},
// AI & ML APIs
{name:"OpenAI API",url:"platform.openai.com",desc:"GPT and DALL-E models via REST API.",cat:"AI & ML APIs"},
{name:"Anthropic API",url:"console.anthropic.com",desc:"Claude AI models for enterprise and devs.",cat:"AI & ML APIs"},
{name:"Google AI Studio",url:"aistudio.google.com",desc:"Gemini models API and prototyping tool.",cat:"AI & ML APIs"},
{name:"Groq",url:"console.groq.com",desc:"Ultra-fast LLM inference via GroqCloud.",cat:"AI & ML APIs"},
{name:"Together AI",url:"api.together.xyz",desc:"Run open-source LLMs with fast inference.",cat:"AI & ML APIs"},
{name:"Replicate",url:"replicate.com",desc:"Run ML models in the cloud via API.",cat:"AI & ML APIs"},
{name:"Mistral AI",url:"console.mistral.ai",desc:"European AI with efficient open models.",cat:"AI & ML APIs"},
{name:"Cohere",url:"cohere.com",desc:"Enterprise NLP APIs for search and generate.",cat:"AI & ML APIs"},
{name:"HuggingFace Inference",url:"huggingface.co/inference-api",desc:"Host and run ML models via simple API.",cat:"AI & ML APIs"},
{name:"Perplexity API",url:"docs.perplexity.ai",desc:"Search-grounded LLM API for real-time info.",cat:"AI & ML APIs"},
// Auth & Identity
{name:"Clerk",url:"clerk.com",desc:"Drop-in auth with UI components for React.",cat:"Auth & Identity"},
{name:"Auth0",url:"auth0.com",desc:"Flexible enterprise identity platform.",cat:"Auth & Identity"},
{name:"Firebase Auth",url:"firebase.google.com/products/auth",desc:"Google's free authentication service.",cat:"Auth & Identity"},
{name:"Okta",url:"okta.com",desc:"Enterprise identity and access management.",cat:"Auth & Identity"},
{name:"SuperTokens",url:"supertokens.com",desc:"Open-source authentication alternative.",cat:"Auth & Identity"},
{name:"Lucia",url:"lucia-auth.com",desc:"Simple auth library for TypeScript apps.",cat:"Auth & Identity"},
{name:"NextAuth.js",url:"next-auth.js.org",desc:"Authentication for Next.js applications.",cat:"Auth & Identity"},
{name:"Kinde",url:"kinde.com",desc:"Modern auth with powerful admin dashboard.",cat:"Auth & Identity"},
{name:"WorkOS",url:"workos.com",desc:"Enterprise SSO and directory sync API.",cat:"Auth & Identity"},
{name:"Stytch",url:"stytch.com",desc:"Flexible auth APIs with magic links/passkeys.",cat:"Auth & Identity"},
// Payments
{name:"Stripe",url:"stripe.com",desc:"Complete payment processing for the internet.",cat:"Payments"},
{name:"Paddle",url:"paddle.com",desc:"Merchant of record for SaaS billing globally.",cat:"Payments"},
{name:"LemonSqueezy",url:"lemonsqueezyhq.com",desc:"Payments and subscriptions for indie devs.",cat:"Payments"},
{name:"Braintree",url:"braintree.com",desc:"PayPal's full-stack payments platform.",cat:"Payments"},
{name:"Adyen",url:"adyen.com",desc:"Global enterprise payments infrastructure.",cat:"Payments"},
{name:"Razorpay",url:"razorpay.com",desc:"India's leading payment gateway platform.",cat:"Payments"},
{name:"Paystack",url:"paystack.com",desc:"Payment gateway for African businesses.",cat:"Payments"},
{name:"Mollie",url:"mollie.com",desc:"European payment service provider.",cat:"Payments"},
{name:"Square",url:"squareup.com",desc:"Point-of-sale and online payment tools.",cat:"Payments"},
{name:"Recurly",url:"recurly.com",desc:"Subscription management and billing platform.",cat:"Payments"},
// Communication APIs
{name:"Resend",url:"resend.com",desc:"Email API built for modern developers.",cat:"Communication APIs"},
{name:"SendGrid",url:"sendgrid.com",desc:"Scalable email delivery API by Twilio.",cat:"Communication APIs"},
{name:"Twilio",url:"twilio.com",desc:"Cloud communications API for SMS/voice.",cat:"Communication APIs"},
{name:"Vonage",url:"vonage.com",desc:"Cloud communication APIs for any app.",cat:"Communication APIs"},
{name:"Mailgun",url:"mailgun.com",desc:"Transactional email API for developers.",cat:"Communication APIs"},
{name:"Pusher",url:"pusher.com",desc:"Real-time WebSocket messaging API.",cat:"Communication APIs"},
{name:"Ably",url:"ably.com",desc:"Pub/sub messaging and realtime data APIs.",cat:"Communication APIs"},
{name:"Novu",url:"novu.co",desc:"Open-source notification infrastructure API.",cat:"Communication APIs"},
{name:"Knock",url:"knock.app",desc:"Flexible notification workflows API.",cat:"Communication APIs"},
{name:"Courier",url:"courier.com",desc:"Multi-channel notification delivery API.",cat:"Communication APIs"},
// Search & Vector
{name:"Algolia",url:"algolia.com",desc:"Hosted search API with sub-10ms results.",cat:"Search & Vector"},
{name:"Typesense",url:"typesense.org",desc:"Open-source typo-tolerant search engine.",cat:"Search & Vector"},
{name:"Pinecone",url:"pinecone.io",desc:"Managed vector database for AI applications.",cat:"Search & Vector"},
{name:"Weaviate",url:"weaviate.io",desc:"Open-source vector search engine.",cat:"Search & Vector"},
{name:"Qdrant",url:"qdrant.tech",desc:"High-performance open-source vector DB.",cat:"Search & Vector"},
{name:"Meilisearch",url:"meilisearch.com",desc:"Lightning-fast open-source search engine.",cat:"Search & Vector"},
{name:"Elastic",url:"elastic.co",desc:"Search and observability powered by ELK.",cat:"Search & Vector"},
{name:"Chroma",url:"trychroma.com",desc:"Open-source embeddings vector database.",cat:"Search & Vector"},
{name:"pgvector",url:"github.com/pgvector/pgvector",desc:"Open-source vector similarity search for Postgres.",cat:"Search & Vector"},
{name:"LanceDB",url:"lancedb.com",desc:"Serverless vector database for AI apps.",cat:"Search & Vector"},
// Storage & CDN
{name:"Cloudflare R2",url:"cloudflare.com/products/r2",desc:"Zero-egress object storage at any scale.",cat:"Storage & CDN"},
{name:"AWS S3",url:"aws.amazon.com/s3",desc:"Industry-standard scalable object storage.",cat:"Storage & CDN"},
{name:"Uploadthing",url:"uploadthing.com",desc:"Simple file upload API for full-stack apps.",cat:"Storage & CDN"},
{name:"Bunny CDN",url:"bunny.net",desc:"Fast and affordable global CDN network.",cat:"Storage & CDN"},
{name:"Cloudinary",url:"cloudinary.com",desc:"Media management with AI transforms and CDN.",cat:"Storage & CDN"},
{name:"Imgix",url:"imgix.com",desc:"Real-time image optimization and delivery.",cat:"Storage & CDN"},
{name:"Backblaze B2",url:"backblaze.com/b2",desc:"S3-compatible affordable cloud object storage.",cat:"Storage & CDN"},
{name:"Wasabi",url:"wasabi.com",desc:"Hot cloud storage 80% cheaper than AWS.",cat:"Storage & CDN"},
{name:"Storj",url:"storj.io",desc:"Decentralized encrypted S3-compatible storage.",cat:"Storage & CDN"},
{name:"Supabase Storage",url:"supabase.com/storage",desc:"S3-compatible object storage with Postgres.",cat:"Storage & CDN"},
// Documentation
{name:"Mintlify",url:"mintlify.com",desc:"Beautiful docs that developers love to read.",cat:"Documentation"},
{name:"GitBook",url:"gitbook.com",desc:"Modern docs platform for teams and products.",cat:"Documentation"},
{name:"ReadMe",url:"readme.com",desc:"Developer hub for API docs and guides.",cat:"Documentation"},
{name:"MDN",url:"developer.mozilla.org",desc:"Mozilla's authoritative web developer docs.",cat:"Documentation"},
{name:"DevDocs",url:"devdocs.io",desc:"Unified API docs for all languages offline.",cat:"Documentation"},
{name:"Docusaurus",url:"docusaurus.io",desc:"Build optimized documentation websites.",cat:"Documentation"},
{name:"Nextra",url:"nextra.site",desc:"Next.js docs theme with MDX support.",cat:"Documentation"},
{name:"Starlight",url:"starlight.astro.build",desc:"Astro documentation site builder.",cat:"Documentation"},
{name:"Swagger UI",url:"swagger.io/tools/swagger-ui",desc:"Visualize and interact with OpenAPI specs.",cat:"Documentation"},
{name:"Stoplight",url:"stoplight.io",desc:"API design, documentation, and mocking.",cat:"Documentation"},
// Design Systems
{name:"Tailwind UI",url:"tailwindui.com",desc:"Premium Tailwind CSS component library.",cat:"Design Systems"},
{name:"shadcn/ui",url:"ui.shadcn.com",desc:"Copy-paste React components with Radix.",cat:"Design Systems"},
{name:"Radix UI",url:"radix-ui.com",desc:"Unstyled accessible React component primitives.",cat:"Design Systems"},
{name:"Mantine",url:"mantine.dev",desc:"Full-featured React component library.",cat:"Design Systems"},
{name:"Framer Motion",url:"framer.com/motion",desc:"Production-ready animation library for React.",cat:"Design Systems"},
{name:"Chakra UI",url:"chakra-ui.com",desc:"Simple and accessible React component library.",cat:"Design Systems"},
{name:"Headless UI",url:"headlessui.com",desc:"Unstyled accessible UI components by Tailwind.",cat:"Design Systems"},
{name:"DaisyUI",url:"daisyui.com",desc:"Tailwind CSS component plugin library.",cat:"Design Systems"},
{name:"Ant Design",url:"ant.design",desc:"Enterprise-level React component system.",cat:"Design Systems"},
{name:"MUI",url:"mui.com",desc:"React components implementing Material Design.",cat:"Design Systems"},
// Security
{name:"Snyk",url:"snyk.io",desc:"Find and fix vulnerabilities in your code.",cat:"Security"},
{name:"Socket.dev",url:"socket.dev",desc:"Protect against supply chain attacks in npm.",cat:"Security"},
{name:"OWASP ZAP",url:"zaproxy.org",desc:"Open-source web application security scanner.",cat:"Security"},
{name:"1Password",url:"1password.com",desc:"Password manager for teams and developers.",cat:"Security"},
{name:"Bitwarden",url:"bitwarden.com",desc:"Open-source password manager for everyone.",cat:"Security"},
{name:"HaveIBeenPwned",url:"haveibeenpwned.com",desc:"Check if your email has been compromised.",cat:"Security"},
{name:"SecurityHeaders",url:"securityheaders.com",desc:"Analyze HTTP security headers of websites.",cat:"Security"},
{name:"SSL Labs",url:"ssllabs.com/ssltest",desc:"Deep analysis of SSL/TLS configuration.",cat:"Security"},
{name:"Dependabot",url:"docs.github.com/dependabot",desc:"Automated dependency security updates.",cat:"Security"},
{name:"Trivy",url:"trivy.dev",desc:"Container and IaC vulnerability scanner.",cat:"Security"},
// Performance
{name:"WebPageTest",url:"webpagetest.org",desc:"Advanced web performance testing globally.",cat:"Performance"},
{name:"GTmetrix",url:"gtmetrix.com",desc:"Analyze and optimize web page performance.",cat:"Performance"},
{name:"Lighthouse",url:"pagespeed.web.dev",desc:"Google's automated web performance auditing.",cat:"Performance"},
{name:"k6",url:"k6.io",desc:"Open-source load testing tool for APIs.",cat:"Performance"},
{name:"Artillery",url:"artillery.io",desc:"Cloud-scale performance testing platform.",cat:"Performance"},
{name:"Locust",url:"locust.io",desc:"Open-source Python load testing framework.",cat:"Performance"},
{name:"BrowserStack",url:"browserstack.com",desc:"Cross-browser testing on real devices.",cat:"Performance"},
{name:"Playwright",url:"playwright.dev",desc:"Reliable end-to-end browser test automation.",cat:"Performance"},
{name:"Checkly",url:"checklyhq.com",desc:"Monitoring as code for APIs and web apps.",cat:"Performance"},
{name:"SpeedCurve",url:"speedcurve.com",desc:"Monitor and improve frontend performance.",cat:"Performance"},
// DNS & Domains
{name:"Namecheap",url:"namecheap.com",desc:"Affordable domain registration and DNS.",cat:"DNS & Domains"},
{name:"Porkbun",url:"porkbun.com",desc:"Low-cost domains with free privacy protection.",cat:"DNS & Domains"},
{name:"Cloudflare DNS",url:"dash.cloudflare.com",desc:"Fast and free authoritative DNS service.",cat:"DNS & Domains"},
{name:"Google Domains",url:"domains.google",desc:"Google's domain registration service.",cat:"DNS & Domains"},
{name:"Dynadot",url:"dynadot.com",desc:"Domain registrar with solid management tools.",cat:"DNS & Domains"},
{name:"Gandi",url:"gandi.net",desc:"Domain registrar with included privacy.",cat:"DNS & Domains"},
{name:"DNSimple",url:"dnsimple.com",desc:"Simple DNS management for developers.",cat:"DNS & Domains"},
{name:"NS1",url:"ns1.com",desc:"Intelligent DNS and traffic management.",cat:"DNS & Domains"},
{name:"MXToolbox",url:"mxtoolbox.com",desc:"DNS lookup, email header, and network tools.",cat:"DNS & Domains"},
{name:"WhoisFreaks",url:"whoisfreaks.com",desc:"WHOIS lookup and domain intelligence API.",cat:"DNS & Domains"},
// Localization
{name:"Crowdin",url:"crowdin.com",desc:"Cloud localization platform for teams.",cat:"Localization"},
{name:"Lokalise",url:"lokalise.com",desc:"Translation management for mobile and web.",cat:"Localization"},
{name:"i18next",url:"i18next.com",desc:"Internationalization framework for JavaScript.",cat:"Localization"},
{name:"Phrase",url:"phrase.com",desc:"Translation management with GitHub sync.",cat:"Localization"},
{name:"Transifex",url:"transifex.com",desc:"Localization platform with AI translation.",cat:"Localization"},
{name:"Weblate",url:"weblate.org",desc:"Open-source web-based translation tool.",cat:"Localization"},
{name:"Loco",url:"localise.biz",desc:"Translation management for developers.",cat:"Localization"},
{name:"Pontoon",url:"pontoon.mozilla.org",desc:"Mozilla's open-source localization platform.",cat:"Localization"},
{name:"FormatJS",url:"formatjs.io",desc:"Internationalize web apps with React Intl.",cat:"Localization"},
// Error Tracking
{name:"Sentry",url:"sentry.io",desc:"Error monitoring and performance tracking.",cat:"Error Tracking"},
{name:"Rollbar",url:"rollbar.com",desc:"Real-time error monitoring and deploy tracking.",cat:"Error Tracking"},
{name:"Bugsnag",url:"bugsnag.com",desc:"Application stability monitoring platform.",cat:"Error Tracking"},
{name:"TrackJS",url:"trackjs.com",desc:"JavaScript error monitoring for web apps.",cat:"Error Tracking"},
{name:"Honeybadger",url:"honeybadger.io",desc:"Exception, uptime, and cron job monitoring.",cat:"Error Tracking"},
{name:"Airbrake",url:"airbrake.io",desc:"Error and performance monitoring service.",cat:"Error Tracking"},
{name:"Raygun",url:"raygun.com",desc:"Crash reporting and performance monitoring.",cat:"Error Tracking"},
{name:"LogRocket",url:"logrocket.com",desc:"Session replay with error and performance.",cat:"Error Tracking"},
{name:"Highlight.io",url:"highlight.io",desc:"Open-source full-stack monitoring platform.",cat:"Error Tracking"},
{name:"GlitchTip",url:"glitchtip.com",desc:"Open-source Sentry-compatible error tracker.",cat:"Error Tracking"},
];
